#!/bin/bash
T="/tmp"
D="/"
FILESDIR="/usr/share/setiathome-updater"

echo -e " \e[32m*\e[0m Updating setiathome configuration files..."
[ -e /var/lib/boinc/projects/setiathome.berkeley.edu/app_info.xml_sah_cpu ] && echo -e " \e[32m*\e[0m Updating setiathome-cpu..." && cp /var/lib/boinc/projects/setiathome.berkeley.edu/app_info.xml_sah_cpu "${T}"
[ -e /var/lib/boinc/projects/setiathome.berkeley.edu/app_info.xml_sah_gpu.ocl ] && echo -e " \e[32m*\e[0m Updating setiathome-gpu..." && cp /var/lib/boinc/projects/setiathome.berkeley.edu/app_info.xml_sah_gpu.ocl "${T}"
[ -e /var/lib/boinc/projects/setiathome.berkeley.edu/app_info.xml_ap_cpu ] && echo -e " \e[32m*\e[0m Updating astropulse-cpu..." && cp /var/lib/boinc/projects/setiathome.berkeley.edu/app_info.xml_ap_cpu "${T}"
[ -e /var/lib/boinc/projects/setiathome.berkeley.edu/app_info.xml_ap_gpu.ocl ] && echo -e " \e[32m*\e[0m Updating astropulse-gpu..." && cp /var/lib/boinc/projects/setiathome.berkeley.edu/app_info.xml_ap_gpu.ocl "${T}"

mkdir -p "${D}"/var/lib/boinc/projects/setiathome.berkeley.edu
cat ${FILESDIR}/app_info.xml_start > "${D}"/var/lib/boinc/projects/setiathome.berkeley.edu/app_info.xml
[ -e /var/lib/boinc/projects/setiathome.berkeley.edu/app_info.xml_sah_cpu ] && cat ${T}/app_info.xml_sah_cpu >> "${D}"/var/lib/boinc/projects/setiathome.berkeley.edu/app_info.xml
[ -e /var/lib/boinc/projects/setiathome.berkeley.edu/app_info.xml_sah_gpu.ocl ] && cat ${T}/app_info.xml_sah_gpu.ocl >> "${D}"/var/lib/boinc/projects/setiathome.berkeley.edu/app_info.xml
[ -e /var/lib/boinc/projects/setiathome.berkeley.edu/app_info.xml_ap_cpu ] && cat ${T}/app_info.xml_ap_cpu >> "${D}"/var/lib/boinc/projects/setiathome.berkeley.edu/app_info.xml
[ -e /var/lib/boinc/projects/setiathome.berkeley.edu/app_info.xml_ap_gpu.ocl ] && cat ${T}/app_info.xml_ap_gpu.ocl >> "${D}"/var/lib/boinc/projects/setiathome.berkeley.edu/app_info.xml
cat ${FILESDIR}/app_info.xml_end >> "${D}"/var/lib/boinc/projects/setiathome.berkeley.edu/app_info.xml

echo -e " \e[32m*\e[0m Fixing setiathome.berkeley.edu ownership..."
chown -R boinc:boinc /var/lib/boinc/projects/setiathome.berkeley.edu
echo -e " \e[32m*\e[0m Fixing projects ownership..."
chown boinc:boinc /var/lib/boinc/projects
