#!/bin/bash

NODE_SLOT=@NODE_SLOT@
# Run lhm as the lobehub user
export HOME="/var/lib/lobehub"
export PATH="/usr/lib/node/${NODE_SLOT}/bin:${PATH}"
export LOBEHUB_SERVER=${LOBEHUB_SERVER:-"http://localhost:3210"}
echo "LOBEHUB_SERVER:  ${LOBEHUB_SERVER}"
export LOBEHUB_CLI_HOME=${LOBEHUB_CLI_HOME:-".lobehub"} # Relative to ${HOME}
unset EXTRA_ARGS

cd "/opt/lobehub-cli" || {
    echo "Error: /opt/lobehub-cli directory not found"
    exit 1
}

has_server_flag=0
for arg in "$@"; do
    if [ "$arg" = "--server" ] || [ "$arg" = "-s" ]; then
        has_server_flag=1
        break
    fi
done

has_login_flag=0
for arg in "${@}"; do
	if [[ "${arg}" = "login" ]] ; then
		has_login_flag=1
		break
	fi
done

if (( ${has_server_flag} != 1 && ${has_login_flag} == 1 )) ; then
	EXTRA_ARGS=( --server ${LOBEHUB_SERVER} )
fi

exec sudo -u "lobehub" -g "lobehub" --preserve-env=HOME,LOBEHUB_CLI_HOME,LOBEHUB_SERVER,PATH \
	"node" \
	"dist/index.js" \
	"$@" \
	${EXTRA_ARGS[@]}
