#!/bin/bash
rm log_$(hostname)/*
cp /usr/bin/bfgminer-gpu ./
cp /usr/bin/bfgminer-cpu ./
cp /usr/share/bfgminer/opencl/*.cl ./
cp /usr/share/boinc-server-maker/wrapper/wrapper ./
chown boincadm:boinc *.cl bfgminer-{gpu,cpu}
DBUSER=$(xml sel -t -v "/boinc/config/db_user" config.xml)
DBPASS=$(xml sel -t -v "/boinc/config/db_passwd" config.xml)
DBNAME=$(xml sel -t -v "/boinc/config/db_name" config.xml)

mysql -B -N --user="${DBUSER}" --password="${DBPASS}" -e "SET GLOBAL binlog_format=MIXED;"
mysql -B -N --user="${DBUSER}" --password="${DBPASS}" -e "USE ${DBNAME}; TRUNCATE TABLE app;"
mysql -B -N --user="${DBUSER}" --password="${DBPASS}" -e "USE ${DBNAME}; TRUNCATE TABLE app_version;"
mysql -B -N --user="${DBUSER}" --password="${DBPASS}" -e "USE ${DBNAME}; TRUNCATE TABLE host;"
mysql -B -N --user="${DBUSER}" --password="${DBPASS}" -e "USE ${DBNAME}; TRUNCATE TABLE host_app_version;"
mysql -B -N --user="${DBUSER}" --password="${DBPASS}" -e "USE ${DBNAME}; TRUNCATE TABLE platform;"
mysql -B -N --user="${DBUSER}" --password="${DBPASS}" -e "USE ${DBNAME}; TRUNCATE TABLE profile;"
mysql -B -N --user="${DBUSER}" --password="${DBPASS}" -e "USE ${DBNAME}; TRUNCATE TABLE result;"
mysql -B -N --user="${DBUSER}" --password="${DBPASS}" -e "USE ${DBNAME}; TRUNCATE TABLE user;"
mysql -B -N --user="${DBUSER}" --password="${DBPASS}" -e "USE ${DBNAME}; TRUNCATE TABLE workunit;"

unset DBUSER
unset DBPASS

#xml ed -L -d "/boinc/app/name[text()='example_app']/.." project.xml

rm -rf apps/*
#./update_app wrapper bfgminer "Boinc BFGMiner" 3.10.5 x86_64-pc-linux-gnu 7.4.42 "" 2 "templates/worker_job_nosimd_noocl.xml" "bfgminer-cpu" bfgminer-cpu
./update_app wrapper bfgminer "Boinc BFGMiner" 3.10.5 x86_64-pc-linux-gnu 7.4.42 sse2 2 "templates/worker_job_sse2.xml" "bfgminer-cpu" bfgminer-cpu
#./update_app wrapper bfgminer "Boinc BFGMiner" 3.10.5 x86_64-pc-linux-gnu 7.4.42 sse3 2 "templates/worker_job_sse3.xml" "bfgminer-cpu" bfgminer-cpu
./update_app wrapper bfgminer "Boinc BFGMiner" 3.10.5 x86_64-pc-linux-gnu 7.4.42 opencl_ati5_cat132 2 "templates/worker_job_opencl_ati5_cat132.xml" "bfgminer-gpu" bfgminer-gpu diablo130302.cl  diakgcn121016.cl  phatk121016.cl  poclbm130302.cl  scrypt130511.cl
./make_masterwu wu wu  bfgminer templates/workunit_template.xml templates/results_template.xml 1

./auto_generate_wu wu 10

/etc/init.d/apache2 stop
sleep 5
/etc/init.d/apache2 start
/etc/init.d/boinc stop
sleep 5
/etc/init.d/boinc start
/etc/init.d/boinc-server-eligius stop
sleep 5
/etc/init.d/boinc-server-eligius start

rm *.cl bfgminer-{gpu,cpu}
