#!/bin/bash
if which wmname >/dev/null ; then
	wmname LG3D
fi

if [[ -d "/tmp/sheepit_binary_cache" ]] ; then
	echo "Removing /tmp/sheepit_binary_cache"
	rm -rf "/tmp/sheepit_binary_cache"
	if [[ -d "/tmp/sheepit_binary_cache" ]] ; then
		local u=$(stat -c "%U" /tmp/sheepit_binary_cache)
		local g=$(stat -c "%U" /tmp/sheepit_binary_cache)
		echo "/tmp/sheepit_binary_cache still exists with owner=${u} group=${g}.  Ask ${u} to remove it."
		exit 1
	fi
fi

java -jar /usr/share/sheepit-client/sheepit-client-all.jar $*
