#!/bin/bash
NODE_SLOT="@NODE_SLOT@"
BASE_DIR="/opt/closure-compiler"
export PATH="${BASE_DIR}/node_modules/.bin:${PATH}"
export NODE_PATH="${BASE_DIR}/packages:${NODE_PATH}"
"/usr/lib/node/${NODE_SLOT}/bin/node" "${BASE_DIR}/packages/google-closure-compiler/cli.js" "${@}"
