#!/bin/bash
BASE_DIR="/opt/closure-compiler"
export PATH="${BASE_DIR}/node_modules/.bin:${PATH}"
export NODE_PATH="${BASE_DIR}/packages:${NODE_PATH}"
/usr/bin/node "${BASE_DIR}/packages/google-closure-compiler/cli.js" "${@}"
