#!/bin/bash

fun() {
	local fun_name="${1}"
	grep -q "${fun_name}" "${x}" || echo "missing ${fun_name} for ${x}"
}

main() {
	for x in $(grep -l -r --exclude-dir=.git "epgo" $(find . -name "*.ebuild" -o -name "*.eclass")) ; do
		fun "epgo_setup"
		fun "PGO_PHASE"
		fun "epgo_src_prepare"
		fun "epgo_src_configure"
		fun "epgo_src_install"
		fun "epgo_pkg_postinst"
	done
}
main
