#!/bin/bash

fun() {
	local fun_name="${1}"
	grep -q "${fun_name}" "${x}" || echo "missing ${fun_name} for ${x}"
}

main() {
	for x in $(grep -l -r --exclude-dir=.git "ebolt" $(find . -name "*.ebuild" -o -name "*.eclass")) ; do
		fun "ebolt_setup"
		fun "BOLT_PHASE"
		fun "ebolt_src_prepare"
		fun "ebolt_src_configure"
		fun "ebolt_src_install"
		fun "ebolt_pkg_postinst"
	done
}
main
