#!/bin/bash
EPREFIX=__EPREFIX__
ACTIVE_VERSION=$(grep -r -e "#define NODE_MAJOR_VERSION" \
	"${EPREFIX}/usr/include/node/node_version.h" | cut -f 3 -d " ")
NODE_VERSION=${NODE_VERSION:-${ACTIVE_VERSION}}

if [[ "${NODE_VERSION}" == "21" ]] ; then
	"${EPREFIX}/usr/bin/node21" "${@}"
elif [[ "${NODE_VERSION}" == "20" ]] ; then
	"${EPREFIX}/usr/bin/node20" "${@}"
elif [[ "${NODE_VERSION}" == "18" ]] ; then
	"${EPREFIX}/usr/bin/node18" "${@}"
elif [[ "${NODE_VERSION}" == "16" ]] ; then
	"${EPREFIX}/usr/bin/node16" "${@}"
else
	echo "LTS is only supported"
	exit 1
fi

exit 0
