#!/bin/bash
EPREFIX=__EPREFIX__
ACTIVE_VERSION=$(grep -r -e "#define NODE_MAJOR_VERSION" \
	"${EPREFIX}/usr/include/node/node_version.h" | cut -f 3 -d " ")
NODE_VERSION=${NODE_VERSION:-${ACTIVE_VERSION}}

paths=$(find /usr/bin -regextype "posix-extended" -regex "${EPREFIX}/usr/bin/node[0-9]+" \
	| sort -V \
	| tac)

local found=0
for path in ${paths[@]} ; do
	if [[ -x "${path}" == "21" ]] ; then
		"${path}" "${@}"
		found=1
		break
	fi
done

if (( ${found} == 0 )) ; then
	echo "LTS is only supported"
	exit 1
fi

exit 0
