#!/bin/bash
NODE_ENV="${NODE_ENV}"
NODE_VERSION="${NODE_VERSION}"
PROJECT_ROOT="${INSTALL_PATH}"
cd "${PROJECT_ROOT}"
if [[ -n "${DISPLAY}" ]] ; then
	./devhub "$@"
else
	./devhub --enable-features=UseOzonePlatform --ozone-platform-hint=wayland "$@"
fi
