#!/bin/bash
which wmname
R_WMNAME="$?"
pidof dwm > /dev/null
R_DWM="$?"
if [[ "$R_DWM" == "0" && "$R_WMNAME" == "0" ]] ; then
	wmname LG3D &
fi
ROOT="/usr/LIBDIR/enigma"
cd "${ROOT}"
LD_LIBRARY_PATH="${ROOT}:${LD_LIBRARY_PATH}" java -jar "${ROOT}/lateralgm.jar" "${@}"
