#!/bin/bash
which wmname && pidof dwm && ( wmname LG3D & )
ROOT="/usr/LIBDIR/enigma"
cd "${ROOT}"
export CLASSPATH="JNA_CLASSPATH:${CLASSPATH}"
export LD_LIBRARY_PATH="${ROOT}:${LD_LIBRARY_PATH}"
java -jar "${ROOT}/lateralgm.jar" "${@}"
