#!/bin/bash
which wmname && pidof dwm && ( wmname LG3D & )
ROOT="/usr/LIBDIR/enigma"
JNA_JAR="JNA_PATH"
cd "${ROOT}"
export LD_LIBRARY_PATH="${ROOT}:${LD_LIBRARY_PATH}"
java \
	-noverify \
	-cp .:${JNA_JAR} \
	-jar "${ROOT}/lateralgm.jar" \
	"${@}"
