#!/bin/bash
export PATH=$PATH:/opt/crark
DIR=`pwd`
if [[ $DIR != "/opt/crark" ]]; then
	echo "Copying rarcrypt dlls...  (Remove it if crark fails.)"
	#opencl
	if [ -f /opt/crark/rarcrypt-cl.dll ] ; then
		cp /opt/crark/{rarcrypt-cl.dll,rarcrypt-hp-cl.dll} ./
	fi
	#cuda
	if [ -f /opt/crark/rarcrypt1.dll ] ; then
		cp /opt/crark/{rarcrypt1.dll,rarcrypt2.dll,rarcrypt3.dll,rarcrypt-hp1.dll,rarcrypt-hp2.dll,rarcrypt-hp3.dll} ./
	fi
fi
/opt/crark/crark $*
if [[ $DIR != "/opt/crark" ]]; then
	echo "Removing rarcrypt dlls..."
	if [ -f /opt/crark/rarcrypt-cl.dll ] ; then
		rm {rarcrypt-cl.dll,rarcrypt-hp-cl.dll}
	fi
	if [ -f /opt/crark/rarcrypt1.dll ] ; then
		rm {rarcrypt1.dll,rarcrypt2.dll,rarcrypt3.dll,rarcrypt-hp1.dll,rarcrypt-hp2.dll,rarcrypt-hp3.dll}
	fi
fi
