# Copyright 2025 Orson Teodoro <orsonteodoro@hotmail.com>
# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

DISTUTILS_EXT=1
DISTUTILS_USE_PEP517="maturin"
PYTHON_COMPAT=( "python3_"{10..13} )

# Generated by "./convert-cargo-lock.sh 0.11.0 0.11.0"
CRATES="
addr2line-0.24.2
adler2-2.0.0
aho-corasick-1.1.3
alloc-no-stdlib-2.0.4
alloc-stdlib-0.2.2
antidote-1.0.0
anyhow-1.0.95
arc-swap-1.7.1
async-compression-0.4.18
atomic-waker-1.1.2
autocfg-1.4.0
backtrace-0.3.74
base64-0.22.1
bindgen-0.70.1
bitflags-2.8.0
boring-sys2-4.14.2
boring2-4.14.2
brotli-7.0.0
brotli-decompressor-4.0.2
byteorder-1.5.0
bytes-1.9.0
cc-1.2.10
cexpr-0.6.0
cfg-if-1.0.0
clang-sys-1.8.1
cmake-0.1.52
cookie-0.18.1
cookie_store-0.21.1
core-foundation-0.9.4
core-foundation-sys-0.8.7
crc32fast-1.4.2
deranged-0.3.11
displaydoc-0.2.5
document-features-0.2.10
either-1.13.0
encoding_rs-0.8.35
equivalent-1.0.1
flate2-1.0.35
fnv-1.0.7
foldhash-0.1.4
foreign-types-0.5.0
foreign-types-macros-0.2.3
foreign-types-shared-0.3.1
form_urlencoded-1.2.1
fs_extra-1.3.0
fslock-0.2.1
futf-0.1.5
futures-channel-0.3.31
futures-core-0.3.31
futures-sink-0.3.31
futures-task-0.3.31
futures-util-0.3.31
getrandom-0.2.15
gimli-0.31.1
glob-0.3.2
hashbrown-0.15.2
heck-0.5.0
html2text-0.13.6
html5ever-0.29.0
http-1.2.0
http-body-1.0.1
http-body-util-0.1.2
http2-0.4.18
httparse-1.9.5
hyper2-1.5.5
icu_collections-1.5.0
icu_locid-1.5.0
icu_locid_transform-1.5.0
icu_locid_transform_data-1.5.0
icu_normalizer-1.5.0
icu_normalizer_data-1.5.0
icu_properties-1.5.1
icu_properties_data-1.5.0
icu_provider-1.5.0
icu_provider_macros-1.5.0
idna-1.0.3
idna_adapter-1.2.0
indexmap-2.7.1
indoc-2.0.5
ipnet-2.11.0
itertools-0.13.0
itoa-1.0.14
jobserver-0.1.32
libc-0.2.169
libloading-0.8.6
linked-hash-map-0.5.6
linked_hash_set-0.1.5
litemap-0.7.4
litrs-0.4.1
lock_api-0.4.12
log-0.4.25
lru-0.12.5
mac-0.1.1
markup5ever-0.14.0
memchr-2.7.4
memoffset-0.9.1
mime-0.3.17
mime_guess-2.0.5
minimal-lexical-0.2.1
miniz_oxide-0.8.3
mio-1.0.3
new_debug_unreachable-1.0.6
nom-7.1.3
num-conv-0.1.0
object-0.36.7
once_cell-1.20.2
openssl-macros-0.1.1
parking_lot-0.12.3
parking_lot_core-0.9.10
percent-encoding-2.3.1
phf-0.11.3
phf_codegen-0.11.3
phf_generator-0.10.0
phf_generator-0.11.3
phf_shared-0.10.0
phf_shared-0.11.3
pin-project-lite-0.2.16
pin-utils-0.1.0
pkg-config-0.3.31
portable-atomic-1.10.0
powerfmt-0.2.0
ppv-lite86-0.2.20
precomputed-hash-0.1.1
proc-macro2-1.0.93
psl-types-2.0.11
publicsuffix-2.3.0
pyo3-0.23.4
pyo3-build-config-0.23.4
pyo3-ffi-0.23.4
pyo3-log-0.12.1
pyo3-macros-0.23.4
pyo3-macros-backend-0.23.4
pythonize-0.23.0
quote-1.0.38
rand-0.8.5
rand_chacha-0.3.1
rand_core-0.6.4
redox_syscall-0.5.8
regex-1.11.1
regex-automata-0.4.9
regex-syntax-0.8.5
rquest-2.0.3
rustc-demangle-0.1.24
rustc-hash-1.1.0
rustls-pki-types-1.10.1
ryu-1.0.18
scopeguard-1.2.0
serde-1.0.217
serde_derive-1.0.217
serde_json-1.0.137
serde_urlencoded-0.7.1
shlex-1.3.0
signal-hook-registry-1.4.2
siphasher-0.3.11
siphasher-1.0.1
slab-0.4.9
smallvec-1.13.2
socket2-0.5.8
stable_deref_trait-1.2.0
string_cache-0.8.7
string_cache_codegen-0.5.2
syn-2.0.96
sync_wrapper-1.0.2
synstructure-0.13.1
system-configuration-0.6.1
system-configuration-sys-0.6.0
target-lexicon-0.12.16
tendril-0.4.3
thiserror-1.0.69
thiserror-2.0.11
thiserror-impl-1.0.69
thiserror-impl-2.0.11
time-0.3.37
time-core-0.1.2
time-macros-0.2.19
tinystr-0.7.6
tokio-1.43.0
tokio-boring2-4.14.2
tokio-macros-2.5.0
tokio-socks-0.5.2
tokio-util-0.7.13
tower-0.5.2
tower-layer-0.3.3
tower-service-0.3.3
tracing-0.1.41
tracing-attributes-0.1.28
tracing-core-0.1.33
try-lock-0.2.5
typed-builder-0.20.0
typed-builder-macro-0.20.0
unicase-2.8.1
unicode-ident-1.0.15
unicode-width-0.2.0
unindent-0.2.3
url-2.5.4
utf-8-0.7.6
utf16_iter-1.0.5
utf8_iter-1.0.4
version_check-0.9.5
want-0.3.1
wasi-0.11.0+wasi-snapshot-preview1
webpki-root-certs-0.26.7
winapi-0.3.9
winapi-i686-pc-windows-gnu-0.4.0
winapi-x86_64-pc-windows-gnu-0.4.0
windows-registry-0.4.0
windows-result-0.3.0
windows-strings-0.3.0
windows-sys-0.52.0
windows-targets-0.52.6
windows-targets-0.53.0
windows_aarch64_gnullvm-0.52.6
windows_aarch64_gnullvm-0.53.0
windows_aarch64_msvc-0.52.6
windows_aarch64_msvc-0.53.0
windows_i686_gnu-0.52.6
windows_i686_gnu-0.53.0
windows_i686_gnullvm-0.52.6
windows_i686_gnullvm-0.53.0
windows_i686_msvc-0.52.6
windows_i686_msvc-0.53.0
windows_x86_64_gnu-0.52.6
windows_x86_64_gnu-0.53.0
windows_x86_64_gnullvm-0.52.6
windows_x86_64_gnullvm-0.53.0
windows_x86_64_msvc-0.52.6
windows_x86_64_msvc-0.53.0
write16-1.0.0
writeable-0.5.5
yoke-0.7.5
yoke-derive-0.7.5
zerocopy-0.7.35
zerocopy-derive-0.7.35
zerofrom-0.1.5
zerofrom-derive-0.1.5
zerovec-0.10.4
zerovec-derive-0.10.3
zstd-0.13.2
zstd-safe-7.2.1
zstd-sys-2.0.13+zstd.1.5.6
"

# Cargo must go after distutils-r1
inherit distutils-r1 cargo pypi

KEYWORDS="~amd64"
S="${WORKDIR}/${PN}-${PV}"
SRC_URI="
$(cargo_crate_uris ${CRATES})
https://github.com/deedy5/primp/archive/refs/tags/v${PV}.tar.gz
	-> ${P}.tar.gz
"

DESCRIPTION="HTTP client that can impersonate web browsers, mimicking their headers and \`TLS/JA3/JA4/HTTP2\` fingerprints"
HOMEPAGE="
	https://github.com/deedy5/primp
	https://pypi.org/project/primp
"
LICENSE="
	MIT
"
RESTRICT="mirror"
SLOT="0/$(ver_cut 1-2 ${PV})"
IUSE+=" dev"
RDEPEND+="
"
DEPEND+="
	${RDEPEND}
"
BDEPEND+="
	dev? (
		>=dev-python/pytest-8.1.1[${PYTHON_USEDEP}]
		dev-python/certifi[${PYTHON_USEDEP}]
	)
"
DOCS=( "README.md" )

pkg_setup() {
	python_setup
	rust_pkg_setup
}

src_unpack() {
	unpack ${A}
	cargo_src_unpack
}

src_prepare() {
	distutils-r1_src_prepare
}

python_configure() {
	:
}

src_configure() {
	cargo_src_configure
	distutils-r1_src_configure
}

python_compile() {
	cargo_src_compile
	distutils-r1_python_compile
}

src_compile() {
	distutils-r1_src_compile
}

src_install() {
	distutils-r1_src_install
	docinto "licenses"
	dodoc "LICENSE"
}

# OILEDMACHINE-OVERLAY-META:  CREATED-EBUILD
