#!/bin/bash

PLUGIN_NAME="assistant-panel"
DEST_DIR="${HOME}/.config/noctalia/plugins/${PLUGIN_NAME}"
SRC_DIR="/opt/noctalia-plugins/${PLUGIN_NAME}"


die() {
	local msg="$@"
	echo "${msg}"
	exit 1
}

main() {
	if [[ -e "${DEST_DIR}" ]] ; then
		echo "Removing previous install of ${PLUGIN_NAME}"
		rm -rf "${DEST_DIR}"
	fi
	echo "Installing ${PLUGIN_NAME} to ${DEST_DIR}"
	mkdir -p "${DEST_DIR}" || die "Failed dir creation"
	cp -aT "${SRC_DIR}" "${DEST_DIR}" || die "Install failed"
	echo "Install successful"
}

main
