#!/bin/bash
ENIGMA_PREFIX="/usr/lib/enigma"
RADIALGM_PREFIX="/usr/lib/RadialGM"
export PATH="${ENIGMA_PREFIX}:${RADIALGM_PREFIX}:${PATH}"
pushd "${ENIGMA_PREFIX}" # Do not remove.  It will break emake if removed.
	"${RADIALGM_PREFIX}/RadialGM" "${@}"
popd
