#!/bin/bash
NODE_SLOT=@NODE_SLOT@
export PATH="/usr/lib/node/${NODE_SLOT}/bin:${PATH}"
main() {
	cd "/opt/lobe-chat"
	source "/etc/conf.d/lobe-chat"
	# TODO add sandbox
	node "/opt/lobe-chat/startServer.js"
}
main
