#!/bin/bash

ARGS=( "${@}" )

prepare_backends() {
	if [[ -n "${EXTRA_BACKENDS}" ]] ; then
		local backend
		for backend in ${EXTRA_BACKENDS} ; do
			echo "Preparing backend:  ${backend}"
			make -C "${backend}"
		done
	fi
}

main() {
	[[ -e "/tmp/generated" ]] && echo "[warn] /tmp/generated may need to be manually removed to avoid ownership issue."
	[[ -e "/tmp/localai" ]] && echo "[warn] /tmp/localai may need to be manually removed to avoid ownership issue."

	cd "/opt/local-ai"
	source "/etc/conf.d/local-ai"
	prepare_backends
	# TODO sandbox local-ai
	./local-ai "${ARGS[@]}"
}

main
