# Copyright 2022-2023 Orson Teodoro <orsonteodoro@hotmail.com>
# Copyright 1999-2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# Auto-Generated by cargo-ebuild 0.3.1
CRATES="
aho-corasick-0.7.20
autocfg-1.1.0
bitflags-1.3.2
cfg-if-1.0.0
indoc-0.3.6
indoc-impl-0.3.6
instant-0.1.12
lazy_static-1.4.0
libc-0.2.140
lock_api-0.4.9
memchr-2.5.0
once_cell-1.17.1
parking_lot-0.11.2
parking_lot_core-0.8.6
paste-0.1.18
paste-impl-0.1.18
proc-macro-hack-0.5.20+deprecated
proc-macro2-1.0.52
pyo3-0.15.2
pyo3-build-config-0.15.2
pyo3-macros-0.15.2
pyo3-macros-backend-0.15.2
quote-1.0.26
redox_syscall-0.2.16
regex-1.7.1
regex-syntax-0.6.28
scopeguard-1.1.0
smallvec-1.10.0
syn-1.0.109
unicode-ident-1.0.8
unindent-0.1.11
winapi-0.3.9
winapi-i686-pc-windows-gnu-0.4.0
winapi-x86_64-pc-windows-gnu-0.4.0
"

DISTUTILS_USE_PEP517="setuptools"
PYTHON_COMPAT=( python3_{8..11} )
inherit autotools cargo distutils-r1 lcnr

DESCRIPTION="Breezy is a friendly powerful distributed version control system."
HOMEPAGE="https://launchpad.net/brz"
LICENSE="
	GPL-2+
	Apache-2.0
"
# tools/rst2pdf.py is Apache-2.0
LICENSE+="
	custom
	Apache-2.0
	BSD
	BSD-4
	MIT
	PSF-2.4
	openssl
	tcltk
	Unicode-DFS-2016
	Unlicense
" # Third party cargo licenses
# homedir/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.15.2 - custom
# homedir/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.6.0 - custom
# homedir/.cargo/registry/src/github.com-1ecc6299db9ec823/pkg-version-1.0.0 - custom
# homedir/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-syntax-0.6.27/src/unicode_tables/LICENSE-UNICODE - Unicode-DFS-2016
# homedir/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-ident-1.0.5/LICENSE-UNICODE - Unicode-DFS-2016
KEYWORDS="~amd64 ~x86"
SLOT="0"
IUSE+=" cext doc fastimport git github gpg sftp test workspace"
REQUIRED_USE+="
	${PYTHON_REQUIRED_USE}
"
# See also:  https://github.com/breezy-team/breezy/blob/upstream-3.2.2/setup.py#L60
DEPEND="
	${PYTHON_DEPS}
	>=dev-python/dulwich-0.21.2[${PYTHON_USEDEP}]
	>=dev-python/fastbencode-0.0.5[${PYTHON_USEDEP}]
	>=dev-python/urllib3-1.24.1[${PYTHON_USEDEP}]
	dev-python/configobj[${PYTHON_USEDEP}]
	dev-python/merge3[${PYTHON_USEDEP}]
	dev-python/patiencediff[${PYTHON_USEDEP}]
	dev-python/pyyaml[${PYTHON_USEDEP}]
	fastimport? (
		dev-python/fastimport[${PYTHON_USEDEP}]
	)
	github? (
		dev-python/PyGithub[${PYTHON_USEDEP}]
	)
	gpg? (
		app-crypt/gpgme[${PYTHON_USEDEP}]
	)
	sftp? (
		dev-python/paramiko[${PYTHON_USEDEP}]
		dev-python/pycrypto[${PYTHON_USEDEP}]
	)
	workspace? (
		dev-python/pyinotify[${PYTHON_USEDEP}]
	)
"
RDEPEND+="
	${DEPEND}
"
# TODO package:
# setuptools-gettext
BDEPEND+="
	${PYTHON_DEPS}
	>=dev-python/setuptools-60[${PYTHON_USEDEP}]
	dev-python/setuptools-rust[${PYTHON_USEDEP}]
	dev-python/setuptools-gettext[${PYTHON_USEDEP}]
	dev-python/flake8[${PYTHON_USEDEP}]
	dev-python/mypy[${PYTHON_USEDEP}]
	dev-python/packaging[${PYTHON_USEDEP}]
	cext? (
		>=dev-python/cython-0.29[${PYTHON_USEDEP}]
	)
	doc? (
		dev-python/docutils[${PYTHON_USEDEP}]
		dev-python/sphinx[${PYTHON_USEDEP}]
		dev-python/sphinx-epytext[${PYTHON_USEDEP}]
	)
	test? (
		>=dev-python/dulwich-0.21.2[${PYTHON_USEDEP}]
		dev-python/testscenarios[${PYTHON_USEDEP}]
		dev-python/testtools[${PYTHON_USEDEP}]
		dev-python/subunit[${PYTHON_USEDEP}]
		dev-python/flake8[${PYTHON_USEDEP}]
	)
"
SRC_URI="
$(cargo_crate_uris ${CRATES})
https://launchpad.net/brz/$(ver_cut 1-2 ${PV})/${PV}/+download/${PN}-${PV}.tar.gz
"
S="${WORKDIR}/${PN}-${PV}"
RESTRICT="mirror"

pkg_setup() {
	if has network-sandbox ${FEATURES} ; then
eerror
eerror "Building requires network-sandbox to be disabled in FEATURES on a"
eerror "per-package level."
eerror
		die
	fi
	python_setup
}

src_install() {
	LCNR_SOURCE="${WORKDIR}/cargo_home/gentoo"
	LCNR_TAG="third_party"
	lcnr_install_files

	distutils-r1_src_install
}

# OILEDMACHINE-OVERLAY-META:  CREATED-EBUILD
