# Copyright 2024-2025 Orson Teodoro <orsonteodoro@hotmail.com>
# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# TODO package (optional):
# mypy-protobuf

# For protobuf version, see Dockerfile

# USE=-dev (production):  protobuf-python >= 4
#               USE=dev:  protobuf-python == 5

MY_PN="chroma"

inherit protobuf

#CHROMA_CORE_HNSWLIB_PV="0.8.1"
DISTUTILS_EXT=1
DISTUTILS_SINGLE_IMPL=1
DISTUTILS_USE_PEP517="maturin"
PROTOBUF_GRPC="5"
PROTOBUF_CPP_SLOT="5"
PROTOBUF_PYTHON_SLOT="${PROTOBUF_PYTHON_SLOT_5[@]}"
PYTHON_COMPAT=( "python3_"{11..12} ) # Upstream has 3.9-3.11
OPENTELEMETRY_PV_DEV="1.29.0"
OPENTELEMETRY_PV_REL="1.27.0"
OPENTELEMETRY_SLOT_DEV="0/${OPENTELEMETRY_PV_DEV}"
OPENTELEMETRY_SLOT_REL="0/${OPENTELEMETRY_PV_REL}"
RE2_SLOT="20250512"
RUST_MAX_VER="1.98.1"
RUST_MIN_VER="1.98.1"

CPU_FLAGS_X86=(
	"cpu_flags_x86_avx"
	"cpu_flags_x86_avx512f"
	"cpu_flags_x86_sse"
)

PROTOBUF_PYTHON=(
	"protobuf_python_4"
	"+protobuf_python_5"
)

# Generated by "./convert-cargo-lock.sh 1.5.9 1.5.9"
#CHROMADB_RS_COMMIT="bd8ec9581e00034363befe7d38146084df018876"
declare -A GIT_CRATES=(
# Remove ?tag=v20260319
[gcloud-auth]="https://github.com/yoshidan/google-cloud-rust;bd8ec9581e00034363befe7d38146084df018876;google-cloud-rust-%commit%/foundation/auth" # 1.3.0
[gcloud-gax]="https://github.com/yoshidan/google-cloud-rust;bd8ec9581e00034363befe7d38146084df018876;google-cloud-rust-%commit%/googleapis/foundation/gax" # 1.4.0
[gcloud-googleapis]="https://github.com/yoshidan/google-cloud-rust;bd8ec9581e00034363befe7d38146084df018876;google-cloud-rust-%commit%/googleapis" # 1.3.0
[gcloud-longrunning]="https://github.com/yoshidan/google-cloud-rust;bd8ec9581e00034363befe7d38146084df018876;google-cloud-rust-%commit%/foundation/longrunning" # 1.4.0
[gcloud-metadata]="https://github.com/yoshidan/google-cloud-rust;bd8ec9581e00034363befe7d38146084df018876;google-cloud-rust-%commit%/foundation/metadata" # 1.0.2
[gcloud-spanner]="https://github.com/yoshidan/google-cloud-rust;bd8ec9581e00034363befe7d38146084df018876;google-cloud-rust-%commit%/spanner" # 1.8.0
[hnswlib]="https://github.com/chroma-core/hnswlib;3748ae95c922c6065f38f7048cc9a8c06f969203;" # 0.8.2
)

EXCLUDE_CRATES="
chroma-benchmark-0.1.0
chroma-blockstore-0.1.0
chroma-cache-0.1.0
chroma-cli-1.4.4
chroma-config-0.1.0
chroma-distance-0.1.0
chroma-error-0.14.0
chroma-frontend-1.0.0
chroma-index-0.1.0
chroma-load-0.1.0
chroma-log-0.1.0
chroma-log-service-0.1.0
chroma-memberlist-0.1.0
chroma-segment-0.1.0
chroma-sqlite-0.1.0
chroma-storage-0.1.0
chroma-sysdb-0.1.0
chroma-system-0.1.0
chroma-tracing-0.1.0
chroma-types-0.14.0
chromadb-js-bindings-0.1.0
chromadb_rust_bindings-0.1.0
garbage_collector-0.1.0
chroma-faults-0.1.0
chroma-jemalloc-pprof-server-0.1.0
chroma-metering-0.1.0
chroma-metering-macros-0.1.0
rust-sysdb-0.1.0
s3heap-0.1.0
s3heap-service-0.1.0
spanner-migrations-0.1.0
"


# Generated by "./convert-cargo-lock.sh 1.5.9 1.5.9"
CRATES="
addr2line-0.25.1
adler2-2.0.1
aes-0.9.3
ahash-0.8.12
aho-corasick-1.1.5
alga-0.9.3
allocator-api2-0.2.21
alloc-no-stdlib-2.0.4
alloc-stdlib-0.2.4
android_system_properties-0.1.6
anes-0.1.6
anstream-1.0.0
anstyle-1.0.14
anstyle-parse-1.0.0
anstyle-query-1.1.5
anstyle-wincon-3.0.11
anyhow-1.0.104
approx-0.3.2
approx-0.5.1
arbitrary-1.5.0
arboard-3.6.1
arc-swap-1.9.2
array-util-1.0.2
arrayvec-0.7.8
arrow-55.2.0
arrow-arith-55.2.0
arrow-array-55.2.0
arrow-buffer-55.2.0
arrow-cast-55.2.0
arrow-csv-55.2.0
arrow-data-55.2.0
arrow-ipc-55.2.0
arrow-json-55.2.0
arrow-ord-55.2.0
arrow-row-55.2.0
arrow-schema-55.2.0
arrow-select-55.2.0
arrow-string-55.2.0
assert-json-diff-2.0.2
assoc-0.1.3
async-channel-2.5.0
async-compression-0.4.50
async-lock-3.4.2
async-object-pool-0.2.0
async-stream-0.3.6
async-stream-impl-0.3.6
async-task-4.7.1
async-tempfile-0.6.0
async-trait-0.1.92
atoi-2.0.0
atomic-0.6.1
atomic-waker-1.1.2
autocfg-1.5.1
auto_enums-0.8.10
aws-config-1.12.0
aws-credential-types-1.3.0
aws-lc-rs-1.18.1
aws-lc-sys-0.45.0
aws-runtime-1.10.0
aws-sdk-s3-1.152.0
aws-sdk-sso-1.114.0
aws-sdk-ssooidc-1.116.0
aws-sdk-sts-1.119.0
aws-sigv4-1.6.0
aws-smithy-async-1.3.0
aws-smithy-checksums-0.65.0
aws-smithy-eventstream-0.61.4
aws-smithy-http-0.64.1
aws-smithy-http-client-1.5.0
aws-smithy-json-0.63.1
aws-smithy-observability-0.3.0
aws-smithy-query-0.62.1
aws-smithy-runtime-1.16.0
aws-smithy-runtime-api-1.19.0
aws-smithy-runtime-api-macros-1.1.0
aws-smithy-schema-0.2.1
aws-smithy-types-1.8.1
aws-smithy-xml-0.62.1
aws-types-1.6.0
axum-0.8.9
axum-core-0.5.6
axum-macros-0.5.1
backoff-0.4.0
backon-1.6.0
backtrace-0.3.76
base16ct-0.2.0
base64-0.21.7
base64-0.22.1
base64-0.23.1
base64ct-1.8.3
base64-simd-0.8.0
bigdecimal-0.4.11
bincode-1.3.3
bitflags-2.13.2
bitpacking-0.9.3
bit-set-0.8.0
bit-vec-0.4.4
bit-vec-0.8.0
bitvec-1.1.1
block-buffer-0.10.4
block-buffer-0.12.1
bloom-0.3.2
bon-3.10.2
bon-macros-3.10.2
brotli-8.0.4
brotli-decompressor-5.0.3
bstr-1.13.1
bumpalo-3.20.3
bytemuck-1.25.2
bytemuck_derive-1.12.1
byteorder-1.5.0
byteorder-lite-0.1.0
bytes-1.12.1
bytes-utils-0.1.4
bzip2-0.6.1
cassowary-0.3.0
cast-0.3.0
castaway-0.2.4
cc-1.6.0
census-0.4.2
cfg_aliases-0.2.2
cfg-if-1.0.5
chacha20-0.10.2
chroma-0.14.0
chroma-api-types-0.14.0
chrono-0.4.45
ciborium-0.2.2
ciborium-io-0.2.2
ciborium-ll-0.2.2
cipher-0.5.2
clap-4.6.7
clap_builder-4.6.7
clap_derive-4.6.7
clap_lex-1.1.1
clipboard-win-5.4.1
cmake-0.1.58
cmov-0.5.4
cmsketch-0.2.4
codespan-reporting-0.13.1
colorchoice-1.0.5
colored-3.1.1
combine-4.6.8
compact_str-0.8.2
compression-codecs-0.4.45
compression-core-0.4.33
concurrent-queue-2.5.0
console-0.15.11
constant_time_eq-0.4.2
const-oid-0.10.2
const-oid-0.9.6
const-random-0.1.18
const-random-macro-0.1.16
convert_case-0.10.0
convert_case-0.6.0
core_detect-1.0.0
core-foundation-0.10.1
core-foundation-0.9.4
core-foundation-sys-0.8.7
cpubits-0.1.1
cpufeatures-0.2.17
cpufeatures-0.3.1
crc32fast-1.5.2
crc-3.4.0
crc-catalog-2.5.0
crc-fast-1.10.0
criterion-0.7.0
criterion-plot-0.6.0
crossbeam-channel-0.5.17
crossbeam-deque-0.8.8
crossbeam-epoch-0.9.21
crossbeam-queue-0.3.14
crossbeam-utils-0.8.23
crossterm-0.28.1
crossterm-0.29.0
crossterm_winapi-0.9.1
crunchy-0.2.4
crypto-bigint-0.5.5
crypto-common-0.1.7
crypto-common-0.2.2
csv-1.4.0
csv-core-0.1.13
ctor-0.2.9
ctutils-0.4.3
cxx-1.0.202
cxxbridge-cmd-1.0.202
cxxbridge-flags-1.0.202
cxxbridge-macro-1.0.202
cxx-build-1.0.202
darling-0.14.4
darling-0.20.11
darling-0.24.1
darling_core-0.14.4
darling_core-0.20.11
darling_core-0.24.1
darling_macro-0.14.4
darling_macro-0.20.11
darling_macro-0.24.1
dashmap-6.2.1
defer-0.2.1
deflate64-0.1.12
der-0.7.10
deranged-0.5.8
derivative-2.2.0
derive_arbitrary-1.5.0
derive_more-2.1.1
derive_more-impl-2.1.1
derive_utils-0.16.0
dialoguer-0.11.0
digest-0.10.7
digest-0.11.3
dirs-5.0.1
dirs-6.0.0
dirs-sys-0.4.1
dirs-sys-0.5.0
dispatch2-0.3.1
displaydoc-0.2.7
document-features-0.2.12
dotenvy-0.15.7
downcast-rs-1.2.1
dunce-1.0.5
dyn-clone-1.0.20
dyn-stack-0.13.2
dyn-stack-macros-0.1.3
ecdsa-0.16.9
either-1.19.0
elliptic-curve-0.13.8
encode_unicode-1.0.0
encoding_rs-0.8.42
enum-as-inner-0.6.1
env_filter-2.0.0
env_logger-0.11.11
equator-0.2.2
equator-0.6.0
equator-macro-0.2.1
equator-macro-0.6.0
equivalent-1.0.2
errno-0.3.14
error-code-3.4.0
etcetera-0.8.0
event-listener-5.4.2
event-listener-strategy-0.5.4
faer-0.24.4
faer-traits-0.24.0
failsafe-1.3.0
fastant-0.1.11
fastbloom-0.17.0
fastdivide-0.4.2
fastrace-0.7.8
fastrace-macro-0.7.19
fastrace-opentelemetry-0.8.1
fastrand-2.5.0
fax-0.2.7
fdeflate-0.3.7
ff-0.13.1
figment-0.10.19
find-msvc-tools-0.1.14
fixedbitset-0.5.7
flatbuffers-25.12.19
flate2-1.1.10
flume-0.11.1
fnv-1.0.7
foldhash-0.1.5
foldhash-0.2.0
foreign-types-0.3.2
foreign-types-shared-0.1.1
form_urlencoded-1.2.2
foyer-0.17.4
foyer-common-0.17.4
foyer-intrusive-collections-0.10.0-dev
foyer-memory-0.17.4
foyer-storage-0.17.4
fs4-0.13.1
fs4-0.8.4
fs_extra-1.3.0
funty-2.0.0
futures-0.3.34
futures-channel-0.3.34
futures-core-0.3.34
futures-executor-0.3.34
futures-intrusive-0.5.0
futures-io-0.3.34
futures-macro-0.3.34
futures-sink-0.3.34
futures-task-0.3.34
futures-timer-3.0.4
futures-util-0.3.34
gemm-0.19.0
gemm-c32-0.19.0
gemm-c64-0.19.0
gemm-common-0.19.0
gemm-f16-0.19.0
gemm-f32-0.19.0
gemm-f64-0.19.0
generativity-1.2.1
generator-0.8.10
generic-array-0.14.7
gethostname-1.1.0
getrandom-0.2.17
getrandom-0.3.4
getrandom-0.4.3
gimli-0.32.3
glob-0.3.4
globset-0.4.20
gloo-timers-0.3.0
group-0.13.0
guacamole-0.11.0
h2-0.3.27
h2-0.4.20
half-2.7.1
hashbrown-0.13.2
hashbrown-0.14.5
hashbrown-0.15.5
hashbrown-0.17.1
hashlink-0.10.0
headers-0.4.2
headers-core-0.3.0
heck-0.4.1
heck-0.5.0
hermit-abi-0.5.3
hex-0.4.3
hf-hub-0.4.3
hkdf-0.12.4
hmac-0.12.1
hmac-0.13.0
home-0.5.12
htmlescape-0.3.1
http-0.2.12
http-1.5.0
httparse-1.10.1
http-body-0.4.6
http-body-1.1.0
http-body-util-0.1.5
httpdate-1.0.3
httpmock-0.8.3
http-range-header-0.3.1
humantime-2.4.0
hybrid-array-0.4.15
hyper-0.14.32
hyper-1.12.0
hyper-rustls-0.24.2
hyper-rustls-0.27.10
hyper-timeout-0.4.1
hyper-timeout-0.5.2
hyper-tls-0.6.0
hyper-util-0.1.21
iana-time-zone-0.1.65
iana-time-zone-haiku-0.1.2
icu_collections-2.3.0
icu_locale_core-2.3.0
icu_locale_fallback-2.3.0
icu_locale_fallback_data-2.3.0
icu_normalizer-2.3.0
icu_normalizer_data-2.3.0
icu_properties-2.3.0
icu_properties_data-2.3.0
icu_provider-2.3.1
icu_segmenter-2.3.0
icu_segmenter_data-2.3.0
ident_case-1.0.1
idna-1.1.0
idna_adapter-1.2.2
image-0.25.10
indexmap-2.14.2
indicatif-0.17.11
indoc-2.0.7
inferno-0.12.8
inherent-1.0.14
inlinable_string-0.1.15
inout-0.2.2
instability-0.3.14
instant-0.1.13
integer-encoding-3.0.4
interpol-0.2.1
ipnet-2.12.2
is_ci-1.2.0
is_terminal_polyfill-1.70.2
iter-read-1.1.0
itertools-0.12.1
itertools-0.13.0
itertools-0.14.0
itoa-1.0.18
jemalloc_pprof-0.8.0
jni-0.22.4
jni-macros-0.22.4
jni-sys-0.4.1
jni-sys-macros-0.4.1
jobserver-0.1.35
json-patch-1.4.0
jsonpath-rust-0.3.5
jsonwebtoken-10.4.0
js-sys-0.3.106
k8s-openapi-0.20.0
keccak-0.1.6
kube-0.87.2
kube-client-0.87.2
kube-core-0.87.2
kube-derive-0.87.2
kube-runtime-0.87.2
lazy_static-1.5.1
levenshtein_automata-0.2.1
lexical-core-1.0.6
lexical-parse-float-1.0.6
lexical-parse-integer-1.0.6
lexical-util-1.0.7
lexical-write-float-1.0.6
lexical-write-integer-1.0.6
libbz2-rs-sys-0.2.5
libc-0.2.190
libloading-0.8.9
libm-0.2.16
libredox-0.1.25
libsqlite3-sys-0.30.1
libyaml-rs-0.3.0
link-cplusplus-1.0.12
linux-raw-sys-0.12.1
linux-raw-sys-0.4.15
litemap-0.8.3
litrs-1.0.0
lock_api-0.4.14
log-0.4.34
lru-0.12.5
lru-0.18.5
lru-slab-0.1.3
lz4-1.28.1
lz4_flex-0.11.6
lz4-sys-1.11.1+lz4-1.10.0
lzma-rust2-0.16.5
madsim-0.2.34
madsim-macros-0.2.12
madsim-tokio-0.2.30
mappings-0.7.0
matchers-0.2.0
matchit-0.8.4
matrixmultiply-0.3.11
md-5-0.10.6
md-5-0.11.0
md5-0.7.0
mdac-0.1.0
measure_time-0.8.3
memchr-2.8.3
memmap2-0.9.11
memoffset-0.9.1
mime-0.3.17
mime_guess-2.0.5
minimal-lexical-0.2.1
miniz_oxide-0.8.9
miniz_oxide-0.9.1
mio-1.2.4
mixtrics-0.1.0
moxcms-0.8.1
multimap-0.10.1
multiversion_no_op-1.0.0
murmur3-0.5.2
murmurhash32-0.3.1
naive-timer-0.2.0
nano-gemm-0.2.2
nano-gemm-c32-0.2.1
nano-gemm-c64-0.2.1
nano-gemm-codegen-0.2.1
nano-gemm-core-0.2.1
nano-gemm-f32-0.2.1
nano-gemm-f64-0.2.1
nanorand-0.7.0
napi-2.16.17
napi-build-2.6.0
napi-derive-2.16.13
napi-derive-backend-1.0.75
napi-sys-2.4.0
native-tls-0.2.18
ndarray-0.16.1
ndarray-0.17.2
ndk-context-0.1.1
network-interface-1.1.4
nom-7.1.3
nu-ansi-term-0.50.3
num-0.4.3
number_prefix-0.4.0
num-bigint-0.4.8
num-bigint-dig-0.8.6
num-complex-0.2.4
num-complex-0.4.6
num-conv-0.2.2
num_cpus-1.17.0
num-format-0.4.4
num-integer-0.1.47
num-iter-0.1.46
num-rational-0.4.2
num-traits-0.2.19
objc2-0.6.5
objc2-app-kit-0.3.2
objc2-core-foundation-0.3.2
objc2-core-graphics-0.3.2
objc2-encode-4.1.0
objc2-foundation-0.3.2
objc2-io-surface-0.3.2
object-0.37.3
object_store-0.12.5
once_cell-1.21.4
once_cell_polyfill-1.70.2
oneshot-0.1.13
oorandom-11.1.5
openssl-0.10.81
openssl-macros-0.1.1
openssl-probe-0.1.6
openssl-probe-0.2.1
openssl-sys-0.9.117
opentelemetry-0.27.1
opentelemetry-0.31.0
opentelemetry-0.33.0
opentelemetry-http-0.33.0
opentelemetry-otlp-0.33.0
opentelemetry-proto-0.33.0
opentelemetry_sdk-0.27.1
opentelemetry_sdk-0.33.0
option-ext-0.2.0
ordered-float-2.10.1
ordered_hash_map-0.4.0
outref-0.5.2
ownedbytes-0.7.0
owo-colors-3.5.0
p256-0.13.2
panic-message-0.3.0
parking-2.2.1
parking_lot-0.12.5
parking_lot_core-0.9.12
parquet-55.2.0
paste-1.0.15
path-tree-0.8.3
pbkdf2-0.13.0
pear-0.2.9
pear_codegen-0.2.9
pem-3.0.6
pem-rfc7468-0.7.0
percent-encoding-2.3.2
pest-2.9.2
pest_derive-2.9.2
pest_generator-2.9.2
pest_meta-2.9.2
petgraph-0.8.3
pin-project-1.1.13
pin-project-internal-1.1.13
pin-project-lite-0.2.17
pin-utils-0.1.1
pkcs1-0.7.5
pkcs8-0.10.2
pkg-config-0.3.34
plain-0.2.3
plotters-0.3.7
plotters-backend-0.3.7
plotters-svg-0.3.7
png-0.18.1
pollster-0.4.0
portable-atomic-1.15.0
portable-atomic-util-0.2.8
potential_utf-0.1.6
powerfmt-0.2.1
ppmd-rust-1.5.0
pprof_util-0.7.0
ppv-lite86-0.2.21
prettyplease-0.2.37
prettyplease-0.3.0
primeorder-0.13.6
private-gemm-x86-0.1.22
proc-macro2-0.4.30
proc-macro2-1.0.107
proc-macro2-diagnostics-0.10.1
proc-macro-error2-2.0.1
proc-macro-error-attr2-2.0.0
proptest-1.11.0
proptest-derive-0.3.0
proptest-derive-0.5.1
proptest-state-machine-0.3.1
prost-0.13.5
prost-0.14.4
prost-build-0.14.4
prost-derive-0.13.5
prost-derive-0.14.4
prost-types-0.14.4
pulldown-cmark-0.13.4
pulldown-cmark-to-cmark-22.0.3
pulp-0.22.3
pulp-wasm-simd-flag-0.1.1
pxfm-0.1.30
pyo3-0.29.3
pyo3-build-config-0.29.3
pyo3-ffi-0.29.3
pyo3-macros-0.29.3
pyo3-macros-backend-0.29.3
qd-0.8.0
quick-error-1.2.3
quick-error-2.0.1
quick-xml-0.38.4
quick-xml-0.41.0
quinn-0.11.12
quinn-proto-0.11.19
quinn-udp-0.5.16
quote-0.6.13
quote-1.0.47
radium-0.7.0
rand-0.10.3
rand-0.8.8
rand-0.9.5
rand_chacha-0.3.1
rand_chacha-0.9.0
rand_core-0.10.1
rand_core-0.6.4
rand_core-0.9.5
rand_distr-0.4.3
rand_distr-0.5.1
random-port-0.1.1
rand_pcg-0.10.2
rand_pcg-0.3.1
rand_xorshift-0.3.0
rand_xorshift-0.4.0
rand_xoshiro-0.6.0
ratatui-0.29.0
raw-cpuid-11.6.0
rawpointer-0.2.1
rayon-1.12.0
rayon-core-1.13.0
reborrow-0.5.5
redox_syscall-0.5.18
redox_syscall-0.9.4
redox_users-0.4.6
redox_users-0.5.3
r-efi-5.3.0
r-efi-6.0.0
regex-1.13.1
regex-automata-0.4.18
regex-lite-0.1.9
regex-syntax-0.8.11
reqwest-0.12.28
reqwest-0.13.5
rfc6979-0.4.0
rgb-0.8.53
ring-0.17.14
roaring-0.10.12
rsa-0.9.10
rtrb-0.3.5
rustc-demangle-0.1.28
rustc-hash-1.1.0
rustc-hash-2.1.3
rustc_version-0.4.1
rust-embed-8.13.0
rust-embed-impl-8.13.0
rust-embed-utils-8.13.0
rustix-0.38.44
rustix-1.1.5
rustls-0.21.12
rustls-0.23.45
rustls-native-certs-0.6.3
rustls-native-certs-0.8.4
rustls-pemfile-1.0.4
rustls-pemfile-2.2.0
rustls-pki-types-1.15.1
rustls-platform-verifier-0.7.1
rustls-platform-verifier-android-0.2.0
rustls-webpki-0.101.7
rustls-webpki-0.103.15
rust-stemmers-1.2.0
rustversion-1.0.23
rusty-fork-0.3.1
ryu-1.0.23
same-file-1.0.6
schannel-0.1.29
schemars-0.8.22
schemars_derive-0.8.22
scoped-tls-1.0.1
scopeguard-1.2.0
scratch-1.0.9
sct-0.7.1
sea-query-0.32.7
sea-query-binder-0.7.0
sea-query-derive-0.4.3
sec1-0.7.3
secrecy-0.8.0
security-framework-2.11.1
security-framework-3.7.0
security-framework-sys-2.17.0
semver-1.0.28
seq-macro-0.3.6
serde-1.0.229
serde_bytes-0.11.19
serde_core-1.0.229
serde_derive-1.0.229
serde_derive_internals-0.29.1
serde_json-1.0.151
serde_path_to_error-0.1.20
serde-pickle-1.2.0
serde_regex-1.2.0
serde_spanned-0.6.9
serde_spanned-1.1.2
serde_urlencoded-0.7.1
serde-value-0.7.0
serde_yaml-0.9.34+deprecated
serial_test-3.5.0
serial_test_derive-3.5.0
setsum-0.7.0
sha1-0.10.7
sha1-0.11.0
sha2-0.10.9
sha2-0.11.0
sha3-0.10.9
sharded-slab-0.1.7
shell-words-1.1.1
shlex-2.0.1
shuttle-0.7.1
signal-hook-0.3.18
signal-hook-mio-0.2.5
signal-hook-registry-1.4.8
signature-2.2.0
simd-adler32-0.3.10
simd_cesu8-1.2.0
simdutf8-0.1.5
similar-2.7.0
simple_asn1-0.6.4
simsimd-6.5.16
siphasher-1.0.4
sketches-ddsketch-0.2.2
slab-0.4.12
small_ctor-0.1.2
smallvec-1.16.2
smawk-0.3.3
snap-1.1.2
socket2-0.5.10
socket2-0.6.5
socks-0.3.4
spin-0.10.1
spin-0.9.9
spki-0.7.3
sprs-0.11.5
sqlx-0.8.6
sqlx-core-0.8.6
sqlx-macros-0.8.6
sqlx-macros-core-0.8.6
sqlx-mysql-0.8.6
sqlx-postgres-0.8.6
sqlx-sqlite-0.8.6
stable_deref_trait-1.2.1
static_assertions-1.1.0
stringmetrics-2.2.2
stringprep-0.1.5
strsim-0.10.0
strsim-0.11.1
str_stack-0.1.1
strum-0.26.3
strum-0.27.2
strum_macros-0.26.4
strum_macros-0.27.2
subtle-2.6.1
supports-color-3.0.2
syn-0.15.44
syn-1.0.109
syn-2.0.119
syn-3.0.6
sync_wrapper-1.0.2
synstructure-0.14.0
sysctl-0.6.0
system-configuration-0.7.0
system-configuration-sys-0.6.0
tabwriter-1.4.1
tantivy-0.22.1
tantivy-bitpacker-0.6.0
tantivy-columnar-0.3.0
tantivy-common-0.7.0
tantivy-fst-0.5.0
tantivy-query-grammar-0.22.0
tantivy-sstable-0.3.0
tantivy-stacker-0.3.0
tantivy-tokenizer-api-0.3.0
tap-1.0.1
target-lexicon-0.13.5
tempfile-3.27.0
termcolor-1.4.1
test-log-0.2.21
test-log-core-0.2.21
test-log-macros-0.2.21
textwrap-0.16.4
thiserror-1.0.69
thiserror-2.0.21
thiserror-impl-1.0.69
thiserror-impl-2.0.21
thread_local-1.1.10
thrift-0.17.0
tiff-0.11.3
tikv-jemallocator-0.6.1
tikv-jemalloc-ctl-0.6.1
tikv-jemalloc-sys-0.6.1+5.3.0-1-ge13ca993e8ccb9ba9847cc330696e02839f328f7
time-0.3.55
time-core-0.1.9
time-macros-0.2.32
tiny-keccak-2.0.2
tinystr-0.8.4
tinytemplate-1.2.1
tinyvec-1.13.3
token-source-1.0.0
tokio-1.53.2
tokio-io-timeout-1.2.1
tokio-macros-2.7.2
tokio-native-tls-0.3.1
tokio-retry2-0.6.2
tokio-rustls-0.24.1
tokio-rustls-0.26.6
tokio-stream-0.1.19
tokio-test-0.4.6
tokio-util-0.7.19
toml-0.8.23
toml-0.9.12+spec-1.1.0
toml_datetime-0.6.11
toml_datetime-0.7.5+spec-1.1.0
toml_edit-0.22.27
toml_parser-1.1.4+spec-1.1.0
toml_write-0.1.2
toml_writer-1.1.3+spec-1.1.0
tonic-0.14.6
tonic-build-0.14.6
tonic-health-0.14.6
tonic-prost-0.14.6
tonic-prost-build-0.14.6
tower-0.4.13
tower-0.5.3
tower-http-0.4.4
tower-http-0.6.11
tower-layer-0.3.3
tower-service-0.3.3
tracing-0.1.44
tracing-attributes-0.1.31
tracing-core-0.1.36
tracing-log-0.2.0
tracing-opentelemetry-0.34.0
tracing-subscriber-0.3.23
tracing-test-0.2.6
tracing-test-macro-0.2.6
try-lock-0.2.5
tui-input-0.12.1
twox-hash-2.1.5
typed-path-0.12.3
typenum-1.20.1
ucd-trie-0.1.7
unarray-0.1.4
uncased-0.9.10
unicase-2.10.0
unicode-bidi-0.3.18
unicode-ident-1.0.26
unicode-normalization-0.1.25
unicode-properties-0.1.4
unicode-segmentation-1.13.3
unicode-truncate-1.1.0
unicode-width-0.1.14
unicode-width-0.2.0
unicode-xid-0.1.0
unsafe-libyaml-0.2.11
untrusted-0.7.1
untrusted-0.9.0
ureq-2.12.1
url-2.5.8
urlencoding-2.1.3
usearch-2.23.0
utf8_iter-1.0.4
utf8parse-0.2.2
utf8-ranges-1.0.5
utoipa-5.5.0
utoipa-axum-0.2.0
utoipa-gen-5.5.0
utoipa-swagger-ui-9.0.2
uuid-1.27.0
validator-0.19.0
validator_derive-0.19.0
valuable-0.1.1
vcpkg-0.2.15
version_check-0.9.5
vsimd-0.8.0
wait-timeout-0.2.1
wal3-0.1.0
walkdir-2.5.0
want-0.3.2
wasi-0.11.1+wasi-snapshot-preview1
wasip2-1.0.4+wasi-0.2.12
wasite-0.1.0
wasm-bindgen-0.2.129
wasm-bindgen-futures-0.4.79
wasm-bindgen-macro-0.2.129
wasm-bindgen-macro-support-0.2.129
wasm-bindgen-shared-0.2.129
wasm-streams-0.4.2
wasm-streams-0.5.0
webbrowser-1.2.4
webpki-root-certs-1.0.9
webpki-roots-0.26.11
webpki-roots-1.0.9
web-sys-0.3.106
web-time-1.1.0
weezl-0.1.12
whoami-1.6.1
winapi-0.3.9
winapi-i686-pc-windows-gnu-0.4.0
winapi-util-0.1.11
winapi-x86_64-pc-windows-gnu-0.4.0
windows_aarch64_gnullvm-0.48.5
windows_aarch64_gnullvm-0.52.6
windows_aarch64_gnullvm-0.53.1
windows_aarch64_msvc-0.48.5
windows_aarch64_msvc-0.52.6
windows_aarch64_msvc-0.53.1
windows-core-0.62.2
windows_i686_gnu-0.48.5
windows_i686_gnu-0.52.6
windows_i686_gnu-0.53.1
windows_i686_gnullvm-0.52.6
windows_i686_gnullvm-0.53.1
windows_i686_msvc-0.48.5
windows_i686_msvc-0.52.6
windows_i686_msvc-0.53.1
windows-implement-0.60.2
windows-interface-0.59.3
windows-link-0.2.1
windows-registry-0.6.1
windows-result-0.4.1
windows-strings-0.5.1
windows-sys-0.48.0
windows-sys-0.52.0
windows-sys-0.59.0
windows-sys-0.60.2
windows-sys-0.61.2
windows-targets-0.48.5
windows-targets-0.52.6
windows-targets-0.53.5
windows_x86_64_gnu-0.48.5
windows_x86_64_gnu-0.52.6
windows_x86_64_gnu-0.53.1
windows_x86_64_gnullvm-0.48.5
windows_x86_64_gnullvm-0.52.6
windows_x86_64_gnullvm-0.53.1
windows_x86_64_msvc-0.48.5
windows_x86_64_msvc-0.52.6
windows_x86_64_msvc-0.53.1
winnow-0.7.15
winnow-1.0.4
wit-bindgen-0.57.1
worker-0.1.0
writeable-0.6.4
wyz-0.5.1
x11rb-0.13.2
x11rb-protocol-0.13.2
xmlparser-0.13.6
yaml_serde-0.10.7
yansi-1.0.1
yoke-0.8.3
yoke-derive-0.8.4
zerocopy-0.8.62
zerocopy-derive-0.8.62
zerofrom-0.1.8
zerofrom-derive-0.1.8
zeroize-1.9.1
zeroize_derive-1.5.0
zerotrie-0.2.5
zerovec-0.11.8
zerovec-derive-0.11.6
zip-3.0.0
zip-8.6.0
zip-extract-0.2.3
zlib-rs-0.6.8
zmij-1.0.23
zopfli-0.8.3
zstd-0.13.3
zstd-safe-7.3.0
zstd-sys-2.1.0+zstd.1.5.7
zune-core-0.5.3
zune-jpeg-0.5.15
"

# Cargo must go after distutils-r1
inherit abseil-cpp distutils-r1 cargo grpc pypi re2

KEYWORDS="~amd64"
S="${WORKDIR}/${MY_PN}-${PV}"
SRC_URI="
$(cargo_crate_uris ${CRATES})
https://github.com/chroma-core/chroma/archive/refs/tags/${PV}.tar.gz
	-> ${P}.tar.gz
"
#https://github.com/chroma-core/hnswlib/archive/refs/tags/${CHROMA_CORE_HNSWLIB_PV}.tar.gz
#	-> chroma-core-hnswlib-${CHROMA_CORE_HNSWLIB_PV}.tar.gz

DESCRIPTION="the AI-native open-source embedding database"
HOMEPAGE="
	https://github.com/chroma-core/chroma
	https://pypi.org/project/chromadb
"
LICENSE="
	Apache-2.0
"
RESTRICT="mirror"
SLOT="0"
IUSE+="
${CPU_FLAGS_X86[@]}
${PROTOBUF_PYTHON[@]/+}
dev
ebuild_revision_15
"
REQUIRED_USE+="
	^^ (
		protobuf_python_4
		protobuf_python_5
	)
"

# grpcio:>=4 protobuf-python:>=4
gen_grpcio_rdepend_dev() {
	local impl
	for impl in "${PYTHON_COMPAT[@]}" ; do
		echo "
			python_single_target_${impl}? (
				dev-python/grpcio:${PROTOBUF_CPP_SLOT}[python_targets_${impl}(-)]
			)
		"
	done
}

gen_grpcio_bdepend_dev() {
	local impl
	for impl in "${PYTHON_COMPAT[@]}" ; do
		echo "
			(
				python_single_target_${impl}? (
					dev-python/grpcio-tools:${PROTOBUF_CPP_SLOT}[python_targets_${impl}(-)]
					dev-python/protobuf:${PROTOBUF_PYTHON_SLOT}[python_targets_${impl}(-)]
				)
			)
		"
	done
}

gen_grpcio_rdepend_rel() {
	local impl
	for impl in "${PYTHON_COMPAT[@]}" ; do
		echo "
			(
				python_single_target_${impl}? (
					dev-python/grpcio:${PROTOBUF_CPP_SLOT}[python_targets_${impl}(-)]
					dev-python/protobuf:${PROTOBUF_PYTHON_SLOT}[python_targets_${impl}(-)]
				)
			)
		"
	done
}

RDEPEND+="
	$(python_gen_cond_dep '
		>=dev-python/bcrypt-4.0.1[${PYTHON_USEDEP}]
		>=dev-python/build-1.0.3[${PYTHON_USEDEP}]
		>=dev-python/httpx-0.27.0[${PYTHON_USEDEP}]
		>=dev-python/jsonschema-4.19.0[${PYTHON_USEDEP}]
		>=dev-python/kubernetes-28.1.0[${PYTHON_USEDEP}]
		>=dev-python/mmh3-4.0.1[${PYTHON_USEDEP}]
		>=dev-python/orjson-3.9.12[${PYTHON_USEDEP}]
		>=dev-python/overrides-7.3.1[${PYTHON_USEDEP}]
		>=dev-python/pybase64-1.4.1[${PYTHON_USEDEP}]
		>=dev-python/pydantic-2.0[${PYTHON_USEDEP}]
		>=dev-python/pydantic-settings-2.0[${PYTHON_USEDEP}]
		>=dev-python/pypika-0.48.9[${PYTHON_USEDEP}]
		>=dev-python/pyyaml-6.0.0[${PYTHON_USEDEP}]
		>=dev-python/rich-10.11.0[${PYTHON_USEDEP}]
		>=dev-python/tenacity-8.2.3[${PYTHON_USEDEP}]
		>=dev-python/tokenizers-0.13.2[${PYTHON_USEDEP}]
		>=dev-python/tqdm-4.65.0[${PYTHON_USEDEP}]
		>=dev-python/typer-0.9.0[${PYTHON_USEDEP}]
		>=dev-python/typing-extensions-4.5.0[${PYTHON_USEDEP}]
		>=dev-python/uvicorn-0.18.3[${PYTHON_USEDEP},standard]
		dev-python/importlib-resources[${PYTHON_USEDEP}]
		virtual/numpy[${PYTHON_USEDEP}]
		protobuf_python_4? (
			dev-python/opentelemetry-api:4[${PYTHON_USEDEP}]
			dev-python/opentelemetry-exporter-otlp-proto-grpc:4[${PYTHON_USEDEP}]
			dev-python/opentelemetry-sdk:4[${PYTHON_USEDEP}]
		)
		protobuf_python_5? (
			dev-python/opentelemetry-api:5[${PYTHON_USEDEP}]
			dev-python/opentelemetry-exporter-otlp-proto-grpc:5[${PYTHON_USEDEP}]
			dev-python/opentelemetry-sdk:5[${PYTHON_USEDEP}]
		)
	')
	>=sci-ml/onnxruntime-1.14.1[${PYTHON_SINGLE_USEDEP},python]
	!dev? (
		|| (
			$(gen_grpcio_rdepend_rel)
		)
		dev-python/grpcio:=
		dev-python/protobuf:=
	)
	dev? (
		|| (
			$(gen_grpcio_rdepend_dev)
		)
		dev-python/grpcio-tools:=
		dev-python/protobuf:=
	)
"
DEPEND+="
	${RDEPEND}
"
# grpcio-tools version range was relaxed
# dev? ( protobuf ) requirement changed for opentelemetry-proto 1.29.0
BDEPEND+="
	$(python_gen_cond_dep '
		>=dev-util/maturin-1.0[${PYTHON_USEDEP}]
		<dev-util/maturin-2.0[${PYTHON_USEDEP}]

		>=dev-python/setuptools-61.0[${PYTHON_USEDEP}]
		>=dev-python/setuptools-scm-6.2[${PYTHON_USEDEP},toml(+)]
		dev? (
			~dev-python/black-23.3.0[${PYTHON_USEDEP}]
			~dev-python/chroma-hnswlib-0.7.6[${PYTHON_USEDEP}]
			>=dev-python/fastapi-0.115.9[${PYTHON_USEDEP}]
			~dev-python/hypothesis-6.112.2[${PYTHON_USEDEP},numpy(+)]
			>=dev-python/opentelemetry-instrumentation-fastapi-0.41_beta0[${PYTHON_USEDEP}]
			dev-python/build[${PYTHON_USEDEP}]
			dev-python/httpx[${PYTHON_USEDEP}]
			dev-python/mmh3[${PYTHON_USEDEP}]
			dev-python/mypy-protobuf[${PYTHON_USEDEP}]
			dev-python/pandas[${PYTHON_USEDEP}]
			dev-python/psutil[${PYTHON_USEDEP}]
			dev-python/pytest[${PYTHON_USEDEP}]
			dev-python/pytest-asyncio[${PYTHON_USEDEP}]
			dev-python/pytest-rerunfailures[${PYTHON_USEDEP}]
			dev-python/pytest-xdist[${PYTHON_USEDEP}]
			dev-python/setuptools-scm[${PYTHON_USEDEP}]
			dev-python/snowballstemmer[${PYTHON_USEDEP}]
			dev-python/types-protobuf[${PYTHON_USEDEP}]
		)
	')
	dev? (
		dev-python/grpcio-tools:=
		dev-python/protobuf:=
		dev-vcs/pre-commit[${PYTHON_SINGLE_USEDEP}]
		|| (
			$(gen_grpcio_bdepend_dev)
		)
	)
"
DOCS=( "README.md" )
PATCHES=(
	"${FILESDIR}/${PN}-1.5.9-use-yaml_serde.patch"
)

pkg_setup() {
	python-single-r1_pkg_setup
	rust_pkg_setup

	# Prevent overswapping
	export MAKEOPTS="-j1"
}

gen_git_tag() {
	local path="${1}"
	local tag_name="${2}"
einfo "Generating tag start for ${path}"
	pushd "${path}" >/dev/null 2>&1 || die
		git init || die
		git config user.email "name@example.com" || die
		git config user.name "John Doe" || die
		touch dummy || die
		git add dummy || die
		#git add -f * || die
		git commit -m "Dummy" || die
		git tag ${tag_name} || die
	popd >/dev/null 2>&1 || die
einfo "Generating tag done"
}

src_unpack() {
	# For maintenance
	unpack ${A}
#	die

	cargo_src_unpack
#	mv \
#		"${WORKDIR}/chromadb-rs-${CHROMADB_RS_COMMIT}" \
#		"${WORKDIR}/chromadb-${CHROMADB_RS_COMMIT}" \
#		|| die
#	mv \
#		"${WORKDIR}/hnswlib-${CHROMA_CORE_HNSWLIB_PV}" \
#		"${WORKDIR}/hnswlib" \
#		|| die
	cp -a \
		"${FILESDIR}/${PV}/Cargo."* \
		"${S}" \
		|| die
	die
	gen_git_tag "${S}" "${PV}"
}

src_prepare() {
	distutils-r1_src_prepare
}

python_configure() {
	if use protobuf5 ; then
		PROTOBUF_GRPC="5"
		PROTOBUF_CPP_SLOT="5"
		PROTOBUF_PYTHON_SLOT="${PROTOBUF_PYTHON_SLOT_5[@]}"
	elif use protobuf4 ; then
		PROTOBUF_GRPC="4"
		PROTOBUF_CPP_SLOT="4"
		PROTOBUF_PYTHON_SLOT="${PROTOBUF_PYTHON_SLOT_4[@]}"
	fi
	abseil-cpp_python_configure
	protobuf_python_configure
	re2_python_configure
	grpc_python_configure
	cargo_src_configure
}

src_configure() {
	if \
		   use cpu_flags_x86_avx \
		|| use cpu_flags_x86_avx512f \
		|| use cpu_flags_x86_sse \
	; then
		:
	else
		export HNSWLIB_NO_NATIVE=1
	fi
	distutils-r1_src_configure
}

python_compile() {
	#export HNSWLIB_NO_NATIVE=1
	cargo_src_compile
	distutils-r1_python_compile
}

src_compile() {
	distutils-r1_src_compile
}

src_install() {
	distutils-r1_src_install
	docinto "licenses"
	dodoc "LICENSE"
}

# OILEDMACHINE-OVERLAY-META:  CREATED-EBUILD
