# Copyright 2024-2025 Orson Teodoro <orsonteodoro@hotmail.com>
# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# TODO package (optional):
# mypy-protobuf

CPU_FLAGS_X86=(
	cpu_flags_x86_avx
	cpu_flags_x86_avx512f
	cpu_flags_x86_sse
)

inherit grpc-ver

MY_PN="chroma"

CHROMA_CORE_HNSWLIB_PV="0.8.1"
DISTUTILS_EXT=1
DISTUTILS_SINGLE_IMPL=1
DISTUTILS_USE_PEP517="maturin"
PYTHON_COMPAT=( "python3_"{11..12} )
GRPC_SLOTS_DEV=(
# Based on protobuf requirement for opentelemetry-proto 1.29.0
	"1.63" # protobuf 5.26
	"1.64" # protobuf 5.26
	"1.65" # protobuf 5.26
)
GRPC_SLOTS_REL=(
# Based on protobuf requirement for opentelemetry-proto 1.27.0
	${GRPC_PROTOBUF_3_SLOTS[@]}
	${GRPC_PROTOBUF_4_SLOTS[@]}
)
OPENTELEMETRY_PV_DEV="1.29.0"
OPENTELEMETRY_PV_REL="1.27.0"
OPENTELEMETRY_SLOT_DEV="0/${OPENTELEMETRY_PV_DEV}"
OPENTELEMETRY_SLOT_REL="0/${OPENTELEMETRY_PV_REL}"

# Generated by "./convert-cargo-lock.sh 1.0.5 1.0.5"
CHROMADB_RS_COMMIT="540c3e225e92ecea05039b73b69adf5875385c0e"
declare -A GIT_CRATES=(
[chromadb]="https://github.com/rescrv/chromadb-rs;540c3e225e92ecea05039b73b69adf5875385c0e;" # 2.0.0
[hnswlib]="https://github.com/chroma-core/hnswlib;340a6fff21f0ba2db2bc720636eba4d7736b9534;" # 0.8.1
)

EXCLUDE_CRATES="
chroma-benchmark-0.1.0
chroma-blockstore-0.1.0
chroma-cache-0.1.0
chroma-cli-1.0.1
chroma-config-0.1.0
chroma-distance-0.1.0
chroma-error-0.1.0
chroma-frontend-1.0.0
chroma-index-0.1.0
chroma-load-0.1.0
chroma-log-0.1.0
chroma-log-service-0.1.0
chroma-memberlist-0.1.0
chroma-segment-0.1.0
chroma-sqlite-0.1.0
chroma-storage-0.1.0
chroma-sysdb-0.1.0
chroma-system-0.1.0
chroma-tracing-0.1.0
chroma-types-0.1.0
chromadb-js-bindings-0.1.0
chromadb_rust_bindings-0.1.0
garbage_collector-0.1.0
"
# Generated by "./convert-cargo-lock.sh 1.0.5 1.0.5"
CRATES="
addr2line-0.21.0
adler-1.0.2
adler2-2.0.0
aes-0.8.4
ahash-0.8.11
aho-corasick-1.1.3
alloc-no-stdlib-2.0.4
alloc-stdlib-0.2.2
allocator-api2-0.2.18
android-tzdata-0.1.1
android_system_properties-0.1.5
anes-0.1.6
anstream-0.6.18
anstyle-1.0.10
anstyle-parse-0.2.6
anstyle-query-1.1.2
anstyle-wincon-3.0.6
anyhow-1.0.93
approx-0.5.1
arbitrary-1.4.1
arboard-3.4.1
arc-swap-1.7.1
array-util-1.0.2
arrayvec-0.7.6
arrow-52.2.0
arrow-arith-52.2.0
arrow-array-52.2.0
arrow-buffer-52.2.0
arrow-cast-52.2.0
arrow-csv-52.2.0
arrow-data-52.2.0
arrow-ipc-52.2.0
arrow-json-52.2.0
arrow-ord-52.2.0
arrow-row-52.2.0
arrow-schema-52.2.0
arrow-select-52.2.0
arrow-string-52.2.0
assert_cmd-2.0.16
assoc-0.1.3
async-channel-2.3.1
async-compression-0.4.18
async-stream-0.3.5
async-stream-impl-0.3.5
async-task-4.7.1
async-tempfile-0.6.0
async-trait-0.1.83
atoi-2.0.0
atomic-0.6.0
atomic-waker-1.1.2
auto_enums-0.8.6
autocfg-1.4.0
aws-config-1.5.4
aws-credential-types-1.2.1
aws-runtime-1.4.3
aws-sdk-s3-1.63.0
aws-sdk-sso-1.36.0
aws-sdk-ssooidc-1.37.0
aws-sdk-sts-1.36.0
aws-sigv4-1.2.5
aws-smithy-async-1.2.1
aws-smithy-checksums-0.60.13
aws-smithy-eventstream-0.60.5
aws-smithy-http-0.60.11
aws-smithy-json-0.60.7
aws-smithy-query-0.60.7
aws-smithy-runtime-1.7.3
aws-smithy-runtime-api-1.7.3
aws-smithy-types-1.2.9
aws-smithy-xml-0.60.9
aws-types-1.3.3
axum-0.7.9
axum-0.8.1
axum-core-0.4.5
axum-core-0.5.0
axum-macros-0.5.0
backoff-0.4.0
backon-1.3.0
backtrace-0.3.71
base16ct-0.1.1
base64-0.21.7
base64-0.22.1
base64-simd-0.8.0
base64ct-1.6.0
bincode-1.3.3
bit-set-0.8.0
bit-vec-0.4.4
bit-vec-0.8.0
bitflags-1.3.2
bitflags-2.9.0
bitpacking-0.9.2
bitvec-1.0.1
block-buffer-0.10.4
block2-0.5.1
bloom-0.3.2
brotli-6.0.0
brotli-decompressor-4.0.2
bstr-1.11.3
bumpalo-3.17.0
bytemuck-1.21.0
byteorder-1.5.0
byteorder-lite-0.1.0
bytes-1.10.1
bytes-utils-0.1.4
bzip2-0.4.4
bzip2-sys-0.1.11+1.0.8
cast-0.3.0
cc-1.2.1
census-0.4.2
cesu8-1.1.0
cfg-if-1.0.0
cfg_aliases-0.2.1
chroma-0.1.0
chrono-0.4.39
ciborium-0.2.2
ciborium-io-0.2.2
ciborium-ll-0.2.2
cipher-0.4.4
clap-4.5.28
clap_builder-4.5.27
clap_derive-4.5.28
clap_lex-0.7.4
clipboard-win-5.4.0
cmsketch-0.2.1
colorchoice-1.0.3
colored-3.0.0
combine-4.6.7
concurrent-queue-2.5.0
console-0.15.8
const-oid-0.9.6
const-random-0.1.18
const-random-macro-0.1.16
constant_time_eq-0.3.1
convert_case-0.6.0
convert_case-0.7.1
core-foundation-0.10.0
core-foundation-0.9.4
core-foundation-sys-0.8.7
core-graphics-0.23.2
core-graphics-types-0.1.3
cpufeatures-0.2.16
crc-3.2.1
crc-catalog-2.4.0
crc32c-0.6.8
crc32fast-1.4.2
criterion-0.5.1
criterion-plot-0.5.0
crossbeam-channel-0.5.12
crossbeam-deque-0.8.5
crossbeam-epoch-0.9.18
crossbeam-queue-0.3.12
crossbeam-utils-0.8.20
crossterm-0.29.0
crossterm_winapi-0.9.1
crunchy-0.2.2
crypto-bigint-0.4.9
crypto-bigint-0.5.5
crypto-common-0.1.6
csv-1.3.0
csv-core-0.1.11
ctor-0.2.9
darling-0.14.4
darling-0.20.10
darling_core-0.14.4
darling_core-0.20.10
darling_macro-0.14.4
darling_macro-0.20.10
deflate64-0.1.9
der-0.6.1
der-0.7.9
deranged-0.3.11
derivative-2.2.0
derive_arbitrary-1.4.1
derive_more-2.0.1
derive_more-impl-2.0.1
derive_utils-0.14.2
dialoguer-0.11.0
difflib-0.4.0
digest-0.10.7
dirs-5.0.1
dirs-6.0.0
dirs-sys-0.4.1
dirs-sys-0.5.0
displaydoc-0.2.5
doc-comment-0.3.3
document-features-0.2.11
dotenvy-0.15.7
downcast-rs-1.2.1
dyn-clone-1.0.17
ecdsa-0.14.8
either-1.13.0
elliptic-curve-0.12.3
encode_unicode-0.3.6
encoding_rs-0.8.35
equivalent-1.0.1
errno-0.3.10
error-code-3.3.1
etcetera-0.8.0
event-listener-5.3.1
event-listener-strategy-0.5.2
fastant-0.1.10
fastdivide-0.4.1
fastrace-0.7.8
fastrace-macro-0.7.8
fastrace-opentelemetry-0.8.0
fastrand-2.2.0
fdeflate-0.3.7
ff-0.12.1
figment-0.10.19
fixedbitset-0.4.2
flatbuffers-24.3.25
flate2-1.0.35
float-cmp-0.10.0
flume-0.11.0
fnv-1.0.7
foldhash-0.1.3
foreign-types-0.3.2
foreign-types-0.5.0
foreign-types-macros-0.2.3
foreign-types-shared-0.1.1
foreign-types-shared-0.3.1
form_urlencoded-1.2.1
foyer-0.15.1
foyer-common-0.15.1
foyer-intrusive-collections-0.10.0-dev
foyer-memory-0.15.1
foyer-storage-0.15.1
fs4-0.13.1
fs4-0.8.4
funty-2.0.0
futures-0.3.31
futures-channel-0.3.31
futures-core-0.3.31
futures-executor-0.3.31
futures-intrusive-0.5.0
futures-io-0.3.31
futures-macro-0.3.31
futures-sink-0.3.31
futures-task-0.3.31
futures-util-0.3.31
generator-0.7.5
generator-0.8.1
generic-array-0.14.7
gethostname-0.2.3
gethostname-0.4.3
getrandom-0.2.15
getrandom-0.3.1
gimli-0.28.1
glob-0.3.1
globset-0.4.15
gloo-timers-0.3.0
group-0.12.1
guacamole-0.11.0
h2-0.3.26
h2-0.4.7
half-2.4.1
hashbrown-0.12.3
hashbrown-0.13.2
hashbrown-0.14.5
hashbrown-0.15.2
hashlink-0.10.0
heck-0.4.1
heck-0.5.0
hermit-abi-0.3.9
hermit-abi-0.4.0
hex-0.4.3
hkdf-0.12.4
hmac-0.12.1
home-0.5.9
htmlescape-0.3.1
http-0.2.12
http-1.1.0
http-body-0.4.6
http-body-1.0.1
http-body-util-0.1.2
http-range-header-0.3.1
httparse-1.9.5
httpdate-1.0.3
humantime-2.2.0
hyper-0.14.31
hyper-1.5.1
hyper-rustls-0.24.2
hyper-rustls-0.27.3
hyper-timeout-0.4.1
hyper-timeout-0.5.1
hyper-tls-0.5.0
hyper-util-0.1.10
iana-time-zone-0.1.61
iana-time-zone-haiku-0.1.2
icu_collections-1.5.0
icu_locid-1.5.0
icu_locid_transform-1.5.0
icu_locid_transform_data-1.5.0
icu_normalizer-1.5.0
icu_normalizer_data-1.5.0
icu_properties-1.5.1
icu_properties_data-1.5.0
icu_provider-1.5.0
icu_provider_macros-1.5.0
ident_case-1.0.1
idna-1.0.3
idna_adapter-1.2.0
image-0.25.5
indexmap-1.9.3
indexmap-2.6.0
indicatif-0.17.9
indoc-2.0.5
inherent-1.0.11
inlinable_string-0.1.15
inout-0.1.4
instant-0.1.13
integer-encoding-3.0.4
ipnet-2.10.1
is-terminal-0.4.13
is_terminal_polyfill-1.70.1
iter-read-1.1.0
itertools-0.10.5
itertools-0.11.0
itertools-0.12.1
itertools-0.13.0
itertools-0.14.0
itoa-1.0.14
jni-0.21.1
jni-sys-0.3.0
jobserver-0.1.32
jpeg-decoder-0.3.1
js-sys-0.3.69
json-patch-1.4.0
jsonpath-rust-0.3.5
k8s-openapi-0.20.0
keccak-0.1.5
kube-0.87.2
kube-client-0.87.2
kube-core-0.87.2
kube-derive-0.87.2
kube-runtime-0.87.2
lazy_static-1.5.0
levenshtein_automata-0.2.1
lexical-core-0.8.5
lexical-parse-float-0.8.5
lexical-parse-integer-0.8.6
lexical-util-0.8.5
lexical-write-float-0.8.5
lexical-write-integer-0.8.5
libc-0.2.171
libloading-0.8.6
libm-0.2.10
libredox-0.1.3
libsqlite3-sys-0.30.1
linux-raw-sys-0.4.14
linux-raw-sys-0.9.3
litemap-0.7.4
litrs-0.4.1
lock_api-0.4.12
lockfree-object-pool-0.1.6
log-0.4.22
loom-0.5.6
lru-0.12.4
lz4-1.26.0
lz4-sys-1.10.0
lz4_flex-0.11.3
lzma-rs-0.3.0
madsim-0.2.30
madsim-macros-0.2.12
madsim-tokio-0.2.28
matchers-0.1.0
matchit-0.7.3
matchit-0.8.4
matrixmultiply-0.3.9
md-5-0.10.6
md5-0.7.0
mdac-0.1.0
measure_time-0.8.3
memchr-2.7.4
memmap2-0.9.5
memoffset-0.9.1
mime-0.3.17
mime_guess-2.0.5
minimal-lexical-0.2.1
miniz_oxide-0.7.4
miniz_oxide-0.8.0
minreq-2.12.0
mio-1.0.2
mixtrics-0.0.4
multimap-0.8.3
murmur3-0.5.2
murmurhash32-0.3.1
naive-timer-0.2.0
nanorand-0.7.0
napi-2.16.17
napi-build-2.1.6
napi-derive-2.16.13
napi-derive-backend-1.0.75
napi-sys-2.4.0
native-tls-0.2.12
ndarray-0.16.1
ndk-context-0.1.1
network-interface-1.1.4
nom-7.1.3
normalize-line-endings-0.3.0
nu-ansi-term-0.46.0
num-0.4.3
num-bigint-0.4.6
num-bigint-dig-0.8.4
num-complex-0.4.6
num-conv-0.1.0
num-integer-0.1.46
num-iter-0.1.45
num-rational-0.4.2
num-traits-0.2.19
num_cpus-1.16.0
number_prefix-0.4.0
numpy-0.23.0
objc-sys-0.3.5
objc2-0.5.2
objc2-app-kit-0.2.2
objc2-core-data-0.2.2
objc2-core-image-0.2.2
objc2-encode-4.1.0
objc2-foundation-0.2.2
objc2-metal-0.2.2
objc2-quartz-core-0.2.2
object-0.32.2
object_store-0.11.1
once_cell-1.20.2
oneshot-0.1.6
oorandom-11.1.3
openssl-0.10.66
openssl-macros-0.1.1
openssl-probe-0.1.5
openssl-sys-0.9.103
opentelemetry-0.27.0
opentelemetry-http-0.27.0
opentelemetry-otlp-0.27.0
opentelemetry-proto-0.27.0
opentelemetry_sdk-0.27.0
option-ext-0.2.0
ordered-float-2.10.1
ordered_hash_map-0.4.0
outref-0.5.1
overload-0.1.1
ownedbytes-0.7.0
owo-colors-3.5.0
p256-0.11.1
panic-message-0.3.0
parking-2.2.0
parking_lot-0.12.3
parking_lot_core-0.9.10
parquet-52.2.0
paste-1.0.15
pbkdf2-0.12.2
pear-0.2.9
pear_codegen-0.2.9
pem-3.0.4
pem-rfc7468-0.7.0
percent-encoding-2.3.1
pest-2.7.14
pest_derive-2.7.14
pest_generator-2.7.14
pest_meta-2.7.14
petgraph-0.6.4
pin-project-1.1.10
pin-project-internal-1.1.10
pin-project-lite-0.2.15
pin-utils-0.1.0
pkcs1-0.7.5
pkcs8-0.10.2
pkcs8-0.9.0
pkg-config-0.3.31
plotters-0.3.5
plotters-backend-0.3.5
plotters-svg-0.3.5
png-0.17.16
portable-atomic-1.9.0
portable-atomic-util-0.2.4
powerfmt-0.2.0
ppv-lite86-0.2.20
predicates-3.1.3
predicates-core-1.0.9
predicates-tree-1.0.12
prettyplease-0.2.16
proc-macro-error-attr2-2.0.0
proc-macro-error2-2.0.1
proc-macro2-0.4.30
proc-macro2-1.0.92
proc-macro2-diagnostics-0.10.1
proptest-1.6.0
proptest-derive-0.3.0
proptest-derive-0.5.1
proptest-state-machine-0.3.1
prost-0.12.3
prost-0.13.5
prost-build-0.12.3
prost-derive-0.12.3
prost-derive-0.13.5
prost-types-0.12.3
prost-types-0.13.5
pyo3-0.23.4
pyo3-build-config-0.23.4
pyo3-ffi-0.23.4
pyo3-macros-0.23.4
pyo3-macros-backend-0.23.4
quick-error-1.2.3
quick-xml-0.36.2
quinn-0.11.6
quinn-proto-0.11.9
quinn-udp-0.5.7
quote-0.6.13
quote-1.0.37
radium-0.7.0
rand-0.8.5
rand-0.9.0
rand_chacha-0.3.1
rand_chacha-0.9.0
rand_core-0.6.4
rand_core-0.9.3
rand_distr-0.4.3
rand_pcg-0.3.1
rand_xorshift-0.3.0
rand_xoshiro-0.6.0
random-port-0.1.1
rawpointer-0.2.1
rayon-1.10.0
rayon-core-1.12.1
redox_syscall-0.5.7
redox_users-0.4.6
redox_users-0.5.0
regex-1.11.1
regex-automata-0.1.10
regex-automata-0.4.9
regex-lite-0.1.6
regex-syntax-0.6.29
regex-syntax-0.8.5
reqwest-0.11.27
reqwest-0.12.9
rfc6979-0.3.1
ring-0.17.8
roaring-0.10.6
rsa-0.9.7
rtrb-0.3.1
rust-embed-8.5.0
rust-embed-impl-8.5.0
rust-embed-utils-8.5.0
rust-stemmers-1.2.0
rustc-demangle-0.1.24
rustc-hash-1.1.0
rustc-hash-2.0.0
rustc_version-0.4.1
rustix-0.38.41
rustix-1.0.3
rustls-0.21.12
rustls-0.23.18
rustls-native-certs-0.6.3
rustls-native-certs-0.8.1
rustls-pemfile-1.0.4
rustls-pemfile-2.2.0
rustls-pki-types-1.10.0
rustls-webpki-0.101.7
rustls-webpki-0.102.8
rustversion-1.0.14
rusty-fork-0.3.0
ryu-1.0.18
same-file-1.0.6
scc-2.2.4
schannel-0.1.23
schemars-0.8.21
schemars_derive-0.8.21
scoped-tls-1.0.1
scopeguard-1.2.0
sct-0.7.1
sdd-3.0.4
sea-query-0.32.1
sea-query-binder-0.7.0
sea-query-derive-0.4.2
sec1-0.3.0
secrecy-0.8.0
security-framework-2.11.1
security-framework-3.0.1
security-framework-sys-2.12.1
semver-1.0.26
seq-macro-0.3.6
serde-1.0.215
serde-pickle-1.2.0
serde-value-0.7.0
serde_derive-1.0.215
serde_derive_internals-0.29.1
serde_json-1.0.133
serde_path_to_error-0.1.16
serde_spanned-0.6.8
serde_urlencoded-0.7.1
serde_yaml-0.9.34+deprecated
serial_test-3.2.0
serial_test_derive-3.2.0
setsum-0.7.0
sha1-0.10.6
sha2-0.10.8
sha3-0.10.8
sharded-slab-0.1.7
shell-words-1.1.0
shlex-1.3.0
shuttle-0.7.1
signal-hook-0.3.17
signal-hook-mio-0.2.4
signal-hook-registry-1.4.2
signature-1.6.4
signature-2.2.0
simd-adler32-0.3.7
siphasher-1.0.1
sketches-ddsketch-0.2.2
slab-0.4.9
small_ctor-0.1.2
smallvec-1.13.2
snafu-0.8.5
snafu-derive-0.8.5
snap-1.1.1
socket2-0.5.7
spin-0.9.8
spki-0.6.0
spki-0.7.3
sqlx-0.8.3
sqlx-core-0.8.3
sqlx-macros-0.8.3
sqlx-macros-core-0.8.3
sqlx-mysql-0.8.3
sqlx-postgres-0.8.3
sqlx-sqlite-0.8.3
stable_deref_trait-1.2.0
static_assertions-1.1.0
stringprep-0.1.5
strsim-0.10.0
strsim-0.11.1
strum-0.27.1
strum_macros-0.27.1
subtle-2.6.1
syn-0.15.44
syn-1.0.109
syn-2.0.89
sync_wrapper-0.1.2
sync_wrapper-1.0.2
synstructure-0.13.1
system-configuration-0.5.1
system-configuration-sys-0.5.0
tantivy-0.22.0
tantivy-bitpacker-0.6.0
tantivy-columnar-0.3.0
tantivy-common-0.7.0
tantivy-fst-0.5.0
tantivy-query-grammar-0.22.0
tantivy-sstable-0.3.0
tantivy-stacker-0.3.0
tantivy-tokenizer-api-0.3.0
tap-1.0.1
target-lexicon-0.12.16
tempfile-3.14.0
termtree-0.5.1
thiserror-1.0.69
thiserror-2.0.4
thiserror-impl-1.0.69
thiserror-impl-2.0.4
thread_local-1.1.8
thrift-0.17.0
tiff-0.9.1
tikv-jemalloc-sys-0.6.0+5.3.0-1-ge13ca993e8ccb9ba9847cc330696e02839f328f7
tikv-jemallocator-0.6.0
time-0.3.36
time-core-0.1.2
time-macros-0.2.18
tiny-keccak-2.0.2
tinystr-0.7.6
tinytemplate-1.2.1
tinyvec-1.8.0
tinyvec_macros-0.1.1
tokio-1.41.1
tokio-io-timeout-1.2.0
tokio-macros-2.4.0
tokio-native-tls-0.3.1
tokio-rustls-0.24.1
tokio-rustls-0.26.0
tokio-stream-0.1.16
tokio-test-0.4.4
tokio-util-0.7.12
toml-0.8.20
toml_datetime-0.6.8
toml_edit-0.22.24
tonic-0.12.3
tonic-build-0.10.2
tonic-health-0.12.3
tower-0.4.13
tower-0.5.2
tower-http-0.4.4
tower-http-0.6.2
tower-layer-0.3.3
tower-service-0.3.3
tracing-0.1.40
tracing-attributes-0.1.27
tracing-bunyan-formatter-0.3.10
tracing-core-0.1.33
tracing-log-0.1.4
tracing-log-0.2.0
tracing-opentelemetry-0.28.0
tracing-subscriber-0.3.18
tracing-test-0.2.5
tracing-test-macro-0.2.5
try-lock-0.2.5
twox-hash-1.6.3
twox-hash-2.0.1
typenum-1.17.0
ucd-trie-0.1.7
unarray-0.1.4
uncased-0.9.10
unicase-2.8.1
unicode-bidi-0.3.18
unicode-ident-1.0.14
unicode-normalization-0.1.24
unicode-properties-0.1.3
unicode-segmentation-1.12.0
unicode-width-0.1.14
unicode-width-0.2.0
unicode-xid-0.1.0
unindent-0.2.3
unsafe-libyaml-0.2.11
untrusted-0.9.0
url-2.5.4
urlencoding-2.1.3
utf16_iter-1.0.5
utf8-ranges-1.0.5
utf8_iter-1.0.4
utf8parse-0.2.2
utoipa-5.3.1
utoipa-axum-0.2.0
utoipa-gen-5.3.1
utoipa-swagger-ui-9.0.0
uuid-1.11.0
uuid-macro-internal-1.11.0
validator-0.19.0
validator_derive-0.19.0
valuable-0.1.0
vcpkg-0.2.15
version_check-0.9.5
vsimd-0.8.0
wait-timeout-0.2.0
wal3-0.1.0
walkdir-2.5.0
want-0.3.1
wasi-0.11.0+wasi-snapshot-preview1
wasi-0.13.3+wasi-0.2.2
wasite-0.1.0
wasm-bindgen-0.2.92
wasm-bindgen-backend-0.2.92
wasm-bindgen-futures-0.4.42
wasm-bindgen-macro-0.2.92
wasm-bindgen-macro-support-0.2.92
wasm-bindgen-shared-0.2.92
wasm-streams-0.4.0
web-sys-0.3.69
web-time-1.1.0
webbrowser-1.0.3
webpki-roots-0.25.4
weezl-0.1.8
which-4.4.2
whoami-1.5.2
winapi-0.3.9
winapi-i686-pc-windows-gnu-0.4.0
winapi-util-0.1.8
winapi-x86_64-pc-windows-gnu-0.4.0
windows-0.48.0
windows-0.54.0
windows-core-0.52.0
windows-core-0.54.0
windows-registry-0.2.0
windows-result-0.1.1
windows-result-0.2.0
windows-strings-0.1.0
windows-sys-0.45.0
windows-sys-0.48.0
windows-sys-0.52.0
windows-sys-0.59.0
windows-targets-0.42.2
windows-targets-0.48.5
windows-targets-0.52.6
windows_aarch64_gnullvm-0.42.2
windows_aarch64_gnullvm-0.48.5
windows_aarch64_gnullvm-0.52.6
windows_aarch64_msvc-0.42.2
windows_aarch64_msvc-0.48.5
windows_aarch64_msvc-0.52.6
windows_i686_gnu-0.42.2
windows_i686_gnu-0.48.5
windows_i686_gnu-0.52.6
windows_i686_gnullvm-0.52.6
windows_i686_msvc-0.42.2
windows_i686_msvc-0.48.5
windows_i686_msvc-0.52.6
windows_x86_64_gnu-0.42.2
windows_x86_64_gnu-0.48.5
windows_x86_64_gnu-0.52.6
windows_x86_64_gnullvm-0.42.2
windows_x86_64_gnullvm-0.48.5
windows_x86_64_gnullvm-0.52.6
windows_x86_64_msvc-0.42.2
windows_x86_64_msvc-0.48.5
windows_x86_64_msvc-0.52.6
winnow-0.7.4
winreg-0.50.0
wit-bindgen-rt-0.33.0
worker-0.1.0
write16-1.0.0
writeable-0.5.5
wyz-0.5.1
x11rb-0.13.1
x11rb-protocol-0.13.1
xmlparser-0.13.6
yansi-1.0.1
yoke-0.7.5
yoke-derive-0.7.5
zerocopy-0.7.35
zerocopy-0.8.23
zerocopy-derive-0.7.35
zerocopy-derive-0.8.23
zerofrom-0.1.5
zerofrom-derive-0.1.5
zeroize-1.8.1
zeroize_derive-1.4.2
zerovec-0.10.4
zerovec-derive-0.10.3
zip-2.2.2
zip-extract-0.2.1
zopfli-0.8.1
zstd-0.13.0
zstd-safe-7.0.0
zstd-sys-2.0.9+zstd.1.5.5
"

# Cargo must go after distutils-r1
inherit distutils-r1 cargo pypi

KEYWORDS="~amd64"
S="${WORKDIR}/${MY_PN}-${PV}"
SRC_URI="
$(cargo_crate_uris ${CRATES})
https://github.com/chroma-core/chroma/archive/refs/tags/${PV}.tar.gz
	-> ${P}.tar.gz
https://github.com/chroma-core/hnswlib/archive/refs/tags/${CHROMA_CORE_HNSWLIB_PV}.tar.gz
	-> chroma-core-hnswlib-${CHROMA_CORE_HNSWLIB_PV}.tar.gz
"

DESCRIPTION="the AI-native open-source embedding database"
HOMEPAGE="
	https://github.com/chroma-core/chroma
	https://pypi.org/project/chromadb
"
LICENSE="
	Apache-2.0
"
RESTRICT="mirror"
SLOT="0/$(ver_cut 1-2 ${PV})"
IUSE+="
${CPU_FLAGS_X86[@]}
dev
ebuild_revision_3
"
gen_grpcio_rdepend_dev() {
	local s
	for s in ${GRPC_SLOTS_DEV[@]} ; do
		local impl
		for impl in ${PYTHON_COMPAT[@]} ; do
			echo "
				python_single_target_${impl}? (
					=dev-python/grpcio-${s}*[python_targets_${impl}(-)]
				)
			"
		done
	done
}
gen_grpcio_bdepend_dev() {
	local s1
	local s2
	for s1 in ${GRPC_SLOTS_DEV[@]} ; do
		s2=$(grpc_get_protobuf_slot "${s1}")
		local impl
		for impl in ${PYTHON_COMPAT[@]} ; do
			echo "
				(
					python_single_target_${impl}? (
						=dev-python/grpcio-tools-${s1}*[python_targets_${impl}(-)]
						dev-python/protobuf:0/${s2}[python_targets_${impl}(-)]
					)
				)
			"
		done
	done
}
gen_grpcio_rdepend_rel() {
	local s1
	local s2
	for s1 in ${GRPC_SLOTS_REL[@]} ; do
		s2=$(grpc_get_protobuf_slot "${s1}")
		local impl
		for impl in ${PYTHON_COMPAT[@]} ; do
			echo "
				(
					python_single_target_${impl}? (
						=dev-python/grpcio-${s1}*[python_targets_${impl}(-)]
						dev-python/protobuf:0/${s2}[python_targets_${impl}(-)]
					)
				)
			"
		done
	done
}
RDEPEND+="
	!dev? (
		|| (
			$(gen_grpcio_rdepend_rel)
		)
		dev-python/grpcio:=
		dev-python/protobuf:=
	)
	dev? (
		|| (
			$(gen_grpcio_rdepend_dev)
		)
		dev-python/grpcio-tools:=
		dev-python/protobuf:=
	)
	$(python_gen_cond_dep '
		>=dev-python/bcrypt-4.0.1[${PYTHON_USEDEP}]
		>=dev-python/chroma-hnswlib-0.7.6[${PYTHON_USEDEP}]
		>=dev-python/fastapi-0.115.9[${PYTHON_USEDEP}]
		>=dev-python/httpx-0.27.0[${PYTHON_USEDEP}]
		>=dev-python/jsonschema-4.19.0[${PYTHON_USEDEP}]
		>=dev-python/kubernetes-28.1.0[${PYTHON_USEDEP}]
		>=dev-python/mmh3-4.0.1[${PYTHON_USEDEP}]
		>=dev-python/numpy-1.22.5[${PYTHON_USEDEP}]
		>=dev-python/orjson-3.9.12[${PYTHON_USEDEP}]
		>=dev-python/overrides-7.3.1[${PYTHON_USEDEP}]
		>=dev-python/pydantic-1.9[${PYTHON_USEDEP}]
		>=dev-python/pypika-0.48.9[${PYTHON_USEDEP}]
		>=dev-python/pyyaml-6.0.0[${PYTHON_USEDEP}]
		>=dev-python/rich-10.11.0[${PYTHON_USEDEP}]
		>=dev-python/tenacity-8.2.3[${PYTHON_USEDEP}]
		>=dev-python/tqdm-4.65.0[${PYTHON_USEDEP}]
		>=dev-python/typer-0.9.0[${PYTHON_USEDEP}]
		>=dev-python/typing-extensions-4.5.0[${PYTHON_USEDEP}]
		>=dev-python/uvicorn-0.18.3[${PYTHON_USEDEP},standard(+)]
		dev-python/importlib-resources[${PYTHON_USEDEP}]
		!dev? (
			~dev-python/opentelemetry-api-'${OPENTELEMETRY_PV_REL}'[${PYTHON_USEDEP}]
			~dev-python/opentelemetry-exporter-otlp-proto-grpc-'${OPENTELEMETRY_PV_REL}'[${PYTHON_USEDEP}]
			~dev-python/opentelemetry-instrumentation-fastapi-0.48_beta0:'${OPENTELEMETRY_SLOT_REL}'[${PYTHON_USEDEP}]
			~dev-python/opentelemetry-sdk-'${OPENTELEMETRY_PV_REL}'[${PYTHON_USEDEP}]
		)
		dev? (
			~dev-python/opentelemetry-api-'${OPENTELEMETRY_PV_DEV}'[${PYTHON_USEDEP}]
			~dev-python/opentelemetry-exporter-otlp-proto-grpc-'${OPENTELEMETRY_PV_DEV}'[${PYTHON_USEDEP}]
			~dev-python/opentelemetry-instrumentation-fastapi-0.50_beta0:'${OPENTELEMETRY_SLOT_DEV}'[${PYTHON_USEDEP}]
			~dev-python/opentelemetry-sdk-'${OPENTELEMETRY_PV_DEV}'[${PYTHON_USEDEP}]
		)
	')
	>=dev-python/posthog-2.4.0[${PYTHON_SINGLE_USEDEP}]
	>=sci-ml/onnxruntime-1.14.1[${PYTHON_SINGLE_USEDEP},python]
	>=sci-ml/tokenizers-0.13.2[${PYTHON_SINGLE_USEDEP}]
"
DEPEND+="
	${RDEPEND}
"
# grpcio-tools version range was relaxed
# dev? ( protobuf ) requirement changed for opentelemetry-proto 1.29.0
BDEPEND+="
	$(python_gen_cond_dep '
		>=dev-python/setuptools-61.0[${PYTHON_USEDEP}]
		>=dev-python/setuptools-scm-6.2[${PYTHON_USEDEP},toml(+)]
		dev-python/setuptools-git-versioning[${PYTHON_USEDEP}]
		dev? (
			>=dev-python/black-23.3.0[${PYTHON_USEDEP}]
			>=dev-python/hypothesis-6.112.2[${PYTHON_USEDEP},numpy(+)]
			dev-python/build[${PYTHON_USEDEP}]
			dev-python/httpx[${PYTHON_USEDEP}]
			dev-python/mypy-protobuf[${PYTHON_USEDEP}]
			dev-python/psutil[${PYTHON_USEDEP}]
			dev-python/pytest[${PYTHON_USEDEP}]
			dev-python/pytest-asyncio[${PYTHON_USEDEP}]
			dev-python/pytest-xdist[${PYTHON_USEDEP}]
			dev-python/setuptools-scm[${PYTHON_USEDEP}]
			dev-python/types-protobuf[${PYTHON_USEDEP}]
		)
	')
	dev? (
		|| (
			$(gen_grpcio_bdepend_dev)
		)
		dev-python/grpcio-tools:=
		dev-python/protobuf:=
		dev-vcs/pre-commit[${PYTHON_SINGLE_USEDEP}]
	)
"
DOCS=( "README.md" )

pkg_setup() {
	python-single-r1_pkg_setup
	rust_pkg_setup

	# Prevent overswapping
	export MAKEOPTS="-j1"
}

gen_git_tag() {
	local path="${1}"
	local tag_name="${2}"
einfo "Generating tag start for ${path}"
	pushd "${path}" >/dev/null 2>&1 || die
		git init || die
		git config user.email "name@example.com" || die
		git config user.name "John Doe" || die
		touch dummy || die
		git add dummy || die
		#git add -f * || die
		git commit -m "Dummy" || die
		git tag ${tag_name} || die
	popd >/dev/null 2>&1 || die
einfo "Generating tag done"
}

src_unpack() {
	# For maintenance
	#unpack ${A}
	#die

	cargo_src_unpack
	mv \
		"${WORKDIR}/chromadb-rs-${CHROMADB_RS_COMMIT}" \
		"${WORKDIR}/chromadb-${CHROMADB_RS_COMMIT}" \
		|| die
	mv \
		"${WORKDIR}/hnswlib-${CHROMA_CORE_HNSWLIB_PV}" \
		"${WORKDIR}/hnswlib" \
		|| die
	#cp -a \
	#	"${FILESDIR}/${PV}/Cargo."* \
	#	"${S}" \
	#	|| die
	gen_git_tag "${S}" "${PV}"
}

src_prepare() {
	distutils-r1_src_prepare
}

python_configure() {
	cargo_src_configure
}

src_configure() {
	if \
		   use cpu_flags_x86_avx \
		|| use cpu_flags_x86_avx512f \
		|| use cpu_flags_x86_sse \
	; then
		:
	else
		export HNSWLIB_NO_NATIVE=1
	fi
	distutils-r1_src_configure
}

python_compile() {
	#export HNSWLIB_NO_NATIVE=1
	cargo_src_compile
	distutils-r1_python_compile
}

src_compile() {
	distutils-r1_src_compile
}

src_install() {
	distutils-r1_src_install
	docinto "licenses"
	dodoc "LICENSE"
}

# OILEDMACHINE-OVERLAY-META:  CREATED-EBUILD
