#!/bin/sh
FANCONTROL_CONFIGFILE=${FANCONTROL_CONFIGFILE:-"/etc/fancontrol"}
FANCONTROL_SSDARGS=${FANCONTROL_SSDARGS:-"--background --wait 1000"}
FANCONTROL_TERMTIMEOUT=${FANCONTROL_TERMTIMEOUT:-"TERM/60/KILL/5"}

fancontrol ${FANCONTROL_CONFIGFILE}
