#!/bin/bash
NODE_SLOT=@NODE_SLOT@
export PATH="/usr/lib/node/${NODE_SLOT}/bin:${PATH}"
main() {
	cd "/opt/lobehub"
	source "/etc/conf.d/lobehub"
	# TODO add sandbox
	node "/opt/lobehub/startServer.js"
}
main
