packages:
  - 'packages/*'
  - 'sticker-creator'

allowedDeprecatedVersions:
  '@humanwhocodes/config-array': '0.11.14'
  '@humanwhocodes/object-schema': '2.0.3'
  '@npmcli/move-file': '2.0.1'
  'abab': '2.0.6'
  'are-we-there-yet': '2.0.0'
  'boolean': '3.2.0'
  'eslint': '8.38.0'
  'expect-playwright': '0.8.0'
  'form-data': '2.5.4'
  'deep-diff': '0.3.8'
  'domexception': '1.0.1'
  'gauge': '3.0.2'
  'glob': '7.2.3 || 8.1.0 || 10.5.0'
  'har-validator': '5.1.5'
  'has-own': '1.0.1'
  'inflight': '1.0.6'
  'jest-playwright-preset': '4.0.0'
  'jest-process-manager': '0.4.0'
  'lodash.isequal': '4.5.0'
  'node-domexception': '1.0.0'
  'npmlog': '5.0.1'
  'request': '2.88.2'
  'request-promise-native': '1.0.9'
  'rimraf': '3.0.2 || 2.6.3'
  'tar': '6.2.1'
  'uuid': '3.4.0 || 8.3.2 || 9.0.1'
  'w3c-hr-time': '1.0.2'
  'whatwg-encoding': '1.0.5 || 2.0.0'

blockExoticSubdeps: false
strictDepBuilds: true
allowBuilds:
  # Enabled Builds: Use specific version
  #   ex: 'package@0.0.0': true
  '@indutny/mac-screen-share@1.0.13': true
  '@indutny/simple-windows-notifications@2.0.16': true
  '@parcel/watcher@2.5.6': true
  '@signalapp/libsignal-client@0.92.2': true # duplicate package
  '@signalapp/libsignal-client@0.96.4': true
  '@signalapp/ringrtc@2.69.4': true
  '@signalapp/sqlcipher@3.3.9': true
  '@signalapp/windows-ucv@1.0.1': true
  '@swc/core@1.10.16': true
  '@tailwindcss/oxide@4.3.0': true
  'electron@23.3.13': false # duplicate package
  'electron@42.3.0': true
  'fs-xattr@0.4.0': true
  'canvas@2.11.2': false # For generating lockfile

  # Disabled Builds: Use wildcard version
  #   ex: 'package': false
  'bufferutil': false
  'core-js': false
  'electron-winstaller': false
  'es5-ext': false
  'esbuild': false
  'utf-8-validate': false
  '@signalapp/ringrtc': true

# Bans or rollbaks
overrides:
  'canvas': '-' # Deny
