#!/bin/bash

ARGS=( "${@}" )

main() {
	cd "/opt/local-recall"
	if [[ -e "/etc/conf.d/local-recall.conf" ]] ; then
		source "/etc/conf.d/local-recall.conf"
	fi
	# TODO sandbox local-recall
	./local-recall "${ARGS[@]}"
}

main
