#!/bin/bash
export PATH=$PATH:/opt/crark
DIR=`pwd`
if [[ $DIR != "/opt/crark" ]]; then
	echo "Copying rarcrypt dlls...  (Remove it if crark fails.)"
	cp /opt/crark/{rarcrypt30-2.dll,rarcrypt30-5.dll,rarcrypt50-2.dll,rarcrypt50-5.dll,rarcrypt30-3.dll,rarcrypt50-3.dll} ./
fi
/opt/crark/crark-cuda $*
if [[ $DIR != "/opt/crark" ]]; then
	echo "Removing rarcrypt dlls..."
	rm {rarcrypt30-2.dll,rarcrypt30-5.dll,rarcrypt50-2.dll,rarcrypt50-5.dll,rarcrypt30-3.dll,rarcrypt50-3.dll}
fi
