# Copyright 2023 Orson Teodoro <orsonteodoro@hotmail.com>
# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# p20230209 is based on last commit of
# https://github.com/tensorflow/tensorboard/tree/2.12.2/tensorboard/data/server

EAPI=8

MY_PV="2.12.2"

DISTUTILS_SINGLE_IMPL=1
DISTUTILS_USE_PEP517="standalone"
PYTHON_COMPAT=( python3_{8..11} )

# Auto-Generated by cargo-ebuild 0.5.4
CRATES="
	aho-corasick-0.7.18
	anyhow-1.0.34
	async-stream-0.3.0
	async-stream-impl-0.3.0
	async-trait-0.1.41
	atty-0.2.14
	autocfg-1.0.1
	base64-0.13.0
	bitflags-1.2.1
	build_const-0.2.1
	bumpalo-3.12.0
	byteorder-1.3.4
	bytes-0.5.6
	bytes-1.0.1
	cc-1.0.66
	cfg-if-0.1.10
	cfg-if-1.0.0
	clap-3.0.0-beta.2
	clap_derive-3.0.0-beta.2
	const_fn-0.4.5
	core-foundation-0.9.3
	core-foundation-sys-0.8.3
	crc-1.8.1
	crossbeam-0.8.0
	crossbeam-channel-0.5.0
	crossbeam-deque-0.8.1
	crossbeam-epoch-0.9.1
	crossbeam-queue-0.3.1
	crossbeam-utils-0.8.8
	dirs-next-2.0.0
	dirs-sys-next-0.1.2
	either-1.6.1
	encoding_rs-0.8.26
	env_logger-0.8.2
	fixedbitset-0.4.1
	fnv-1.0.7
	form_urlencoded-1.0.0
	futures-channel-0.3.8
	futures-core-0.3.12
	futures-io-0.3.12
	futures-macro-0.3.8
	futures-sink-0.3.8
	futures-task-0.3.8
	futures-util-0.3.8
	gcp_auth-0.7.4
	getrandom-0.1.15
	getrandom-0.2.1
	h2-0.3.13
	hashbrown-0.11.2
	heck-0.3.1
	hermit-abi-0.1.17
	http-0.2.1
	http-body-0.4.5
	httparse-1.7.1
	httpdate-1.0.2
	humantime-2.0.1
	hyper-0.14.19
	hyper-rustls-0.22.1
	hyper-rustls-0.23.0
	hyper-timeout-0.4.1
	idna-0.2.0
	indexmap-1.8.2
	ipnet-2.3.0
	itertools-0.10.3
	itoa-0.4.6
	itoa-1.0.2
	js-sys-0.3.47
	lazy_static-1.4.0
	libc-0.2.126
	lock_api-0.4.6
	log-0.4.11
	matches-0.1.8
	memchr-2.5.0
	memoffset-0.6.1
	mime-0.3.16
	mio-0.8.3
	multimap-0.8.2
	num_cpus-1.13.0
	num_threads-0.1.6
	once_cell-1.5.2
	openssl-probe-0.1.5
	os_str_bytes-2.4.0
	parking_lot-0.12.1
	parking_lot_core-0.9.3
	percent-encoding-2.1.0
	petgraph-0.6.2
	pin-project-1.0.12
	pin-project-internal-1.0.12
	pin-project-lite-0.2.9
	pin-utils-0.1.0
	ppv-lite86-0.2.10
	proc-macro-error-1.0.4
	proc-macro-error-attr-1.0.4
	proc-macro-hack-0.5.19
	proc-macro-nested-0.1.7
	proc-macro2-1.0.43
	prost-0.9.0
	prost-build-0.9.0
	prost-derive-0.9.0
	prost-types-0.9.0
	quote-1.0.7
	rand-0.7.3
	rand-0.8.2
	rand_chacha-0.2.2
	rand_chacha-0.3.0
	rand_core-0.5.1
	rand_core-0.6.1
	rand_hc-0.2.0
	rand_hc-0.3.0
	rayon-1.5.0
	rayon-core-1.9.0
	redox_syscall-0.1.57
	redox_syscall-0.2.16
	redox_users-0.4.3
	regex-1.5.6
	regex-syntax-0.6.26
	remove_dir_all-0.5.3
	reqwest-0.11.0
	ring-0.16.20
	rustls-0.19.0
	rustls-0.20.6
	rustls-native-certs-0.6.2
	rustls-pemfile-1.0.1
	ryu-1.0.5
	same-file-1.0.6
	schannel-0.1.20
	scopeguard-1.1.0
	sct-0.6.1
	sct-0.7.0
	security-framework-2.3.1
	security-framework-sys-2.6.1
	serde-1.0.144
	serde_derive-1.0.144
	serde_json-1.0.61
	serde_urlencoded-0.7.0
	slab-0.4.2
	smallvec-1.10.0
	socket2-0.4.4
	spin-0.5.2
	strsim-0.10.0
	syn-1.0.99
	tempfile-3.1.0
	termcolor-1.1.0
	textwrap-0.12.1
	thiserror-1.0.22
	thiserror-impl-1.0.22
	time-0.3.14
	tinyvec-1.1.1
	tinyvec_macros-0.1.0
	tokio-1.19.2
	tokio-io-timeout-1.2.0
	tokio-macros-1.8.0
	tokio-rustls-0.22.0
	tokio-rustls-0.23.4
	tokio-stream-0.1.2
	tokio-util-0.6.6
	tokio-util-0.7.3
	tonic-0.6.2
	tonic-build-0.6.2
	tonic-reflection-0.3.0
	tower-0.4.11
	tower-layer-0.3.1
	tower-service-0.3.0
	tracing-0.1.34
	tracing-attributes-0.1.21
	tracing-core-0.1.26
	tracing-futures-0.2.5
	try-lock-0.2.3
	unicode-bidi-0.3.4
	unicode-ident-1.0.3
	unicode-normalization-0.1.16
	unicode-segmentation-1.6.0
	unicode-width-0.1.8
	untrusted-0.7.1
	url-2.2.0
	vec_map-0.8.2
	version_check-0.9.2
	walkdir-2.3.1
	want-0.3.0
	wasi-0.9.0+wasi-snapshot-preview1
	wasi-0.10.1+wasi-snapshot-preview1
	wasi-0.11.0+wasi-snapshot-preview1
	wasm-bindgen-0.2.70
	wasm-bindgen-backend-0.2.70
	wasm-bindgen-futures-0.4.20
	wasm-bindgen-macro-0.2.70
	wasm-bindgen-macro-support-0.2.70
	wasm-bindgen-shared-0.2.70
	web-sys-0.3.47
	webpki-0.21.4
	webpki-0.22.0
	webpki-roots-0.21.1
	which-4.3.0
	winapi-0.3.9
	winapi-i686-pc-windows-gnu-0.4.0
	winapi-util-0.1.5
	winapi-x86_64-pc-windows-gnu-0.4.0
	windows-sys-0.36.1
	windows_aarch64_msvc-0.36.1
	windows_i686_gnu-0.36.1
	windows_i686_msvc-0.36.1
	windows_x86_64_gnu-0.36.1
	windows_x86_64_msvc-0.36.1
	winreg-0.7.0
"

inherit cargo distutils-r1

DESCRIPTION="Fast data loading for TensorBoard"
HOMEPAGE="
https://github.com/tensorflow/tensorboard/tree/master/tensorboard/data/server
"
CARGO_LICENSES="
	Apache-2.0
	Apache-2.0-with-LLVM-exceptions
	Boost-1.0
	ISC
	MIT
	MPL-2.0
	Unicode-DFS-2016
	Unlicense
	ZLIB
"
LICENSE="
	${CARGO_LICENSES}
	all-rights-reserved
	Apache-2.0
"
# The distro Apache-2.0 license template does not have all rights reserved, but
# it appears in the LICENSE file.
KEYWORDS="~amd64 ~arm ~arm64 ~mips ~mips64 ~ppc ~ppc64 ~x86"
SLOT="0/$(ver_cut 1-2 ${PV})"
IUSE+=" test r1"
PROTOBUF_SLOT="0/32"
RDEPEND="
	${PYTHON_DEPS}
	$(python_gen_cond_dep '
		(
			<dev-python/google-auth-3[${PYTHON_USEDEP}]
			>=dev-python/google-auth-1.6.3[${PYTHON_USEDEP}]
		)
		(
			<dev-python/google-auth-oauthlib-1.1[${PYTHON_USEDEP}]
			>=dev-python/google-auth-oauthlib-0.5[${PYTHON_USEDEP}]
		)
		(
			<dev-python/requests-3[${PYTHON_USEDEP}]
			>=dev-python/requests-2.21.0[${PYTHON_USEDEP}]
		)
		>=dev-python/absl-py-0.4[${PYTHON_USEDEP}]
		>=dev-python/markdown-2.6.8[${PYTHON_USEDEP}]
		>=dev-python/numpy-1.12.0[${PYTHON_USEDEP}]
		>=dev-python/tensorboard-plugin-wit-1.6.0[${PYTHON_USEDEP}]
		>=dev-python/werkzeug-1.0.1[${PYTHON_USEDEP}]
		dev-python/protobuf-python:'${PROTOBUF_SLOT}'[${PYTHON_USEDEP}]
		|| (
			=dev-python/grpcio-1.49*:=[${PYTHON_USEDEP}]
			=dev-python/grpcio-1.50*:=[${PYTHON_USEDEP}]
			=dev-python/grpcio-1.51*:=[${PYTHON_USEDEP}]
			=dev-python/grpcio-1.52*:=[${PYTHON_USEDEP}]
		)
	')
"
BDEPEND="
	${PYTHON_DEPS}
	$(python_gen_cond_dep '
		>=dev-python/setuptools-41[${PYTHON_USEDEP}]
		>=dev-python/wheel-0.26[${PYTHON_USEDEP}]
		>=dev-python/black-22.6.0[${PYTHON_USEDEP}]
		>=dev-python/flake8-3.7.8[${PYTHON_USEDEP}]
		>=dev-util/yamllint-1.17.0[${PYTHON_USEDEP}]
		dev-python/virtualenv[${PYTHON_USEDEP}]
		test? (
			>=dev-python/boto3-1.9.86[${PYTHON_USEDEP}]
			>=dev-python/fsspec-0.7.4[${PYTHON_USEDEP}]
			>=dev-python/moto-1.3.7[${PYTHON_USEDEP}]
			>=dev-python/pandas-1.0[${PYTHON_USEDEP}]
			|| (
				=dev-python/grpcio-testing-1.49*:=[${PYTHON_USEDEP}]
				=dev-python/grpcio-testing-1.50*:=[${PYTHON_USEDEP}]
				=dev-python/grpcio-testing-1.51*:=[${PYTHON_USEDEP}]
				=dev-python/grpcio-testing-1.52*:=[${PYTHON_USEDEP}]
			)
		)
	')
	>=virtual/rust-1.65.0
	app-arch/unzip
	|| (
		>=dev-lang/rust-bin-1.51.0[rustfmt]
		>=dev-lang/rust-1.51.0[rustfmt]
	)
"
SRC_URI="
$(cargo_crate_uris)
"
TARBALL_TYPE="tensorboard" # Can be tensorboard, tensorboard-data-server
if [[ "${TARBALL_TYPE}" == "tensorboard" ]] ; then
	SRC_URI+="
https://github.com/tensorflow/tensorboard/archive/refs/tags/${MY_PV}.tar.gz
	-> tensorboard-${MY_PV}.tar.gz
	"
	S_PROJ="${WORKDIR}/tensorboard-${MY_PV}"
	S="${S_PROJ}/tensorboard/data/server"
else
	SRC_URI+="
https://github.com/tensorflow/tensorboard/archive/refs/tags/data-server-v${PV}.tar.gz
	-> ${P}.tar.gz
	"
	S_PROJ="${WORKDIR}/${PN}-v${PV}"
	S="${WORKDIR}/${PN}-v${PV}/tensorboard/data/server"
fi
RESTRICT="mirror"
DOCS=( )

pkg_setup() {
	python_setup
}

src_unpack() {
	cargo_src_unpack
}

python_configure() {
	cargo_src_configure
}

src_configure() {
	distutils-r1_src_prepare
}

python_compile() {
	cargo_src_compile
	cd "${S_PROJ}" || die
	mkdir -p "${T}/pip_package" || die
	${EPYTHON} tensorboard/data/server/pip_package/build.py \
		--server-binary tensorboard/data/server/target/release/rustboard \
		--out-dir "${T}/pip_package" \
		|| die
	local wheel_path=$(realpath "${T}/pip_package/"*".whl")
	local d
	if [[ "${TARBALL_TYPE}" == "tensorboard" ]] ; then
		d="${WORKDIR}/tensorboard-${MY_PV}_${EPYTHON}/install"
	else
		d="${WORKDIR}/tensorboard-$(ver_cut 1-3 ${PV})_${EPYTHON}/install"
	fi
	distutils_wheel_install "${d}" \
		"${wheel_path}"
	local d2="${d}/usr/bin"
	mkdir -p "${d2}" || die
	touch "${d2}/"{"${EPYTHON}",python3,python,pyvenv.cfg}
}

src_compile() {
	distutils-r1_src_compile
}

src_install() {
	docinto licenses
	cd "${S_PROJ}" || die
	dodoc LICENSE
	BUILD_DIR="${S_PROJ}"
	distutils-r1_src_install
}

pkg_postinst() {
einfo "Reported by cargo-ebuild"
echo \
"
Error: Found 4 vulnerabilities:

Crate:    h2
Version:  0.3.13
Title:    Resource exhaustion vulnerability in h2 may lead to Denial of Service (DoS)
Date:     2023-04-14
ID:       RUSTSEC-2023-0034
URL:      https://rustsec.org/advisories/RUSTSEC-2023-0034
Solution: Upgrade to >=0.3.17

Crate:    rand_core
Version:  0.6.1
Title:    Incorrect check on buffer length when seeding RNGs
Date:     2021-02-12
ID:       RUSTSEC-2021-0023
URL:      https://rustsec.org/advisories/RUSTSEC-2021-0023
Solution: Upgrade to >=0.6.2

Crate:    remove_dir_all
Version:  0.5.3
Title:    Race Condition Enabling Link Following and Time-of-check Time-of-use (TOCTOU)
Date:     2023-02-24
ID:       RUSTSEC-2023-0018
URL:      https://rustsec.org/advisories/RUSTSEC-2023-0018
Solution: Upgrade to >=0.8.0

Crate:    tokio
Version:  1.19.2
Title:    reject_remote_clients Configuration corruption
Date:     2023-01-04
ID:       RUSTSEC-2023-0001
URL:      https://rustsec.org/advisories/RUSTSEC-2023-0001
Solution: Upgrade to >=1.18.4, <1.19.0 or >=1.20.3, <1.21.0 or >=1.23.1
"
#Please fix the issues or use "--noaudit" flag.
}

# OILEDMACHINE-OVERLAY-META:  CREATED-EBUILD
