#!/bin/bash
export PATH=$PATH:/opt/crark
DIR=`pwd`
if [[ $DIR != "/opt/crark" ]]; then
	echo "Copying rarcrypt-cl.dll...  (Remove it if crark fails.)"
	cp /opt/crark/rarcrypt-cl.dll ./
fi
/opt/crark/crark-hp $*
if [[ $DIR != "/opt/crark" ]]; then
	echo "Removing rarcrypt-cl.dll..."
	rm rarcrypt-cl.dll
fi
