#/bin/bash
#
# Checks only dependency lists and options
#
# Usage:
# ./compare-point-releases.sh 2.38.2-r1 2.38.2 2.38.3 2.38.3

PVA1="${1}"
PVA2="${2}"
PVB1="${3}"
PVB2="${4}"
main() {
	S_OLD="/var/tmp/portage/media-libs/opencv-${PVA1}/work/opencv-${PVA2}"
	S_NEW="/var/tmp/portage/media-libs/opencv-${PVB1}/work/opencv-${PVB2}"
	local P=(
CMakeLists.txt
apps/CMakeLists.txt
apps/annotation/CMakeLists.txt
apps/createsamples/CMakeLists.txt
apps/interactive-calibration/CMakeLists.txt
apps/model-diagnostics/CMakeLists.txt
apps/traincascade/CMakeLists.txt
apps/version/CMakeLists.txt
apps/visualisation/CMakeLists.txt
cmake/FindCUDA.cmake
cmake/FindCUDA/make2cmake.cmake
cmake/FindCUDA/parse_cubin.cmake
cmake/FindCUDA/run_nvcc.cmake
cmake/FindCUDNN.cmake
cmake/FindFlake8.cmake
cmake/FindONNX.cmake
cmake/FindOpenVX.cmake
cmake/FindPylint.cmake
cmake/FindVulkan.cmake
cmake/OpenCVCRTLinkage.cmake
cmake/OpenCVCompilerDefenses.cmake
cmake/OpenCVCompilerOptimizations.cmake
cmake/OpenCVCompilerOptions.cmake
cmake/OpenCVDetectApacheAnt.cmake
cmake/OpenCVDetectCUDA.cmake
cmake/OpenCVDetectCUDALanguage.cmake
cmake/OpenCVDetectCUDAUtils.cmake
cmake/OpenCVDetectCXXCompiler.cmake
cmake/OpenCVDetectDirectML.cmake
cmake/OpenCVDetectDirectX.cmake
cmake/OpenCVDetectFlatbuffers.cmake
cmake/OpenCVDetectHalide.cmake
cmake/OpenCVDetectInferenceEngine.cmake
cmake/OpenCVDetectOpenCL.cmake
cmake/OpenCVDetectPython.cmake
cmake/OpenCVDetectTBB.cmake
cmake/OpenCVDetectTrace.cmake
cmake/OpenCVDetectVTK.cmake
cmake/OpenCVDetectVulkan.cmake
cmake/OpenCVDetectWebNN.cmake
cmake/OpenCVDownload.cmake
cmake/OpenCVExtraTargets.cmake
cmake/OpenCVFindAVIF.cmake
cmake/OpenCVFindAtlas.cmake
cmake/OpenCVFindCANN.cmake
cmake/OpenCVFindFrameworks.cmake
cmake/OpenCVFindIPP.cmake
cmake/OpenCVFindIPPIW.cmake
cmake/OpenCVFindLAPACK.cmake
cmake/OpenCVFindLATEX.cmake
cmake/OpenCVFindLibsGUI.cmake
cmake/OpenCVFindLibsGrfmt.cmake
cmake/OpenCVFindLibsPerf.cmake
cmake/OpenCVFindLibsVideo.cmake
cmake/OpenCVFindMKL.cmake
cmake/OpenCVFindOpenBLAS.cmake
cmake/OpenCVFindOpenEXR.cmake
cmake/OpenCVFindProtobuf.cmake
cmake/OpenCVFindTIMVX.cmake
cmake/OpenCVFindVA.cmake
cmake/OpenCVFindWebP.cmake
cmake/OpenCVFindXimea.cmake
cmake/OpenCVGenABI.cmake
cmake/OpenCVGenAndroidMK.cmake
cmake/OpenCVGenConfig.cmake
cmake/OpenCVGenHeaders.cmake
cmake/OpenCVGenInfoPlist.cmake
cmake/OpenCVGenPkgconfig.cmake
cmake/OpenCVGenSetupVars.cmake
cmake/OpenCVInstallLayout.cmake
cmake/OpenCVMinDepVersions.cmake
cmake/OpenCVModule.cmake
cmake/OpenCVPCHSupport.cmake
cmake/OpenCVPackaging.cmake
cmake/OpenCVPluginStandalone.cmake
cmake/OpenCVPylint.cmake
cmake/OpenCVUtils.cmake
cmake/OpenCVVersion.cmake
cmake/android/OpenCVDetectAndroidSDK.cmake
cmake/android/android_ant_projects.cmake
cmake/android/android_gradle_projects.cmake
cmake/cl2cpp.cmake
cmake/copy_files.cmake
cmake/mirrors/custom.cmake
cmake/mirrors/gitcode.cmake
cmake/platforms/OpenCV-Android.cmake
cmake/platforms/OpenCV-Darwin.cmake
cmake/platforms/OpenCV-Emscripten.cmake
cmake/platforms/OpenCV-Linux.cmake
cmake/platforms/OpenCV-WinRT.cmake
cmake/platforms/OpenCV-Windows.cmake
cmake/platforms/OpenCV-WindowsCE.cmake
cmake/platforms/OpenCV-WindowsPhone.cmake
cmake/platforms/OpenCV-WindowsStore.cmake
cmake/platforms/OpenCV-iOS.cmake
cmake/vars/EnableModeVars.cmake
cmake/vars/OPENCV_DISABLE_THREAD_SUPPORT.cmake
cmake/vars/OPENCV_SEMIHOSTING.cmake
data/CMakeLists.txt
doc/CMakeLists.txt
include/CMakeLists.txt
modules/calib3d/CMakeLists.txt
modules/core/CMakeLists.txt
modules/core/cmake/parallel/detect_openmp.cmake
modules/core/cmake/parallel/detect_tbb.cmake
modules/core/cmake/parallel/init.cmake
modules/core/misc/plugins/parallel_openmp/CMakeLists.txt
modules/core/misc/plugins/parallel_tbb/CMakeLists.txt
modules/dnn/CMakeLists.txt
modules/dnn/cmake/hooks/INIT_MODULE_SOURCES_opencv_dnn.cmake
modules/dnn/cmake/init.cmake
modules/dnn/cmake/plugin.cmake
modules/dnn/misc/plugin/openvino/CMakeLists.txt
modules/features2d/CMakeLists.txt
modules/flann/CMakeLists.txt
modules/gapi/CMakeLists.txt
modules/gapi/cmake/DownloadADE.cmake
modules/gapi/cmake/init.cmake
modules/gapi/cmake/standalone.cmake
modules/highgui/CMakeLists.txt
modules/highgui/cmake/detect_gtk.cmake
modules/highgui/cmake/detect_wayland.cmake
modules/highgui/cmake/detect_win32ui.cmake
modules/highgui/cmake/init.cmake
modules/highgui/cmake/plugin.cmake
modules/highgui/misc/plugins/plugin_gtk/CMakeLists.txt
modules/imgcodecs/CMakeLists.txt
modules/imgproc/CMakeLists.txt
modules/java/CMakeLists.txt
modules/java/android_sdk/CMakeLists.txt
modules/java/android_sdk/libcxx_helper/CMakeLists.txt
modules/java/common.cmake
modules/java/generator/CMakeLists.txt
modules/java/jar/CMakeLists.txt
modules/java/jar/list_java_sources.cmake
modules/java/jni/CMakeLists.txt
modules/java/test/android_test/CMakeLists.txt
modules/java/test/pure_test/CMakeLists.txt
modules/js/CMakeLists.txt
modules/js/common.cmake
modules/js/generator/CMakeLists.txt
modules/ml/CMakeLists.txt
modules/objc/CMakeLists.txt
modules/objc/common.cmake
modules/objc/generator/CMakeLists.txt
modules/objdetect/CMakeLists.txt
modules/photo/CMakeLists.txt
modules/python/CMakeLists.txt
modules/python/bindings/CMakeLists.txt
modules/python/common.cmake
modules/python/python2/CMakeLists.txt
modules/python/python3/CMakeLists.txt
modules/python/python_loader.cmake
modules/python/standalone.cmake
modules/python/test/CMakeLists.txt
modules/stitching/CMakeLists.txt
modules/ts/CMakeLists.txt
modules/video/CMakeLists.txt
modules/videoio/CMakeLists.txt
modules/videoio/cmake/detect_android_camera.cmake
modules/videoio/cmake/detect_android_mediandk.cmake
modules/videoio/cmake/detect_aravis.cmake
modules/videoio/cmake/detect_avfoundation.cmake
modules/videoio/cmake/detect_dc1394.cmake
modules/videoio/cmake/detect_dshow.cmake
modules/videoio/cmake/detect_ffmpeg.cmake
modules/videoio/cmake/detect_gphoto.cmake
modules/videoio/cmake/detect_gstreamer.cmake
modules/videoio/cmake/detect_ios.cmake
modules/videoio/cmake/detect_msdk.cmake
modules/videoio/cmake/detect_msmf.cmake
modules/videoio/cmake/detect_obsensor.cmake
modules/videoio/cmake/detect_openni2.cmake
modules/videoio/cmake/detect_pvapi.cmake
modules/videoio/cmake/detect_realsense.cmake
modules/videoio/cmake/detect_ueye.cmake
modules/videoio/cmake/detect_v4l.cmake
modules/videoio/cmake/detect_ximea.cmake
modules/videoio/cmake/detect_xine.cmake
modules/videoio/cmake/init.cmake
modules/videoio/cmake/plugin.cmake
modules/videoio/misc/plugin_ffmpeg/CMakeLists.txt
modules/videoio/misc/plugin_gstreamer/CMakeLists.txt
modules/world/CMakeLists.txt
platforms/ios/cmake/Modules/Platform/iOS.cmake
platforms/ios/cmake/Toolchains/Toolchain-Catalyst_Xcode.cmake
platforms/ios/cmake/Toolchains/Toolchain-XROS_Xcode.cmake
platforms/ios/cmake/Toolchains/Toolchain-XRSimulator_Xcode.cmake
platforms/ios/cmake/Toolchains/Toolchain-iPhoneOS_Xcode.cmake
platforms/ios/cmake/Toolchains/Toolchain-iPhoneSimulator_Xcode.cmake
platforms/ios/cmake/Toolchains/common-ios-toolchain.cmake
platforms/linux/aarch64-gnu.toolchain.cmake
platforms/linux/arm-gnueabi.toolchain.cmake
platforms/linux/arm.toolchain.cmake
platforms/linux/gnu.toolchain.cmake
platforms/linux/mips.toolchain.cmake
platforms/linux/mips32r5el-gnu.toolchain.cmake
platforms/linux/mips64r6el-gnu.toolchain.cmake
platforms/linux/ppc64-gnu.toolchain.cmake
platforms/linux/ppc64le-gnu.toolchain.cmake
platforms/linux/ppcat.toolchain.cmake
platforms/linux/riscv-gnu.toolchain.cmake
platforms/linux/riscv64-071-gcc.toolchain.cmake
platforms/linux/riscv64-andes-gcc.toolchain.cmake
platforms/linux/riscv64-clang.toolchain.cmake
platforms/linux/riscv64-gcc.toolchain.cmake
platforms/semihosting/aarch64-semihosting.toolchain.cmake
platforms/wince/arm-wince-headless-overrides.cmake
platforms/wince/arm-wince.toolchain.cmake
platforms/winpack_dldt/2021.4.2/cmake/InferenceEngineConfig-version.cmake
platforms/winpack_dldt/2021.4.2/cmake/InferenceEngineConfig.cmake
platforms/winpack_dldt/cmake-opencv-checks/POST_FINALIZE.cmake
samples/CMakeLists.txt
samples/android/15-puzzle/CMakeLists.txt
samples/android/CMakeLists.txt
samples/android/camera-calibration/CMakeLists.txt
samples/android/color-blob-detection/CMakeLists.txt
samples/android/face-detection/CMakeLists.txt
samples/android/image-manipulations/CMakeLists.txt
samples/android/mobilenet-objdetect/CMakeLists.txt
samples/android/qr-detection/CMakeLists.txt
samples/android/tutorial-1-camerapreview/CMakeLists.txt
samples/android/tutorial-2-mixedprocessing/CMakeLists.txt
samples/android/tutorial-2-mixedprocessing/jni/CMakeLists.txt
samples/android/tutorial-3-cameracontrol/CMakeLists.txt
samples/android/tutorial-4-opencl/CMakeLists.txt
samples/android/tutorial-4-opencl/jni/CMakeLists.txt
samples/android/video-recorder/CMakeLists.txt
samples/cpp/CMakeLists.txt
samples/cpp/example_cmake/CMakeLists.txt
samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/CMakeLists.txt
samples/cpp/tutorial_code/core/parallel_backend/CMakeLists.txt
samples/cpp/tutorial_code/gpu/gpu-thrust-interop/CMakeLists.txt
samples/directx/CMakeLists.txt
samples/dnn/CMakeLists.txt
samples/gpu/CMakeLists.txt
samples/hal/c_hal/CMakeLists.txt
samples/hal/c_hal/config.cmake
samples/hal/slow_hal/CMakeLists.txt
samples/hal/slow_hal/config.cmake
samples/java/tutorial_code/CMakeLists.txt
samples/opencl/CMakeLists.txt
samples/opengl/CMakeLists.txt
samples/openvx/CMakeLists.txt
samples/python/CMakeLists.txt
samples/samples_utils.cmake
samples/semihosting/CMakeLists.txt
samples/semihosting/histogram/CMakeLists.txt
samples/semihosting/include/CMakeLists.txt
samples/semihosting/norm/CMakeLists.txt
samples/sycl/CMakeLists.txt
samples/tapi/CMakeLists.txt
samples/va_intel/CMakeLists.txt
	)
	for p in ${P[@]} ; do
		echo
		echo "Comparing ${p}:"
		C="${p}" D1="${S_OLD}" ; D2="${S_NEW}" ; diff  -urp "${D1}/${C}" "${D2}/${C}" # For individual comparisons
		echo
	done
}

main
