# Copyright 2022-2025 Orson Teodoro <orsonteodoro@hotmail.com>
# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# U 22.04

# Contains synthetic data generated by AI in the metadata.xml
# Contains AI generated code in patch.

MY_PN="Firejail"

CFLAGS_HARDENED_USE_CASES="security-critical sandbox sensitive-data untrusted-data"
CXX_STANDARD="ignore"
FIREJAIL_DEFAULT_WIDTH=${FIREJAIL_DEFAULT_WIDTH:-1920}
FIREJAIL_DEFAULT_HEIGHT=${FIREJAIL_DEFAULT_HEIGHT:-1080}
FIREJAIL_DEFAULT_BPP=${FIREJAIL_DEFAULT_BBP:-24}
FIREJAIL_MAX_ENVS=${FIREJAIL_MAX_ENVS:-512} # 2048 for testing only, the 512 is needed when building with firejail inside ebuild.
GEN_EBUILD=0 # Uncomment to regen ebuild parts
PYTHON_COMPAT=( "python3_"{9..12} )
TEST_SET="distro" # distro or full

declare -A APPARMOR_PROFILE
declare -A ARGS
declare -A AUTO_BLACKLIST
declare -A COMMAND
declare -A LANDLOCK
declare -A LANDLOCK_PROC
declare -A LANDLOCK_READ
declare -A LANDLOCK_WRITE
declare -A LANDLOCK_EXECUTE
declare -A LANDLOCK_SPECIAL
declare -A OOM
declare -A SECCOMP
declare -A SECCOMP_BLOCK
declare -A SECCOMP_KEEP
declare -A MALLOC_BACKEND
declare -A PATH_CORRECTION
declare -A SCOPE
declare -A SCUDO_FREE_IMMEDIATE
declare -A XEPHYR_WH
declare -A X_BACKEND

declare -A _SCOPE=(
	["gpg-agent"]="ban" # Breaks loading of xfce4
	["ssh-agent"]="ban" # Breaks loading of xfce4
	["sway"]="ban" # Breaks startup
	["X"]="ban"
	["Xephyr"]="ban" # Breaks --x11=xephyr
	["xpra"]="ban" # Causes Authorization required, but no authorization protocol specified
	["Xvfb"]="ban" # Breaks --x11=xvfb
	["x-terminal-emulator"]="ban"
)

HARDENED_ALLOCATORS_IUSE=(
	"hardened_malloc"
	"mimalloc"
	"scudo"
)

inherit libcxx-compat
LLVM_COMPAT=(
	"${LIBCXX_COMPAT_LTS[@]/llvm_slot_}"
)

declare -A _PATH_CORRECTION=(
	["spotify"]="/opt/spotify/spotify-client/spotify"
)

X_BLACKLIST=(
# False positives for X support.
	"gjs"

	# Generated from
	#for x in $(grep -r -e "^x11 none" /var/tmp/portage/sys-apps/firejail-0.9.80/work/firejail-0.9.80/etc/profile* | cut -f 1 -d ":") ; do echo -e "\t\""$(basename "${x}" | sed -e "s|.profile||g")"\""; done
	"deadlink"
	"axel"
	"gtk-update-icon-cache"
	"daisy"
	"clamav"
	"bpftop"
	"dexios"
	"editorconfiger"
	"cloneit"
	"erd"
	"clac"
	"highlight"
	"file"
	"hledger"
	"gconf"
	"dconf"
	"hasher-common"
	"chafa"
	"less"
	"gnome-keyring-daemon"
	"exiftool"
	"archiver-common"
	"checkbashisms"
	"hashcat"
	"gapplication"
	"gdu"
	"devilspie"
	"enchant"
	"img2txt"
	"qrencode"
	"unf"
	"mdr"
	"mp3splt"
	"uudeview"
	"mencoder"
	"odt2txt"
	"notify-send"
	"nvim"
	"ncdu"
	"statusof"
	"pkglog"
	"mediainfo"
	"reader"
	"strings"
	"qpdf"
	"tvnamer"
	"tesseract"
	"mimetype"
	"spectre-meltdown-checker"
	"man"
	"shellcheck"
	"pdftotext"
	"patch"
	"pandoc"
	"nano"
	"pngquant"
)

# Avoid broken resolution issue
X_FALLBACKS=(
	"leafpad:xpra"
	"x-terminal-emulator:xpra"
)

X_HEADLESS_COMPAT=(
# These are x11 sandboxed apps that could be headless and may use xvfb.
	"vmware"
)

# Use cases:
# Automation
# Background tasks
# GUI apps on a remote host without a monitor via SSH
X_HEADLESS_ONLY=(
)

# Use cases:
# Console only apps that have annoying Xpra noise.
X_NONE_ONLY=(
	"ollama"
)

X_XEPHYR_ONLY=(
)

X_XPRA_ONLY=(
	# Ban those that perform unexpected behavior like eager window close
	# with xephyr.
	"firefox"
	"firefox-beta"
	"firefox-developer-edition"
	"firefox-esr"
	"firefox-nightly"
	"firefox-wayland"
	"firefox-x11"
)

CURSES_COMPAT=(
# This list are apps that may run in the console but are organized like a GUI.
	"weechat"
	"weechat-curses"
)

X_APPS_MISSING_REQUIRED_USE=(
	"amarok"
	"amule"
	"bluefish"
	"brave"
	"brave-browser"
	"brasero"
	"calligraauthor"
	"calligraconverter"
	"calligraflow"
	"calligragemini"
	"calligraplan"
	"calligraplanwork"
	"calligrasheets"
	"calligrastage"
	"calligrawords"
	"chromium"
	"cinelerra"
	"clementine"
	"dillo"
	"ferdi"
	"firefox"
	"freecad"
	"geany"
	"geeqie"
	"gitter"
	"epiphany"
	"evince"
	"evince-previewer"
	"evince-thumbnailer"
	"godot3"
	"google-chrome"
	"eog"
	"google-earth"
	"google-earth-pro"
	"gramps"
	"hexchat"
	"hugin"
	"kodi"
	"leafpad"
	"mousepad"
	"mumble"
	"nautilus"
	"netsurf"
	"obs"
	"pcmanfm"
	"pidgin"
	"pinta"
	"pitivi"
	"qbittorrent"
	"rawtherapee"
	"ripperx"
	"ristretto"
	"qupzilla"
	"seamonkey-bin"
	"shotcut"
	"spotify"
	"surf"
	"synfigstudio"
	"teamspeak3"
	"telegram-desktop"
	"thunar"
	"thunderbird"
	"uzbl-browser"
	"vivaldi"
	"vmware-player"
	"vscodium"
	"x-terminal-emulator"
	"xchat"
	"xfburn"
	"xmms"
	"waterfox"
	"wireshark"
	"wireshark-gtk"
	"wireshark-qt"
	"xpdf"
# If it is uppercase, it is assumed is is a win port of that app.
)

CHROMIUM_APPS=(
	"spotify"
)

CHKL_TIMESTAMPS=(
	"sys-libs/libselinux-9999"
)

inherit cflags-hardened chkl flag-o-matic libcxx-slot linux-info python-single-r1 secure-version toolchain-funcs
inherit virtualx

gen_clang_bdepend() {
	local s
	for s in "${LLVM_COMPAT[@]}" ; do
		echo "
		llvm_slot_${s}? (
			llvm-core/clang:${s}
			llvm-core/lld:${s}
			llvm-core/llvm:${s}
			scudo? (
				llvm-runtimes/compiler-rt-sanitizers[scudo]
			)
		)
		"
	done
}

if [[ "${PV}" =~ "9999" ]]; then
	EGIT_BRANCH="master"
	EGIT_REPO_URI="https://github.com/netblue30/firejail.git"
	FALLBACK_COMMIT="8baad2bebfb96f1bd082c6bd270bb3907ef41833"
#	FALLBACK_COMMIT="1a576d15a9339b8f70ae3056e2413e58931072d5" # Jan 17, 2025 # working
#	FALLBACK_COMMIT="897f12dd88c1add667ecb211b61b6126a49c7065" # Sep 1, 2024 # working
	if [[ "${FALLBACK_COMMIT}" ]] ; then
		IUSE+=" fallback-commit"
	fi
	inherit git-r3
else
	KEYWORDS="amd64 ~arm ~arm64 ~x86"
	SRC_URI="
https://github.com/netblue30/${PN}/releases/download/${PV}/${P}.tar.xz
	"
fi

DESCRIPTION="Security sandbox for any type of processes"
HOMEPAGE="https://firejail.wordpress.com/"
LICENSE="GPL-2"
SLOT="0"
# Upstream enables landlock, but disabled in ebuild to prevent soft brick possibility.
# Defaults based on CI
IUSE+="
${FIREJAIL_PROFILES_IUSE[@]}
${HARDENED_ALLOCATORS_IUSE[@]}
${LLVM_COMPAT[@]/#/llvm_slot_}
-apparmor +chroot clang contrib +dbusproxy +file-transfer +globalcfg
landlock +network +private-home -private-lib -selinux +suid
test-profiles test-x11 +userns vanilla wrapper X xephyr xpra xcsecurity xvfb
ebuild_revision_145
"
REQUIRED_USE+="
	!test
	clang? (
		^^ (
			${LLVM_COMPAT[@]/#/llvm_slot_}
		)
	)
	contrib? (
		${PYTHON_REQUIRED_USE}
	)
	scudo? (
		clang
	)
	test-x11? (
		test
	)
	test-profiles? (
		test
	)
	xephyr? (
		X
	)
	xpra? (
		X
	)
	xcsecurity? (
		X
	)
	xvfb? (
		X
	)
"
RDEPEND+="
	!sys-apps/firejail-lts
	>=sys-libs/libseccomp-${LIBSECCOMP_PV}:=
	apparmor? (
		sys-libs/libapparmor:=
		|| (
			~sys-libs/libapparmor-${LIBAPPARMOR_5_0_PV}
			~sys-libs/libapparmor-${LIBAPPARMOR_4_1_PV}
		)
	)
	contrib? (
		${PYTHON_DEPS}
	)
	dbusproxy? (
		>=sys-apps/xdg-dbus-proxy-0.1.2:=
	)
	elibc_glibc? (
		>=sys-libs/glibc-${GLIBC_PV}:=
	)
	elibc_musl? (
		>=sys-libs/musl-${MUSL_PV}:=
	)
	hardened_malloc? (
		>=dev-libs/hardened_malloc-${HARDENED_MALLOC_PV}:=
	)
	mimalloc? (
		dev-libs/mimalloc:=
		|| (
			~dev-libs/mimalloc-${MIMALLOC3_PV}
			~dev-libs/mimalloc-${MIMALLOC2_PV}
			~dev-libs/mimalloc-${MIMALLOC1_PV}
		)
	)
	selinux? (
		>=sys-libs/libselinux-${LIBSELINUX_PV}:=
	)
	X? (
		>=x11-base/xorg-server-${XORG_SERVER_PV}:=[-suid,xcsecurity?,xvfb?]
	)
	xpra? (
		x11-wm/xpra:=[${PYTHON_SINGLE_USEDEP},X,avif,client,cython,firejail,gtk3,jpeg,rencodeplus,server,webp]
		|| (
			=x11-wm/xpra-6*[${PYTHON_SINGLE_USEDEP},X,avif,client,cython,firejail,gtk3,jpeg,rencodeplus,server,webp]
			=x11-wm/xpra-5*[${PYTHON_SINGLE_USEDEP},X,avif,client,cython,firejail,gtk3,jpeg,rencodeplus,server,webp]
		)
	)
	xephyr? (
		>=x11-base/xorg-server-${XORG_SERVER_PV}:=[xephyr?]
	)
"
DEPEND+="
	${RDEPEND}
"
BDEPEND+="
	$(gen_clang_bdepend)
	>=sys-devel/gcc-12
	test? (
		>=app-arch/xz-utils-${XZ_UTILS_PV}
		>=dev-tcltk/expect-5.45.4
	)
	test-x11? (
		>=x11-base/xorg-server-${XORG_SERVER_PV}[xvfb]
		x11-apps/xhost
	)
"

PATCHES=(
	"${FILESDIR}/${PN}-0.9.78-envlimits.patch"
	"${FILESDIR}/${PN}-0.9.80-firecfg.config.patch"
	"${FILESDIR}/${PN}-0.9.80-manpage-nocompress.patch"
#	"${FILESDIR}/extra-patches/${PN}-009110a-disable-xcsecurity.patch"
#	"${FILESDIR}/extra-patches/${PN}-009110a-disable-xcsecurity-usage.patch"
	"${FILESDIR}/extra-patches/${PN}-8baad2b-profile-fixes.patch"
	"${FILESDIR}/extra-patches/${PN}-3bbc6b5-private-bin-no-local-default-yes.patch" # Fix all wrappers and mpv
	"${FILESDIR}/extra-patches/${PN}-1b2d18e-default-res.patch"
	"${FILESDIR}/extra-patches/${PN}-0.9.80-inc-profile-changes.patch"
	"${FILESDIR}/extra-patches/${PN}-0.9.80-fix-private-lib-for-multilslot.patch"
	"${FILESDIR}/extra-patches/${PN}-0.9.80-chown-warning.patch"
)

TESTING_PATCHES=(
)

get_impls() {
	echo "release"
	use test && echo "test"
}

get_supported_commands() {
	local etc_folder="${S}/etc"
	local f
	local L1=(
		$(find "${etc_folder}/"{"profile-a-l","profile-m-z"} -name "*.profile")
	)
	local L2=()
	for f in "${L1[@]}" ; do
		local n=$(basename "${f}" \
			| sed -e "s|\.profile||g")
		L2+=(
			"${n}"
		)
	done
	echo "${L2[@]}" | tr " " $'\n' | sort | uniq
}

is_x_blacklisted() {
	local arg="${1}"
	local y
	for y in "${X_BLACKLIST[@]}" ; do
		if [[ "${arg}" == "${y}" ]] ; then
			return 0
		fi
	done
	return 1
}

is_x_headless_only() {
	local arg="${1}"
	local y
	for y in "${X_HEADLESS_ONLY[@]}" ; do
		if [[ "${arg}" == "${y}" ]] ; then
			return 0
		fi
	done
	return 1
}

is_x_none_only() {
	local arg="${1}"
	local y
	for y in "${X_NONE_ONLY[@]}" ; do
		if [[ "${arg}" == "${y}" ]] ; then
			return 0
		fi
	done
	return 1
}

is_x_headless_compat() {
	local arg="${1}"
	local y
	for y in "${X_HEADLESS_COMPAT[@]}" ; do
		if [[ "${arg}" == "${y}" ]] ; then
			return 0
		fi
	done
	return 1
}

is_xephyr_only() {
	local arg="${1}"
	local y
	for y in "${X_XEPHYR_ONLY[@]}" ; do
		if [[ "${arg}" == "${y}" ]] ; then
			return 0
		fi
	done
	return 1
}

is_xpra_only() {
	local arg="${1}"
	local y
	for y in "${X_XPRA_ONLY[@]}" ; do
		if [[ "${arg}" == "${y}" ]] ; then
			return 0
		fi
	done
	return 1
}

is_chromium_app() {
	local arg="${1}"
	local y
	for y in "${CHROMIUM_APPS[@]}" ; do
		if [[ "${arg}" == "${y}" ]] ; then
			return 0
		fi
	done
	return 1
}

check_kernel_config() {
	linux-info_pkg_setup

	CONFIG_CHECK="
		~PROC_FS
		~DEVTMPFS
		~TMPFS
		~UNIX
		~SYSFS
		~FILE_LOCKING
		~BINFMT_SCRIPT
	"
	WARNING_PROC_FS="CONFIG_PROC_FS is required by ${PN} for /proc support."
	WARNING_DEVTMPFS="CONFIG_DEVTMPFS is required by ${PN} for /dev support and chroot."
	WARNING_TMPFS="CONFIG_TMPFS is required by ${PN} for /run, testing /dev/shm, dbus support."
	WARNING_UNIX="CONFIG_UNIX is required by ${PN} for socket(AF_UNIX,...) support."
	WARNING_SYSFS="CONFIG_SYSFS may be required by ${PN} for ipvlan support."
	WARNING_DEVPTS_FS="CONFIG_DEVPTS_FS may be required by ${PN} for testing or private-dev sandboxing."
	WARNING_FILE_LOCKING="CONFIG_FILE_LOCKING is required by ${PN} for chroot and pid sandboxing."
	WARNING_BINFMT_SCRIPT="CONFIG_BINFMT_SCRIPT is required by ${PN} for contrib, tools, testing scripts."
	check_extra_config

	if use suid ; then
		CONFIG_CHECK="
			~USER_NS
			~NAMESPACES
			~SECCOMP
			~SECCOMP_FILTER
		"
		WARNING_USER_NS="CONFIG_USER_NS is required by ${PN} for USE=-suid support"
		WARNING_NAMESPACES="CONFIG_NAMESPACES is required by ${PN} for USE=-suid support"
		WARNING_SECCOMP="CONFIG_SECCOMP is required by ${PN} for USE=-suid support"
		WARNING_SECCOMP_FILTER="CONFIG_SECCOMP_FILTER is required by ${PN} for USE=-suid support"
		check_extra_config
	fi

	if has_version "virtual/jack" ; then
		CONFIG_CHECK="
			~MMU
			~SHMEM
		"
		WARNING_MMU="CONFIG_MMU is required by ${PN} for sound support for jack."
		WARNING_SHMEM="CONFIG_SHMEM is required by ${PN} for sound sound support for jack."
		check_extra_config
	fi

	if [[ -e "/etc/portage/env/firejail.conf" ]] ; then
		local owner=$(stat -c "%U:%G" "/etc/portage/env/firejail.conf")
		local perms=$(stat -c "%a" "/etc/portage/env/firejail.conf")
		if [[ "${owner}" != "root:root" ]] ; then
eerror "Check contents for tampering and change owner to root:root for /etc/portage/env/firejail.conf"
			die
		fi
		if [[ "${perms}" == "640" ]] ; then
			:
		elif [[ "${perms}" == "644" ]] ; then
			:
		else
eerror "Check contents for tampering and change file permissions to 644 or 640 for /etc/portage/env/firejail.conf"
			die
		fi
		source "/etc/portage/env/firejail.conf"
	fi
	python-single-r1_pkg_setup
	CONFIG_CHECK="
		~BLOCK
		~MISC_FILESYSTEMS
		~SQUASHFS
	"
	WARNING_BLOCK="CONFIG_BLOCK is required for firejail --appimage mode."
	WARNING_MISC_FILESYSTEMS="CONFIG_MISC_FILESYSTEMS is required for firejail --appimage mode."
	WARNING_SQUASHFS="CONFIG_SQUASHFS is required for firejail --appimage mode."
	check_extra_config

	CONFIG_CHECK="
		~NET
		~SECCOMP
		~SECCOMP_FILTER
	"
	WARNING_NET="CONFIG_NET is required for seccomp-bpf for sandboxing or limiting the capabilities of the attacker."
	WARNING_SECCOMP="CONFIG_SECCOMP is required for seccomp-bpf for sandboxing or limiting the capabilities of the attacker."
	WARNING_SECCOMP_FILTER="CONFIG_SECCOMP_FILTER is required for seccomp-bpf for sandboxing or limiting the capabilities of the attacker."
	check_extra_config

	local config_path=$(linux_config_path)
einfo "config_path:  ${config_path}"
	local lsm_list=$(grep -e "CONFIG_LSM" "${config_path}" \
		| cut -f 2 -d '"')

	if use selinux ; then
		CONFIG_CHECK="
			~AUDIT
			~NET
			~INET
			~SYSFS
			~MULTIUSER
			~SECURITY
			~SECURITY_NETWORK
			~SECURITY_SELINUX
		"
		if ! [[ "${lsm_list}" =~ "selinux" ]] ; then
ewarn
ewarn "Missing  selinux  in kernel .config CONFIG_LSM list."
ewarn "See also https://github.com/torvalds/linux/blob/v6.6/security/Kconfig#L234"
ewarn
		fi
		WARNING_AUDIT="CONFIG_AUDIT is required for SELinux LSM support."
		WARNING_NET="CONFIG_NET is required for SELinux LSM support."
		WARNING_INET="CONFIG_INET is required for SELinux LSM support."
		WARNING_SYSFS="CONFIG_SYSFS is required for SELinux LSM support."
		WARNING_MULTIUSER="CONFIG_MULTIUSER is required for SELinux LSM support."
		WARNING_SECURITY="CONFIG_SECURITY is required for SELinux LSM support."
		WARNING_SECURITY_NETWORK="CONFIG_SECURITY_NETWORK is required for SELinux LSM support."
		WARNING_SECURITY_SELINUX="CONFIG_SECURITY_SELINUX is required for SELinux LSM for access control."
		check_extra_config
	fi

	if use apparmor ; then
		CONFIG_CHECK="
			~SYSFS
			~MULTIUSER
			~SECURITY
			~NET
			~SECURITY_APPARMOR
		"
		if ! [[ "${lsm_list}" =~ "apparmor" ]] ; then
ewarn
ewarn "Missing  apparmor  in kernel .config CONFIG_LSM list."
ewarn "See also https://github.com/torvalds/linux/blob/v6.6/security/Kconfig#L234"
ewarn
		fi
		WARNING_SYSFS="CONFIG_SYSFS is required for AppArmor LSM support."
		WARNING_MULTIUSER="CONFIG_MULTIUSER is required for AppArmor LSM support."
		WARNING_SECURITY="CONFIG_NET is required for AppArmor LSM."
		WARNING_SECURITY="CONFIG_SECURITY is required for AppArmor LSM."
		WARNING_SECURITY_APPARMOR="CONFIG_SECURITY_LANDLOCK is required for AppArmor LSM for access control."
		check_extra_config
	fi

	if use landlock ; then
		CONFIG_CHECK="
			~SYSFS
			~MULTIUSER
			~SECURITY
			~SECURITY_LANDLOCK
		"
		if ! [[ "${lsm_list}" =~ "landlock" ]] ; then
ewarn
ewarn "Missing landlock in kernel .config CONFIG_LSM list."
ewarn "See also https://github.com/torvalds/linux/blob/v6.6/security/Kconfig#L234"
ewarn
		fi
		WARNING_SYSFS="CONFIG_SYSFS is required for Landlock LSM support."
		WARNING_MULTIUSER="CONFIG_MULTIUSER is required for Landlock LSM support."
		WARNING_SECURITY="CONFIG_SECURITY is required for Landlock LSM support."
		WARNING_SECURITY_LANDLOCK="CONFIG_SECURITY_LANDLOCK is required for Landlock LSM to impose filesystem restrictions to sandboxed processes and their children."
		check_extra_config
	fi

	if use scudo ; then
# See https://llvm.org/docs/ScudoHardenedAllocator.html#randomness
		CONFIG_CHECK="
			~RELOCATABLE
			~RANDOMIZE_BASE
		"
		if [[ "${ARCH}" == "amd64" ]] ; then
			CONFIG_CHECK+="
				~RANDOMIZE_MEMORY
			"
		fi
		WARNING_RELOCATABLE="CONFIG_RELOCATABLE is required by Scudo."
		WARNING_RANDOMIZE_BASE="CONFIG_RANDOMIZE_BASE (KASLR) is required by Scudo."
		WARNING_RANDOMIZE_MEMORY="CONFIG_RANDOMIZE_MEMORY is required by Scudo."
		check_extra_config
	fi

	if [[ -n "${AUTO_BLACKLIST[@]}" ]] ; then
eerror "The AUTO_BLACKLIST has been changed to SCOPE[@].  See metadata.xml or \`epkginfo -x sys-apps/firejail::oiledmachine-overlay\` for details."
		die
	fi
}

get_x11_compat() {
	local L=(
		$(grep -l -r -E -e "(tauri|electron|chromium|firefox.profile|firefox-common|torbrowser-launcher|opengl|@x11|gtk|gnome|kde|sdl|qt|opengl|vulkan)" "${S}/etc/profile"*)
		"${X_APPS_MISSING_REQUIRED_USE[@]}"
	)
	local L_sanitized=()

	cond_basename() {
		if [[ -e "${x}" ]] && grep -q -e "^x11 none" ; then
			:
		elif [[ "${x}" =~ "-common" ]] ; then
			:
		else
			local t=$(basename "${x}" \
				| sed -e "s|\.profile||g" \
				| sed -e "s|\.|_|g")
			if is_x_blacklisted "${t}" ; then
				:
			else
				echo "${t}"
			fi
		fi
	}

	local x
	for x in "${L[@]}" ; do
		L_sanitized+=( $(cond_basename "${x}") )
	done
	echo "${L_sanitized[@]}" | fold -s -w 80
}

pkg_setup() {
	check_kernel_config
	if use test && [[ "${TEST_SET}" == "full" ]] ; then
		if has userpriv ${FEATURES} ; then
eerror
eerror "You need to add FEATURES=\"\${FEATURES} -userpriv\" to complete testing"
eerror "in your per-package envvars"
eerror
			die
		fi
	fi

	if ! use scudo && ! use mimalloc && ! use hardened_malloc ; then
ewarn
ewarn "You are not using a hardened allocator for heap protection."
ewarn "USE=scudo, USE=mimalloc, USE=hardened_malloc can provide for a hardened"
ewarn "malloc."
ewarn
	fi
	if [[ "${ARCH}" == "arm64" ]] && ! use hardened_malloc ; then
einfo
einfo "You may use hardened_malloc for MTE support for arm64 to mitigate"
einfo "against buffer overflows and use-after-free."
einfo
	fi
	libcxx-slot_verify
}

_src_prepare_test_full() {
	#
	# The problem with the tests is that they assume BROOT always,
	# and not SYSROOT agnostic, which makes it difficult to test
	# (our customizations) before installing.  The tests reference
	# the already installed version which is what we do not want.
	# We prefer the test the one that will be installed.
	#
einfo "Redirecting paths to isolated image (from \${ROOT} to \${ED})"
	for f in $(grep -l -r -e "/etc/firejail" "${S}/test") ; do
einfo "Editing ${f}:  /etc/firejail -> ${ED}/etc/firejail"
		sed -i -e "s| /etc/firejail| ${ED}/etc/firejail|g" \
			-e "s|--netfilter=/etc/firejail|--netfilter=${ED}/etc/firejail|g" \
			-e "s|--output=/etc/firejail|--output=${ED}/etc/firejail|g" \
			-e "s|\"/etc/firejail/default.profile|\"${ED}/etc/firejail/default.profile|g" \
			"${f}" || die
	done
	for f in $(grep -l -r -e "/usr/bin/firejail" "${S}/test") ; do
einfo "Editing ${f}:  /usr/bin/firejail -> ${ED}/usr/bin/firejail"
		sed -i -e "s|/usr/bin/firejail|${ED}/usr/bin/firejail|g" \
			"${f}" || die
	done
	for f in $(grep -l -r -e "PATH:/usr/lib/firejail:/usr/lib64/firejail" "${S}/test") ; do
einfo "Editing ${f}:  \$PATH:/usr/lib/firejail:/usr/lib64/firejail -> \$PATH:${ED}/usr/lib/firejail:${ED}/usr/lib64/firejail"
		sed -i -e "s|PATH:/usr/lib/firejail:/usr/lib64/firejail|PATH:${ED}/usr/lib/firejail:${ED}/usr/lib64/firejail|g" \
			"${f}" || die
	done
	for f in $(grep -l -r -e "/usr/share/doc/firejail" "${S}/test") ; do
einfo "Editing ${f}:  /usr/share/doc/firejail -> ${ED}/usr/share/doc/firejail-${PVR}"
		sed -i -e "s|/usr/share/doc/firejail|${ED}/usr/share/doc/firejail-${PVR}|g" \
			"${f}" || die
	done
#	for f in $(grep -l -r -e "PREFIX=/usr" "${S}") ; do
#einfo "Editing ${f}:  PREFIX=/usr -> PREFIX=${ED}/usr"
#		sed -i -e "s|PREFIX=/usr|PREFIX=${ED}/usr|g" \
#			"${f}" || die
#	done
}

src_unpack() {
	if [[ "${PV}" =~ "9999" ]] ; then
		if in_iuse fallback-commit && use fallback-commit ; then
			EGIT_COMMIT="${FALLBACK_COMMIT}"
		fi
		git-r3_fetch
		git-r3_checkout
	else
		unpack ${A}
	fi
}

src_prepare() {
	default

	cp -aT "${FILESDIR}/extra-profiles/" "${S}/etc" || die

	if use xpra ; then
		eapply "${FILESDIR}/extra-patches/${PN}-0.9.80-xpra-opengl.patch"
		eapply "${FILESDIR}/extra-patches/${PN}-0.9.80-disable-xpra-splash-v2.patch"
	fi

	if use xpra ; then
	# eog fix
		sed -i -e "s|@IPC_NAMESPACE_FIX@|#|g" "etc/profile-a-l/eo-common.profile" || die
	fi

	# Our toolchain already sets SSP by default but forcing it causes problems
	# on arches which don't support it. As for F_S, we again set it by defualt
	# in our toolchain, but forcing F_S=2 is actually a downgrade if 3 is set.
	sed -i \
		-e 's:-fstack-protector-all::' \
		-e 's:-D_FORTIFY_SOURCE=2::' \
		"src/so.mk" \
		"src/prog.mk" \
		|| die

	local ldflags=""
	local cflags=""

einfo "Adding shuffle-sections ROP mitigation flags"
	cflags="-ffunction-sections"
	if tc-ld-is-lld ; then
		ldflags="-Wl,--shuffle-sections=0"
	elif tc-ld-is-mold ; then
		ldflags="-Wl,--shuffle-sections"
	else
ewarn "Use LLD or mold for ROP mitigation"
	fi

	[[ -n "${cflags}" ]] && append-flags ${cflags}
	[[ -n "${ldflags}" ]] && append-flags ${ldflags}

	cflags-hardened_append
	cflags="${cflags} ${CFLAGS_HARDENED_CFLAGS}"
	ldflags="${ldflags} ${CFLAGS_HARDENED_LDFLAGS}"

	sed -i \
		-e "s:-ggdb::g" \
		-e "s:-Wall:${cflags} -Wall:g" \
		-e "s:-Wl,-z,relro:-Wl,-z,relro ${ldflags}:g" \
		"config.mk.in" \
		|| die

	find \
		-type f \
		\( \
			   -name "*.mk" \
			-o -name "configure" \
		\) \
		-exec \
			sed -i -r \
				-e "s/(-O2|-ggdb)//g" {} + \
				|| die

einfo "CWD:  "$(pwd)
	# Fix up hardcoded paths to templates and docs
	local files=$(grep \
		-E \
		-l \
		-r \
		'/usr/share/doc/firejail([^-]|$)' \
		"RELNOTES" \
		"src/man/" \
		"etc/profile"*"/" \
		"test/" \
		|| die)
	local file
	for file in ${files[@]} ; do
einfo "Processing:  ${file}"
		sed -i -r \
			-e "s:/usr/share/doc/firejail([^-]|\$):/usr/share/doc/${PF}\1:" \
			"${file}" \
			|| die
	done

	# Remove compression of man pages
	sed -i -r -e \
'/rm -f \$\$man.gz; \\/d; '\
'/gzip -9n \$\$man; \\/d; '\
's|\*\.([[:digit:]])\) install -m 0644 \$\$man\.gz|\*\.\1\) install -m 0644 \$\$man|g' \
		Makefile || die

	if use contrib; then
		python_fix_shebang -f "contrib/"*".py"
	fi

	if use test ; then
		if [[ "${TEST_SET}" == "full" ]] ; then
			_src_prepare_test_full
		fi
	fi

	if use private-lib ; then
		sed -i -e "s|# private-lib no|private-lib yes|" \
			"etc/firejail.config" \
			|| die
	fi

	# Common symbol replacements
	local L=(
		$(find "etc" -type f)
	)
	local x
	for x in "${L[@]}" ; do
		sed -i -e "s|@LIBDIR@|$(get_libdir)|" \
			"${x}" \
			|| die
	done

	local impl
	for impl in $(get_impls) ; do
		cp -a "${S}" "${S}_${impl}" || die
	done
}

_src_configure_default_res() {
	use test || return
	sed -i \
		-e "s|@WIDTH@|${FIREJAIL_DEFAULT_WIDTH}|g" \
		-e "s|@HEIGHT@|${FIREJAIL_DEFAULT_HEIGHT}|g" \
		-e "s|@BBP@|${FIREJAIL_DEFAULT_BBP}|g" \
		"etc/firejail.config" \
		"src/firejail/checkcfg.c" \
		"src/firejail/usage.c" \
		"src/man/firejail.1.in" \
		|| die
}

_src_configure_max_envs() {
	sed -i \
		-e "s|@ENV_MAX_COUNT@|${FIREJAIL_MAX_ENVS}|g" \
		"etc/firejail.config" \
		"src/firejail/checkcfg.c" \
		|| die
einfo "FIREJAIL_MAX_ENVS:  ${FIREJAIL_MAX_ENVS}"
einfo "Current envvar count: "$(env | wc -l)
}

_src_configure_test_full() {
	# firejail deprecated --profile-dir= so must be hardwired this way
	sed -i \
		-e "s|\$(sysconfdir)|${ED}/etc|g" \
		"src/common.mk.in" \
		|| die
#	test_opts+=(--prefix="${ED}/usr")
einfo "Editing ${BUILD_DIR}/test/filters/memwrexe.exp:  ./memwrexe -> ${BUILD_DIR}/test/filters/memwrexe"
	sed -i \
		-e "s|\./memwrexe|${BUILD_DIR}/test/filters/memwrexe|g" \
		"${BUILD_DIR}/test/filters/memwrexe.exp" \
		|| die
#	:
}

_src_configure() {
	local test_opts=()
	if [[ "${impl}" == "test" && "${TEST_SET}" == "full" ]] ; then
		_src_configure_test_full
	else
		test_opts=()
	fi

	_src_configure_max_envs
	_src_configure_default_res

	local myconf=(
		$(use_enable apparmor)
		$(use_enable chroot)
		$(use_enable dbusproxy)
		$(use_enable file-transfer)
		$(use_enable globalcfg)
		$(use_enable landlock)
		$(use_enable network)
		$(use_enable private-home)
		$(use_enable private-lib)
		$(use_enable selinux)
		$(use_enable suid)
		$(use_enable userns)
		$(use_enable X x11)
		"${test_opts[@]}"
	)

	econf "${myconf[@]}"
}

src_configure()
{
	chkl_check_many_timestamps

	# Make _FORTIFY_SOURCE=2 work
	replace-flags "-O0" "-O1"

	local impl
	for impl in $(get_impls) ; do
		export BUILD_DIR="${S}_${impl}"
		cd "${BUILD_DIR}" || die
		_src_configure
	done
}

_src_compile() {
	emake CC="$(tc-getCC)"
	if [[ "${impl}" == "test" ]] ; then
		DESTDIR="${D}" emake install
	fi
}

src_compile()
{
	local impl
	for impl in $(get_impls) ; do
		export BUILD_DIR="${S}_${impl}"
		cd "${BUILD_DIR}" || die
		_src_compile
	done
}

WHITELIST_READONLY=(
	BROOT
	D
	DEFINED_PHASES
	EAPI
	EBUILD
	EBUILD_PHASE
	EBUILD_PHASE_FUNC
	ED
	EMERGE_FROM
	EPREFIX
	EROOT
	FILESDIR
	INHERITED
	KEYWORDS
	LICENSE
	MERGE_TYPE
	PM_EBUILD_HOOK_DIR
	PORTAGE_ACTUAL_DISTDIR
	PORTAGE_ARCHLIST
	PORTAGE_BASHRC
	PORTAGE_BIN_PATH
	PORTAGE_BUILDDIR
	PORTAGE_BUILD_GROUP
	PORTAGE_BUILD_USER
	PORTAGE_BZIP2_COMMAND
	PORTAGE_COLORMAP
	PORTAGE_CONFIGROOT
	PORTAGE_DEPCACHEDIR
	PORTAGE_GID
	PORTAGE_INST_GID
	PORTAGE_INST_UID
	PORTAGE_INTERNAL_CALLER
	PORTAGE_IPC_DAEMON
	PORTAGE_LOG_FILE
	PORTAGE_OVERRIDE_EPREFIX
	PORTAGE_PROPERTIES
	PORTAGE_PYM_PATH
	PORTAGE_PYTHON
	PORTAGE_PYTHONPATH
	PORTAGE_REPO_NAME
	PORTAGE_REPOSITORIES
	PORTAGE_RESTRICT
	PORTAGE_SIGPIPE_STATUS
	PORTAGE_TMPDIR
	PORTAGE_VERBOSE
	PORTAGE_WORKDIR_MODE
	PORTAGE_XATTR_EXCLUDE
	SLOT
	T
	USE
	WORKDIR
)

save_env()
{
	env -0 > "${T}/env.txt"
}

restore_env()
{
	while IFS= read -r -d $'\0' l
	do
		local allow=1
		k=$(echo "${l}" \
			| cut -f 1 -d "=" \
			| cut -f 1 -d "=")
		[[ "${k}" =~ "PORTAGE_REPOSITORIES" ]] && k="PORTAGE_REPOSITORIES"
		[[ "${k}" =~ "PORTAGE_COLORMAP" ]] && k="PORTAGE_COLORMAP"
		local w
		for w in "${WHITELIST_READONLY[@]}" ; do
			[[ "${k}" == "${w}" ]] && allow=0
		done
		local v=$(echo "${l}" | cut -f 2- -d "=")
		(( ${allow} == 1 )) && export ${k}="${v}"
	done < "${T}/env.txt"
	export IFS=$' \t\n'
}

wipe_env()
{
	local whitelist=(
		CFLAGS
		CHOST
		CXXFLAGS
		DIE_ON_CAPS_ERROR
		DIE_ON_GRSECURITY_ERROR
		DIE_ON_PROGRAM_LOAD_FAILURE
		DIE_ON_SECCOMP_ERROR
		DISPLAY
		IFS
		HOME
		LDFLAGS
		LD_LIBRARY_PATH
		PATH
		PWD
		S
		SANDBOX_ON
		SHELL
		TERM
		USE_CAPS
		USE_GRSECURITY
		USE_SECCOMP
		USER
	)

	env -0 > "${T}/env-dump.txt"

	local envs=()
	while IFS= read -r -d $'\0' l
	do
		n=$(echo "${l}" | cut -f 1 -d "=")
		[[ "${n}" =~ "PORTAGE_REPOSITORIES" ]] && n="PORTAGE_REPOSITORIES"
		[[ "${n}" =~ "PORTAGE_COLORMAP" ]] && n="PORTAGE_COLORMAP"
		local allow=1
		local w
		for w in "${whitelist[@]}" "${WHITELIST_READONLY[@]}" ; do
			[[ "${n}" == "${w}" ]] && allow=0
		done
		(( ${allow} == 1 )) && envs+=( "${n}" )
	done < "${T}/env-dump.txt"
	export IFS=$' \t\n'

	local n
	for n in "${envs[@]}" ; do
		unset ${n}
	done
}

_src_test_full()
{
	# Setting these to test against the to be installed version not the one to be replaced.
	export PATH="${ED}/usr/bin:${PATH}"
	export LD_LIBRARY_PATH="${ED}/usr/$(get_libdir)/firejail:${LD_LIBRARY_PATH}"
einfo "PATH=\"${PATH}\""
einfo "LD_LIBRARY_PATH=\"${LD_LIBRARY_PATH}\""

	export SANDBOX_ON=0

	if [[ -f "/proc/sys/kernel/grsecurity" ]] ; then
		export USE_GRSECURITY=1
		export DIE_ON_GRSECURITY_ERROR=0
	else
		export USE_GRSECURITY=0
	fi
	if grep -q -e "^Seccomp" "/proc/self/status" ; then
		export USE_SECCOMP=1
		export DIE_ON_SECCOMP_ERROR=0
	else
		export USE_SECCOMP=0
	fi
	if [[ -f "/sys/kernel/security/apparmor/profiles" ]] ; then
		:
	fi
	export USE_CAPS=1
	export DIE_ON_CAPS_ERROR=0
	export DIE_ON_PROGRAM_LOAD_FAILURE=1

	# Upstream uses `make test-github` for CI
	local x11_tests=()
	local profile_tests=()
	local misc_tests=()
	use test-profiles && profile_tests+=(test-profiles)
	misc_tests=()
	# Mixes test-github and test-noprofiles with exclusions.
	local basic_tests=(
		test-private-lib
		test-fnetfilter
		test-fs
		test-utils
		test-sysutils
		test-environment
	)

	mkdir -p "${ED}/etc/firejail" || die
	touch "${ED}/etc/firejail/globals.local" || die

	# Sandboxed $HOME for HOME tests
#	echo \
#		"whitelist $(realpath ~/)" \
#		>> \
#		"${ED}/etc/firejail/globals.local" \
#		|| die
#	echo \
#		"whitelist $(realpath ~/)/_firejail_test_file1" \
#		>> \
#		"${ED}/etc/firejail/globals.local" \
#		|| die

	# Add globals for ricers
	echo \
		"private-lib gcc/*/*/libgomp.so.*" \
		>> \
		"${ED}/etc/firejail/globals.local" \
		|| die

	# Temporary enable list
	echo \
		"include file.profile #REMOVE_ME: temporary test addition" \
		>> \
		"${ED}/etc/firejail/server.profile" \
		|| die

	# It's safe to ignore these kinds of fldd warnings:
	#Warning fldd: cannot find libstdc++.so.6, skipping...
	#Warning fldd: cannot find libgcc_s.so.1, skipping...
	# pavcontrol still works with these warnings.

	touch "${T}/test-all.log" || die

	save_env

if true ; then
	for x in "${profile_tests[@]}" "${basic_tests[@]}" "${misc_tests[@]}" ; do
einfo "Testing ${x}"
		wipe_env
		make ${x} 2>&1 >"${T}/test.log"
		local retcode=$?
		restore_env
		if (( ${retcode} == 0 )) ; then
einfo "${x} passed"
		else
eerror
eerror "Test failed for ${x}.  Return code: ${retcode}.  For details see"
eerror "${T}/test.log"
eerror
			die
		fi
		if grep -q -E -e "Error [0-9]+" "${T}/test.log" ; then
eerror "Test failed for ${x}.  For details see ${T}/test.log"
			die
		fi
		cat "${T}/test.log" >> "${T}/test-all.log" || die
	done
fi

	if use test-x11 ; then
		# For memwrexe.exp tests
#		echo \
#			"keep-var-tmp" \
#			>> \
#			"${ED}/etc/firejail/globals.local" \
#			|| die
#		echo \
#			"whitelist ${WORKDIR}/${PN}-${PV}*/test/filters/memwrexe*" \
#			>> \
#			"${ED}/etc/firejail/globals.local" \
#			|| die

		x11_tests+=(
			test-apps
			test-apps-x11
			test-apps-x11-xorg
			test-filters
		)
		for x in "${x11_tests[@]}" ; do
			cd "${BUILD_DIR}" || die
einfo "Testing ${x}"
cat <<EOF > "${BUILD_DIR}/run.sh"
#!/bin/bash
cat /dev/null > "${T}/test-retcode.log"
make ${x} 2>&1 >"${T}/test.log"
echo -n "\$?" > "${T}/test-retcode.log"
exit \$(cat "${T}/test-retcode.log")
EOF
			chmod +x "${BUILD_DIR}/run.sh"
			wipe_env
			virtx "${BUILD_DIR}/run.sh"
			restore_env
			if grep -q -E -e "Error [0-9]+" "${T}/test.log" ; then
eerror "Test failed for ${x}.  For details see ${T}/test.log"
				die
			fi
			if [[ ! -f "${T}/test-retcode.log" ]] ; then
eerror "Missing retcode for ${x}"
				die
			fi
			local test_retcode=$(cat "${T}/test-retcode.log")
			if [[ "${test_retcode}" != "0" ]] ; then
eerror
eerror "Test failed for ${x}.  Return code: ${test_retcode}.  For details see"
eerror "${T}/test.log"
eerror
				die
			fi
			cat \
				"${T}/test.log" \
				>> \
				"${T}/test-all.log" \
				|| die
		done

#		sed -i \
#			-e "\|#REMOVE_ME|d" \
#			"${ED}/etc/firejail/globals.local" \
#			|| die

	fi
	export SANDBOX_ON=1

einfo "FIXME:  Error results:"
	grep -o -E -r \
		-e "TESTING ERROR [0-9.]+" "${T}/test-all.log" \
		-e "TESTING ERROR - grsecurity detection" \
		| sort \
		| uniq -c

	rm \
		"${ED}/etc/firejail/globals.local" \
		|| die

	sed -i \
		-e "\|#REMOVE_ME|d" \
		"${ED}/etc/firejail/server.profile" \
		|| die
}

_src_test_distro() {
	emake test-utils test-sysutils
}

src_test() {
	local impl
	for impl in $(get_impls) ; do
		export BUILD_DIR="${S}_${impl}"
		cd "${BUILD_DIR}" || die
		if [[ "${TEST_SET}" == "full" ]] ; then
			_src_test_full
		else
			_src_test_distro
		fi
	done
}

# See also https://github.com/llvm/llvm-project/blob/llvmorg-18.1.8/compiler-rt/cmake/Modules/AllSupportedArchDefs.cmake
get_llvm_arch() {
	if [[ "${ARCH}" == "amd64" ]] ; then
		echo "x86_64"
	elif [[ "${ARCH}" == "x86" ]] ; then
		echo "i386"
	elif [[ "${ARCH}" == "arm64" ]] ; then
		echo "aarch64"
	elif [[ "${ARCH}" == "arm" ]] ; then
		echo "arm"
	elif [[ "${ARCH}" == "loong" ]] ; then
		echo "loongarch64"
	elif [[ "${CHOST}" =~ "mips64" ]] ; then
		echo "mips64"
	elif [[ "${CHOST}" =~ "mips" ]] ; then
		echo "mips"
	elif [[ "${ARCH}" == "ppc64" ]] ; then
		echo "ppc"
	elif [[ "${CHOST}" =~ "riscv64" ]] ; then
		echo "riscv64"
	elif [[ "${CHOST}" =~ "riscv32" ]] ; then
		echo "riscv32"
	elif [[ "${CHOST}" == "sparc" ]] ; then
		echo "sparc"
	elif [[ "${CHOST}" == "s390x" ]] ; then
		echo "s390x"
	fi
}

_gen_one_wrapper() {
	local command="${1}"
	local wrapper_name="${2}"
	local exe_path="${3}"
einfo "Generating wrapper for ${wrapper_name}"

	local key_command="${1//./_}" # Sanitized associative array key
	if [[ "${1:0:1}" =~ ^[0-9] ]] ; then
# You cannot use a number as the prefix to associative array.
		key_command="_${1//./_}"
	fi

	local x11_arg=""
	local x

	is_x11_compat() {
		local arg="${1}"
		local x
		for x in "${X11_COMPAT[@]}" ; do
			if [[ "${arg}" == "${x}" ]] ; then
				return 0
			fi
		done
		return 1
	}

	if \
		[[ \
			"${X_BACKEND[${key_command}]}" == "auto" \
		]] \
	; then
eerror
eerror "X_BACKEND[PROFILE]=auto has been removed."
eerror "Use X_BACKEND[PROFILE]=xorg|xpra|xephyr to continue."
eerror
	fi

	if \
		[[ \
			   "${X_BACKEND[${key_command}]}" == "game" \
			|| "${X_BACKEND[${key_command}]}" == "gaming" \
			|| "${X_BACKEND[${key_command}]}" == "opengl" \
		]] \
	; then
eerror
eerror "X_BACKEND[PROFILE]=game|gaming|opengl has been renamed to"
eerror "X_BACKEND[PROFILE]=gaming-sandboxed|opengl-sandboxed"
eerror
eerror "Convert to the new values to continue."
eerror
		die
	fi

	local preferred_fallback=""
	local x
	for x in "${X_FALLBACKS[@]}" ; do
		local fallback_profile=${x%:*}
		local x_backend=${x#*:}
		if [[ "${key_command}" =~ "${fallback_profile}" ]] ; then
			preferred_fallback="${x_backend}"
			break
		fi
	done

	is_xephyr_only() {
		local arg="${1}"
		local y
		for y in "${X_XEPHYR_ONLY[@]}" ; do
			if [[ "${arg}" == "${y}" ]] ; then
				return 0
			fi
		done
		return 1
	}

	is_xpra_only() {
		local arg="${1}"
		local y
		for y in "${X_XPRA_ONLY[@]}" ; do
			if [[ "${arg}" == "${y}" ]] ; then
				return 0
			fi
		done
		return 1
	}

	local x11_sandbox=""
	if ! use X ; then
		:
	elif [[ "${X_BACKEND[${key_command}]}" =~ ("disable"|"none"|"unsandboxed"|"gaming-unsandboxed"|"opengl-unsandboxed") ]] ; then
		:
	elif is_xpra_only "${key_command}" ; then
einfo "Forcing xpra for ${key_command}"
		x11_arg="--x11=xpra"
	elif is_xephyr_only "${key_command}" ; then
einfo "Forcing xephyr for ${key_command}"
		x11_arg="--x11=xephyr"
		x11_sandbox="xephyr"
	elif [[ "${X_BACKEND[${key_command}]}" =~ ("gaming-sandboxed"|"opengl-sandboxed") ]] ; then
		x11_arg="--x11=xpra"
	elif [[ "${X_BACKEND[${key_command}]}" =~ "xpra" ]] ; then
		x11_arg="--x11=xpra"
	elif [[ "${X_BACKEND[${key_command}]}" == "xephyr" ]] ; then
		x11_arg="--x11=xephyr"
		x11_sandbox="xephyr"
	elif [[ "${X_BACKEND[${key_command}]}" =~ "xorg" ]] ; then
		x11_arg="--x11=xorg"
		x11_sandbox="xorg"
	elif [[ "${X_BACKEND[${key_command}]}" =~ ("/dev/null"|"headless"|"xvfb") ]] ; then
		x11_arg="--x11=xvfb"
	elif [[ "${X_BACKEND[${key_command}]}" == "auto" ]] ; then
		x11_arg="--x11"
	elif is_x11_compat "${key_command}" && [[ "${preferred_fallback}" == "xpra" ]] && use xpra ; then
		x11_arg="--x11=xpra"
	elif is_x11_compat "${key_command}" && [[ "${preferred_fallback}" == "xephyr" ]] && use xephyr ; then
		x11_arg="--x11=xephyr"
		x11_sandbox="xephyr"
	elif is_x11_compat "${key_command}" && [[ "${preferred_fallback}" == "xvfb" ]] && use xvfb ; then
		x11_arg="--x11=xvfb"
	elif is_x11_compat "${key_command}" && [[ "${preferred_fallback}" == "xorg" ]] && use xcsecurity ; then
		x11_arg="--x11=xorg"
		x11_sandbox="xorg"
	elif is_x11_compat "${key_command}" && use xpra ; then
		x11_arg="--x11=xpra"
	elif is_x11_compat "${key_command}" && use xephyr ; then
		x11_arg="--x11=xephyr"
		x11_sandbox="xephyr"
	elif is_x11_compat "${key_command}" && use xcsecurity ; then
		x11_arg="--x11=xorg"
		x11_sandbox="xorg"
	else
ewarn "Uncaught x11_arg case for ${command}.  Ignore the warning if it is a console app."
	fi

	if is_x_headless_only "${command}" ; then
		x11_arg="--x11=xvfb"
		x11_sandbox="headless"
	fi

	if is_x_none_only "${command}" ; then
		x11_arg="--x11=none"
		x11_sandbox="none"
	fi

	if [[ "${x11_sandbox}" == "xephyr" ]] ; then
		if [[ -z "${XEPHYR_WH[${key_command}]}" ]] ; then
ewarn
ewarn "XEPHYR_WH[${key_command}] is unset.  The default 1920x1080 will be used."
ewarn "Consider setting it to either 1280x720, 1920x1080, 2560x1440, 3840x2160 instead."
ewarn "See metadata.xml or \`epkginfo -x sys-apps/firejail::oiledmachine-overlay\` for details."
ewarn
		fi
	fi

	local profile_path=""
	if [[ "${COMMAND[${key_command}]}" == "1" ]] ; then
		:
	else
		profile_path=$(find "${T}/profiles" "${T}/profiles_processed" "${S}/etc/profile"* -name "${command}.profile")
	fi

	if [[ "${COMMAND[${key_command}]}" == "1" ]] ; then
		:
	elif [[ -n "${x11_arg}" ]] && grep -q -e "x11 none" "${profile_path}" ; then
	# False positive
		x11_arg="--x11=none"
	fi

	local allocator_args=""
	local allocator_args_scudo=""
	local allocator_args_mimalloc=""
	local allocator_args_hardened_malloc=""
	local s
	for s in "${LLVM_COMPAT[@]}" ; do
		if use "llvm_slot_${s}" && has_version "llvm-runtimes/compiler-rt-sanitizers:${s}[scudo]" ; then
			if [[ "${SCUDO_FREE_IMMEDIATE[${key_command}]}" != "1" ]] ; then
				allocator_args_scudo+=" --env=SCUDO_OPTIONS='quarantine_size_kb=256:quarantine_max_chunk_size=2048:thread_local_quarantine_size_kb=64' "
			fi
			allocator_args_scudo+=" --env=LD_PRELOAD=/usr/lib/clang/${s}/lib/linux/libclang_rt.scudo_standalone-$(get_llvm_arch).so"
			break
		fi
	done
	if use mimalloc ; then
		allocator_args_mimalloc="--env=LD_PRELOAD=/usr/$(get_libdir)/libmimalloc-secure.so"
	fi
	if use hardened_malloc ; then
		allocator_args_hardened_malloc="--env=LD_PRELOAD=/usr/$(get_libdir)/libhardened_malloc.so"
	fi

	local PROFILE_NEEDS_SYSTEM_ALLOCATOR=(
	# Ban if it it is statically linked.
		"firefox"
		"firefox-bin"
		"google-chrome"
		"google-chrome-beta"
		"google-chrome-stable"
		"google-chrome-unstable"
		"spotify"

	# Still broken with browser plugin disabled
		"obs"
	)

	local force_system_allocator=0

	if grep -q -e "electron-common" "${T}/profiles_data/${command}.profile" 2>/dev/null ; then
einfo "Forcing system allocator for ${command} (1)"
		force_system_allocator=1
	elif [[ "${command}" == "electron-common" ]] ; then
einfo "Forcing system allocator for ${command} (2)"
		force_system_allocator=1
	elif [[ "${command}" == "firefox-bin" ]] ; then
einfo "Forcing system allocator for ${command} (3)"
		force_system_allocator=1
	fi

	local x
	for x in "${PROFILE_NEEDS_SYSTEM_ALLOCATOR[@]}" ; do
		if [[ "${key_command}" == "firefox" ]] && has_version "www-client/firefox" && ! has_version "www-client/firefox[jemalloc]" ; then
			:
		elif [[ "${key_command}" == "chromium" ]] && has_version "www-client/chromium" && ! has_version "www-client/chromium[partitionalloc]" ; then
			:
		elif [[ "${key_command}" == "${x}" ]] ; then
			force_system_allocator=1
			break
		fi
	done

	# Sort by data remittance policy (most scrambled on top, least scrambled bottom)
	if (( ${force_system_allocator} == 1 )) ; then
		:
	elif [[ "${MALLOC_BACKEND[${key_command}]}" == "mimalloc" ]] && use mimalloc ; then
		allocator_args="${allocator_args_mimalloc}"
	elif [[ "${MALLOC_BACKEND[${key_command}]}" == "scudo" ]] && use scudo ; then
		allocator_args="${allocator_args_scudo}"
	elif [[ "${MALLOC_BACKEND[${key_command}]}" == "hardened_malloc" ]] && use hardened_malloc ; then
		allocator_args="${allocator_args_hardened_malloc}"
	elif [[ "${MALLOC_BACKEND[${key_command}]}" == "system-malloc" ]] ; then
		:
	elif use mimalloc ; then
		allocator_args="${allocator_args_mimalloc}"
	elif use scudo ; then
		allocator_args="${allocator_args_scudo}"
	elif use hardened_malloc ; then
		allocator_args="${allocator_args_hardened_malloc}"
	fi

	local landlock_arg=""
	if use landlock ; then
		if [[ -n "${LANDLOCK[${key_command}]}" ]] ; then
			landlock_arg="--landlock"
		fi
		if [[ -n "${LANDLOCK_READ[${key_command}]}" ]] ; then
			local L=(
				echo
			)
			local p
			while IFS=, read p ; do
				landlock_arg+=" --landlock.read=${p}"
			done <<< ${LANDLOCK_READ[${key_command}]}
		fi
		if [[ -n "${LANDLOCK_WRITE[${key_command}]}" ]] ; then
			local p
			while IFS=, read p ; do
				landlock_arg+=" --landlock.write=${p}"
			done <<< ${LANDLOCK_WRITE[${key_command}]}
		fi
		if [[ -n "${LANDLOCK_SPECIAL[${key_command}]}" ]] ; then
			local p
			while IFS=, read p ; do
				landlock_arg+=" --landlock.special=${p}"
			done <<< ${LANDLOCK_SPECIAL[${key_command}]}
		fi
		if [[ -n "${LANDLOCK_EXECUTE[${key_command}]}" ]] ; then
			local p
			while IFS=, read p ; do
				landlock_arg+=" --landlock.execute=${p}"
			done <<< ${LANDLOCK_EXECUTE[${key_command}]}
		fi
		if [[ -n "${LANDLOCK_PROC[${key_command}]}" ]] ; then
			local x="${LANDLOCK_PROC[${key_command}]}"
			landlock_arg+=" --landlock.proc=${x}"
		fi
	fi

	local wh_arg="" # WidthxHeight args
	if [[ -n "${XEPHYR_WH[${key_command}]}" ]] ; then
		wh_arg="--xephyr-screen=${XEPHYR_WH[${key_command}]}"
	fi

	local apparmor_arg=""
	if [[ "${APPARMOR_PROFILE[${key_command}]}" == "default" ]] ; then
		apparmor_arg="--apparmor"
	elif [[ -n "${APPARMOR_PROFILE[${key_command}]}" ]] ; then
		apparmor_arg="--apparmor=${APPARMOR_PROFILE[${key_command}]}"
	fi

	local seccomp_arg=""
	if [[ -n "${SECCOMP[${key_command}]}" ]] ; then
		seccomp_arg+=" --seccomp"
	fi

	if [[ -n "${SECCOMP_BLOCK[${key_command}]}" ]] ; then
		seccomp_arg+=" --seccomp.drop=${SECCOMP_BLOCK[${key_command}]}"
	fi

	if [[ -n "${SECCOMP_KEEP[${key_command}]}" ]] ; then
		seccomp_arg=+" --seccomp.keep=${SECCOMP_KEEP[${key_command}]}"
	fi

	local args=""
	if [[ -n "${ARGS[${key_command}]}" ]] ; then
		args="${ARGS[${key_command}]}"
	fi

	local profile_headless_arg=""
	local profile_wayland_arg=""
	local profile_x11_arg=""
	if [[ -e "${profile_path}" ]] ; then
		if [[ "${command}" =~ "firefox" ]] ; then
			profile_headless_arg="--profile=firefox"
			profile_wayland_arg="--profile=firefox-wayland"
			profile_x11_arg="--profile=firefox-x11"
		else
			profile_headless_arg="--profile=${command}"
			profile_wayland_arg="--profile=${command}"
			profile_x11_arg="--profile=${command}"
		fi
	else
		profile_headless_arg="--profile=default"
		profile_wayland_arg="--profile=default"
		profile_arg="--profile=default"
	fi

	local pulse_arg=""
	if [[ "${key_command}" == "pavucontrol" ]] ; then
		pulse_arg+="--keep-config-pulse"
	fi

	local folder="bin"

	local is_allowed_wrapper=1

	if [[ "${scope}" =~ ("ban"|"blacklist"|"blacklisted") ]] ; then
		is_allowed_wrapper=0
	fi

	local oom_arg=""
	if [[ -n "${OOM[${key_command}]}" ]] ; then
		oom_arg="--oom=${OOM[${key_command}]}"
	fi

	local env_args=()
	local ozone_args=()
	local exe_wayland_args=()
	local exe_x11_args=()
	is_ozone=0

	if is_chromium_app "${command}" ; then
		is_ozone=1
	elif grep -q -E -e "include.*(electron-common|chromium-common)" "${T}/profiles_data/${command}.profile" 2>/dev/null ; then
		is_ozone=1
	fi

	if [[ "${command}" == "spotify" ]] ; then
		env_args=(
			--env=LD_PRELOAD="/usr/lib64/spotify-xstub.so"
		)
	fi
	if (( ${is_ozone} == 1 )) ; then
einfo "Detected CEF/Chromium.  Using ozone for Wayland."
		exe_wayland_args+=(
			--enable-features=UseOzonePlatform
			--ozone-platform=wayland
		)
	fi

	# Also includes xvfb sandbox use case
	local all_args_x11=(
		${env_args[@]}
		${apparmor_arg}
		${x11_arg}
		${allocator_args}
		${wh_arg}
		${seccomp_arg}
		${landlock_arg}
		${pulse_arg}
		${oom_arg}
		${args}
		${profile_x11_arg}
	)

	local all_args_wayland=(
		${env_args[@]}
		${apparmor_arg}
		${allocator_args}
		${seccomp_arg}
		${landlock_arg}
		${pulse_arg}
		${oom_arg}
		${args}
		${profile_wayland_arg}
	)

	# No X11 sandbox
	local all_args_none=(
		${env_args[@]}
		${apparmor_arg}
		${allocator_args}
		${seccomp_arg}
		${landlock_arg}
		${oom_arg}
		${args}
		${profile_headless_arg}
	)

	# Experimental.  Ideally we want only 1 wrapper.
	# The lockdown is not the optimal solution.
	# You need a modded web browser with fingerprinting mitigations.
	if [[ "${wrapper_name}" =~ ("chromium-lockdown"|"chromium-bin-lockdown"|"google-chrome-stable-lockdown"|"ungoogled-chromium-lockdown") ]] ; then
		all_args_wayland+=(
			--no3d
		)
		all_args_x11+=(
			--no3d
		)
		exe_wayland_args+=(
			--incognito
		)
		exe_x11_args+=(
			--incognito
		)
	elif [[ "${wrapper_name}" =~ ("firefox-lockdown"|"firefox-bin-lockdown") ]] ; then
		all_args_wayland+=(
			--no3d
		)
		all_args_x11+=(
			--no3d
		)
		exe_wayland_args+=(
			-private-window # incognito equivalent
		)
		exe_x11_args+=(
			-private-window # incognito equivalent
		)
	fi

	# The root doesn't get Firejail because we need at least 1 user to
	# unbreak a bad Firejail configuration and to not mess up the uptime
	# score.

	# EUID = 0:  root
	# EUID = 250:  portage
	gen_headless_wrapper() {
cat <<EOF > "${ED}/usr/local/${folder}/${wrapper_name}" || die
#!/bin/bash
if [[ "\${EUID}" == "0" || "\${EUID}" == "250" ]] ; then
	"${exe_path}" "\$@"
else
	exec firejail ${all_args_x11[@]} "${exe_path}" "\$@"
fi
EOF
	}

	gen_none_wrapper() {
cat <<EOF > "${ED}/usr/local/${folder}/${wrapper_name}" || die
#!/bin/bash
if [[ "\${EUID}" == "0" || "\${EUID}" == "250" ]] ; then
	"${exe_path}" "\$@"
else
	exec firejail ${all_args_none[@]} "${exe_path}" "\$@"
fi
EOF
	}

	gen_x11_wrapper() {
cat <<EOF > "${ED}/usr/local/${folder}/${wrapper_name}" || die
#!/bin/bash

if [[ "\${EUID}" == "0" || "\${EUID}" == "250" ]] ; then
	"${exe_path}" "\$@"
elif [[ -n "\${DISPLAY}" ]] ; then
	exec firejail ${all_args_x11[@]} "${exe_path}" ${exe_x11_args[@]} "\$@"
else
	exec firejail ${all_args_wayland[@]} "${exe_path}" ${exe_wayland_args[@]} "\$@"
fi
EOF
	}

	gen_xcsecurity_wrapper() {
cat <<EOF > "${ED}/usr/local/${folder}/${wrapper_name}" || die
#!/bin/bash

if [[ -e "\${XAUTHORITY}" ]] ; then
	_XAUTHORITY="\${XAUTHORITY}"
elif [[ -e "/run/user/\${EUID}/gdm/Xauthority" ]] ; then
	_XAUTHORITY="/run/user/\${EUID}/gdm/Xauthority"
elif ls "/run/user/\${EUID}/sddm/xauth_"* >/dev/null ; then
	_XAUTHORITY=\$(realpath "/run/user/${EUID}/sddm/xauth_"*)
elif ls "/run/user/\${EUID}/.mutter-Xwaylandauth" >/dev/null ; then
	_XAUTHORITY=\$(realpath "/run/user/\${EUID}/.mutter-Xwaylandauth")
fi

if [[ "\${EUID}" == "0" || "\${EUID}" == "250" ]] ; then
	"${exe_path}" "\$@"
elif [[ -n "\${DISPLAY}" ]] ; then
	xhost +si:localuser:\${USER}
	exec firejail ${all_args_x11[@]} --env=XAUTHORITY="\${_XAUTHORITY}" "${exe_path}" ${exe_x11_args[@]} "\$@"
else
	exec firejail ${all_args_wayland[@]} "${exe_path}" ${exe_wayland_args[@]} "\$@"
fi
EOF
	}

	if (( ${is_allowed_wrapper} == 1 )) ; then
		if [[ "${x11_sandbox}" == "headless" ]] ; then
			gen_headless_wrapper
		elif [[ "${x11_sandbox}" == "none" ]] ; then
			gen_none_wrapper
		elif [[ "${x11_sandbox}" == "xorg" ]] ; then
			gen_xcsecurity_wrapper
		else
	# Includes x11_sandbox == none
			gen_x11_wrapper
		fi

		fowners "root:root" "/usr/local/${folder}/${wrapper_name}"
		fperms 0755 "/usr/local/${folder}/${wrapper_name}"
	fi
}

gen_wrapper() {
	local command="${1}"
	local key_command="${1//./_}" # Sanitized associative array key
	if [[ "${1:0:1}" =~ ^[0-9] ]] ; then
# You cannot use a number as the prefix to associative array.
		key_command="_${1//./_}"
	fi

	local exe_path=""
	if [[ -n "${PATH_CORRECTION[${key_command}]}" ]] ; then
		exe_path="${PATH_CORRECTION[${key_command}]}"
	elif [[ -n "${_PATH_CORRECTION[${key_command}]}" ]] ; then
		exe_path="${_PATH_CORRECTION[${key_command}]}"
	else
		if [[ -e "/bin/${command}" ]] ; then
			exe_path="/bin/${command}"
		elif [[ -e "/sbin/${command}" ]] ; then
			exe_path="/sbin/${command}"
		elif [[ -e "/usr/bin/${command}" ]] ; then
			exe_path="/usr/bin/${command}"
		elif [[ -e "/usr/sbin/${command}" ]] ; then
			exe_path="/usr/sbin/${command}"
		else
# The abspath excluding /usr/local/bin/${command} is required to avoid possible infinite loop.
			exe_path="${command}"
ewarn "${command} is not found in standard paths.  Skipping wrapper creation for ${command} to avoid infinite loop."
			return
		fi
	fi

	# Regular = GPU acceleration + persistent profile
	# Lockdown = incognito + no GPU acceleration
	# This is not the optimal solution.
	# You need a modded browser with fingerprinting mitigations.
	if [[ "${command}" == "ungoogled-chromium" ]] ; then
		_gen_one_wrapper "${command}" "ungoogled-chromium" "${exe_path}"
		#_gen_one_wrapper "${command}" "ungoogled-chromium-lockdown" "${exe_path}"
	elif [[ "${command}" == "google-chrome-stable" ]] ; then
		_gen_one_wrapper "${command}" "google-chrome-stable" "${exe_path}"
		#_gen_one_wrapper "${command}" "google-chrome-stable-lockdown" "${exe_path}"
	elif [[ "${command}" == "chromium" ]] ; then
		if has_version "www-client/chromium" ; then
			_gen_one_wrapper "${command}" "chromium" "${exe_path}"
			#_gen_one_wrapper "${command}" "chromium-lockdown" "${exe_path}"
		fi
	elif [[ "${command}" == "firefox" ]] ; then
		if has_version "www-client/firefox" ; then
			_gen_one_wrapper "${command}" "firefox" "${exe_path}"
			#_gen_one_wrapper "${command}" "firefox-lockdown" "${exe_path}"
		fi
		if has_version "www-client/firefox-bin" ; then
			_gen_one_wrapper "${command}" "firefox-bin" "/usr/bin/firefox-bin"
			#_gen_one_wrapper "${command}" "firefox-bin-lockdown" "/usr/bin/firefox-bin"
		fi
	elif [[ "${command}" == "x-terminal-emulator" ]] ; then
		local terms=(
			"alacritty"
			"aterm"
			"cool-retro-term"
			"gnome-terminal"
			"guake"
			"kitty"
			"kterm"
			"konsole"
			"lxterminal"
			"mate-terminal"
			"ptyxis"
			"qterminal"
			"roxterm"
			"rxvt-unicode"
			"sakura"
			"st"
			"terminator"
			"terminology"
			"tilda"
			"wezterm"
			"xfce4-terminal"
			"xterm"
			"yakuake"
			"yeahconsole"
			"zutty"
		)
		local command
		for command in "${terms[@]}" ; do
			local exe_path=""
			if [[ -n "${PATH_CORRECTION[${command}]}" ]] ; then
				exe_path="${PATH_CORRECTION[${command}]}"
			elif [[ -n "${_PATH_CORRECTION[${command}]}" ]] ; then
				exe_path="${_PATH_CORRECTION[${command}]}"
			elif [[ -e "/usr/bin/${command}" ]] ; then
				exe_path="/usr/bin/${command}"
			fi
			if [[ -e "${exe_path}" ]] ; then
				_gen_one_wrapper "${command}" "${command}" "${exe_path}"
			fi
		done
	elif \
		[[ \
			   -e "/bin/${command}" \
			|| -e "/sbin/${command}" \
			|| -e "/usr/bin/${command}" \
			|| -e "/usr/sbin/${command}" \
		]] \
	; then
	#
	# Ideally we like to install the wrappers to catch all the future cases,
	# but it is not possible without all the information.
	#
	# Many programs and build system configure checks use the which command
	# as a lazy way to check if the program exists.  We cannot install all
	# the wrappers because it will break a lot of configure test
	# assumptions.
	#
	# Also if it is not installed, we don't know which of the above is
	# correct.
	#
		_gen_one_wrapper "${command}" "${command}" "${exe_path}"
	else
ewarn "Skipping wrapper creation for ${command} because it was not found in standard paths."
	fi
}

_install_profiles() {
	default

	if use contrib ; then
		python_scriptinto "/usr/$(get_libdir)/firejail"
		python_doscript "contrib/"*".py"
		insinto "/usr/$(get_libdir)/firejail"
		dobin "contrib/"*".sh"
	fi

	mkdir -p "${T}/profiles" || die
	mv \
		$(find "${ED}/etc/firejail/" -name "*.profile") \
		"${T}/profiles" \
		|| die

	# Stable state set for analysis
	mkdir -p "${T}/profiles_data" || die
	cp -aT "${T}/profiles" "${T}/profiles_data" || die

	mkdir -p "${T}/profiles_processed" || die

	get_scope() {
		local arg="${1}"

		if [[ "${SCOPE[${arg}]}" ]] ; then
			# User scope override
			echo "${SCOPE[${arg}]}"
		elif [[ -n "${_SCOPE[${arg}]}" ]] ; then
			# Ebuild scope
			echo "${_SCOPE[${arg}]}"
		else
			echo ""
		fi
	}

	local commands=(
		$(get_supported_commands) # Program name
	)

einfo "DEBUG: commands ${commands[@]}"

	local command
	for command in "${commands[@]}" ; do
		local src
		local dest
		src=$(find "${T}/profiles" -name "${command}.profile" \
			| sed -r -e "s|[ ]+||g")
		dest="${ED}/etc/firejail/${command}.profile"

		local key_command="${command//./_}" # # Sanitized associative array key
		if [[ "${command:0:1}" =~ ^[0-9] ]] ; then
# You cannot use a number as the prefix to associative array.
			key_command="_${command//./_}"
		fi

		local exe_path=""
		if [[ -n "${PATH_CORRECTION[${key_command}]}" ]] ; then
			exe_path="${PATH_CORRECTION[${key_command}]}"
		elif [[ -n "${_PATH_CORRECTION[${key_command}]}" ]] ; then
			exe_path="${_PATH_CORRECTION[${key_command}]}"
		else
			exe_path="/usr/bin/${command}"
		fi

		local scope
		scope=$(get_scope "${key_command}")

# Move it to image folder
		if use wrapper [[ -e "${exe_path}" || "${command}" == "x-terminal-emulator" ]] && ! [[ "${command}" =~ "-common" ]] && ! [[ "${command}" =~ "-wrapper" ]] && ! [[ "${scope}" =~ ("ban"|"blacklist"|"blacklisted") ]] ; then
einfo "Adding ${command} profile with wrapper (1)"
			#einfo "deps for ${command}:  ${deps[@]}"
			mv "${src}" "${dest}" || die
			gen_wrapper "${command}"
		elif [[ "${command}" =~ ("default"|"server") ]] ; then
einfo "Adding ${command} profile (2)"
			mv "${src}" "${dest}" || die
		elif true ; then
	# Add all the profiles
			mv "${src}" "${dest}" || die
			if use wrapper && ! [[ "${u}" =~ "-common" ]] && ! [[ "${u}" =~ "-wrapper" ]] ; then
einfo "Adding ${command} profile with wrapper (3)"
				gen_wrapper "${command}"
			else
einfo "Adding ${command} profile (4)"
			fi
		else
einfo "Moving rejected ${command} profile (5)"
			local dest="${T}/profiles_processed"
			mv "${src}" "${dest}" || die
		fi
	done

	if (( $(find "${T}/profiles" | sed -e "1d" | wc -l) != 0 )) ; then
eerror "${T}/profiles is not empty"
		die
	fi

einfo "Verifying release build"
	if grep -r -e "/image/" "${ED}/usr/bin" ; then
eerror "Detected test binaries"
		die
	fi
	if grep -r -e "/image/" "${ED}/usr/$(get_libdir)" ; then
eerror "Detected test libraries"
		die
	fi
}

src_install() {
	export X11_COMPAT=( $(get_x11_compat) ) # Use before wrappers installed
einfo "${X11_COMPAT}:  ${X11_COMPAT}"

	use wrapper && dodir "/usr/local/bin"
	local impl
	for impl in $(get_impls) ; do
		export BUILD_DIR="${S}_${impl}"
		cd "${BUILD_DIR}" || die

		# Test does not get installed due to modifications
		[[ "${impl}" == "test" ]] && continue

		_install_profiles
	done

	if (( "${#COMMAND[@]}" >= "1" )) ; then
		local x
		for x in ${!COMMAND[@]} ; do
			local program="${x}"
			gen_wrapper "${command}"
		done
	fi

	if ! use vanilla ; then
		# Gentoo-specific profile customizations
		insinto "/etc/${PN}"
		local profile_local
		for profile_local in "${FILESDIR}/profile_"*"local" ; do
			newins "${profile_local}" "${profile_local/\/*profile_/}"
		done
	fi

	# Prevent sandbox violations when toolchain is firejailed
cat > "${T}/99firejail" <<-EOF || die
SANDBOX_WRITE="/run/firejail"
EOF
	insinto "/etc/sandbox.d"
	doins "${T}/99firejail"

	if use suid ; then
ewarn "Adding the suid bit for /usr/bin/firejail"
		fperms "u+s" "/usr/bin/firejail"
	else
einfo "Removing the suid bit for /usr/bin/firejail"
		fperms "u-s" "/usr/bin/firejail"
einfo "Updating config for non-suid mode"
		sed -i \
			-e "s|# force-nonewprivs no|force-nonewprivs yes|g" \
			-e "s|# userns yes|userns yes|g"
			"${ED}/etc/firejail/firejail.conf" \
			|| die
	fi

	dodir "/usr/share/${PN}"
	mv "${ED}/usr/share/doc/firejail-${PV}/profile.template" "${ED}/usr/share/${PN}" || die
}

pkg_postinst() {
einfo
einfo "Note to ricers and optimization fanatics:"
einfo
einfo "You may need to update /etc/firejail/globals.local to add"
einfo "private-lib gcc/*/*/libgomp.so.*"
einfo
ewarn
ewarn "The /usr/local/firejail-bin has been removed.  You should remove"
ewarn "PATH=\"/usr/local/firejail-bin:\${PATH}\" from ~/.bashrc."
ewarn

ewarn
ewarn "SUID is required for ${MY_PN} to work, so using it has risk of privilege"
ewarn "escalation."
ewarn

einfo
einfo "TIP:  If the app processes untrusted data, user generated content, or"
einfo "interacts with the network or Internet, it should have a ${MY_PN}"
einfo "profile."
einfo

ewarn
ewarn
ewarn "IMPORTANT:  Please read the section \"important blacklist paths\" and"
ewarn "\"path traversal mitigation verification\" section in the metadata.xml"
ewarn "(\`epkginfo -x firejail::oiledmachine-overlay\`) to properly secure"
ewarn "the browser ~/Downloads folder containing PII or sensitive data and"
ewarn "crown jewel keys."
ewarn
ewarn
ewarn "IMPORTANT:  File names containing sensitive data/keys in the root"
ewarn "directory are exposed to an attacker in the sandbox.  They should be"
ewarn "moved in either another disk or in a folder with a blacklist.  Blacklist"
ewarn "these paths in /etc/firejail/globals.local.  Blacklist the folder"
ewarn "containing the file."
ewarn
ewarn
ewarn "IMPORTANT:  Always check sandbox profiles by manual inspection in the"
ewarn "sandbox to verify if there is any sensitive data leaks.  See the"
ewarn "\"path traversal mitigation verification\" section in the metadata.xml."
ewarn
# Remove the annoying compression
einfo
einfo "For a starter ${PN} profile, copy-paste"
einfo
einfo "  /usr/share/${PN}/profile.template"
einfo
einfo "into"
einfo
einfo "  /etc/firejail/<cli-name>.profile       # for systemwide"
einfo "  ~/.config/firejail/<cli-name>.profile  # for profiles to follow your profile backups"
ewarn
einfo
	if ! use suid ; then
einfo
einfo "USE=-suid is not tested.  Ask the AI for help."
einfo
	fi
ewarn
ewarn "To update profiles, run etc-update."
ewarn
ewarn
ewarn "The /etc/profile/default.profile is now more restrictive to mitigate"
ewarn "Living of the Land attacks.  To relax, add needed noblacklist <path> to"
ewarn "/etc/firejail/default.local or ~/.config/firejail/default.local."
ewarn
ewarn "Example:"
ewarn
ewarn "noblacklist \${PATH}/bash"
ewarn "noblacklist \${PATH}/sh"
ewarn "noblacklist \${PATH}/ls"
ewarn
einfo
einfo "\`emerge -vO ${CATEGORY}/${PN}\` later after installing @world to update wrappers."
einfo
einfo
einfo "The npm, pnpm, yarn eclasses now use Firejail, but it requires setup to"
einfo "protect credentials and secrets.  (oiledmachine-overlay feature)"
einfo
einfo "Installing Firejail already opts-in to using Firejail as a way for"
einfo "access control to credentials/secrets."
einfo
einfo "To opt-out, add the following per package or to /etc/portage/make.conf:"
einfo
einfo "  NPM_FIREJAIL=0"
einfo "  PNPM_FIREJAIL=0"
einfo "  YARN_FIREJAIL=0"
einfo
einfo
einfo "To protect credentials and secrets from supply chain attacks for npm, pnpm, yarn, node"
einfo
einfo "  Set the contents of /etc/firejail/npm.local:"
einfo "  Set the contents of /etc/firejail/pnpm.local:"
einfo "  Set the contents of /etc/firejail/yarn.local:"
einfo "  Set the contents of /etc/firejail/node-common.local:"
einfo "  Set the contents of /etc/firejail/globals.local:"
einfo
einfo "blacklist <credentials-path>"
einfo "blacklist <secrets-path>"
einfo "rmenv <var-name>"
einfo "blacklist /mnt/usb/passwords.kdbx"
einfo "blacklist /home/johndoe/.ssh"
einfo "rmenv KEY_VAULTS_SECRET"
einfo
ewarn
# For the Boost friendly environment variable changes suggested by the distro
# ebuild, this is a course-grained edit that decreases the complexity of stack
# smash attack.  It is unknown if limits raised was intentionally to weaken the
# security of the sandbox by the distro ebuild maintainers to help threat
# actors.  The unintended consequence is that lifting the limits encourages
# abusing environment variables to store keys or non-free access tokens in
# plaintext.
ewarn "For Boost or CMake dependent builds with issues, in"
ewarn "/etc/firejail/firejail.config set arg-max-count 4096 and"
ewarn "env-max-count 1024."
ewarn
ewarn "For Electron or Node.js dependent builds, use keep env-max-count as 512."
ewarn
ewarn "For production or after emerging, revert back to upstream defaults with"
ewarn "env-max-count 256 and arg-max-count 128."
ewarn
ewarn "The reasons why env-max-count should kept low:"
ewarn
ewarn "- To mitigate DoS."
ewarn "- To mitigate payload obfuscation."
ewarn "- To mitigate RCE buffer overflows."
ewarn "- To mitigate SUID privilege escalation via stack clash attack."
ewarn "- To mitigate truncation of PATH in different implementations."
ewarn "- To mitigate the chances of too many secrets or API keys leaked."
ewarn
ewarn
ewarn "GPU acceleration is off by default."
ewarn
ewarn "To add GPU acceleration add \`include allow-gpu-acceleration.inc\` to"
ewarn "either:"
ewarn
ewarn "/etc/firejail/globals.local"
ewarn "/etc/firejail/<cli-cmd>.local"
ewarn "/home/<user-name>/.config/firejail/globals.local"
ewarn "/home/<user-name>/.config/firejail/<cli-cmd>.local"
ewarn
ewarn "Keep GPU acceleration off in untrusted contexts to mitigate sandbox"
ewarn "escape, information disclosure, code execution, privilege escalation."
ewarn "Use GPU acceleration selectively."
ewarn
}

# OILEDMACHINE-OVERLAY-META:  LEGAL-PROTECTIONS
# OILEDMACHINE-OVERLAY-META-MOD-TYPE:  patches, ebuild-changes, profile-selection, testing-sections, audio-patch
# OILEDMACHINE-OVERLAY-META-WIP:  test-USE-flag
# OILEDMACHINE-OVERLAY-META-DETAILED-NOTES:  The test USE flag was found useful in correcting profile errors and why it kept around; however, it is garbage quality.
# OILEDMACHINE-OVERLAY-TEST:  PASSED (1a576d1 with xpra 5.0.11 and 6.2.1, 20250118)
# OILEDMACHINE-OVERLAY-TEST:  PASSED (897f12d, 20250118)
# OILEDMACHINE-OVERLAY-TEST:  PASSED (1a576d1, 20250814)
# OILEDMACHINE-OVERLAY-TEST:  PASSED (0.9.76, 20250814)
# OILEDMACHINE-OVERLAY-TEST:  PASSED (0.9.78, 20260102)

# Tested for both 1a576d1, 897f12d
# For sys-apps/firejail
# USE="X auto chroot clang fallback-commit landlock private-home suid userns
# wrapper xephyr xpra -apparmor -contrib -dbusproxy -file-transfer -globalcfg
# -hardened_malloc -mimalloc -network -scudo -selfrando (-selinux) -test
# -test-profiles -test-x11 -vanilla -xvfb"

# 1a576d1 tests and config (on 20250814):
# mousepad with xephyr:  passed
# mousepad with xpra:  passed
# mousepad with wayland:  passed
# xpra 6.2.5:  passed
# xpra 6.3.2:  passed
#
# xpra USE flags used for testing:
# USE="X avif client cython firejail gtk3 jpeg rencodeplus server vsock webp
# -aac -aes -alsa -amf -aom -appindicator -audio -avahi -brotli -cityhash
# -clipboard -cpu-percent -csc_cython -csc_libyuv -cuda -cuda_rebuild -cups
# -cups-forwarding -cythonize-more -dbus (-debug) -doc -drm -evdi -flac
# -gnome-shell -gssapi -html5-client -html5_brotli -html5_gzip -http -ibus -jack
# -kerberos -keyboard-layout -keycloak -lame -ldap -ldap3 -lz4 -lzo -matroska
# -mdns -mp3 -mysql -netdev -notifications -nvdec -nvenc -nvfbc -nvjpeg -ogg
# -opengl -openh264 -openrc -opus -osmesa -oss -otp -pam -pinentry -png -proc
# -proxy -pulseaudio -pyglet -pyinotify -qrencode -qt6 -quic -remote-encoder
# -rencode -rfb -sd_listen (-selinux) -socks -sound-forwarding -speex -spng -sql
# -sqlite -ssh -sshpass -ssl -systemd -tcp-wrappers -test -tiff -tk -u2f -uinput
# -v4l2 -vaapi -vorbis -vpx -wavpack -wayland -webcam -webcam-forwarding
# -websockets -x264 -xdg -xinput -yaml -zeroconf -zlib"
# PYTHON_SINGLE_TARGET="python3_11 -python3_12"
#
# firejail USE flags used for testing:
# USE="X auto chroot clang landlock private-home userns wrapper xephyr xpra
# -apparmor -contrib -dbusproxy -file-transfer -globalcfg -hardened_malloc
# -mimalloc -network -scudo -selfrando (-selinux) -test -test-profiles -test-x11
# -vanilla -xvfb"
#
