#!/bin/bash
NODE_ENV="${NODE_ENV}"
NODE_VERSION="${NODE_VERSION}"
PROJECT_ROOT="${INSTALL_DIR}"
cd "${PROJECT_ROOT}"
if [[ -n "${DISPLAY}" ]] ; then
	./${PN} "$@"
else
	./${PN} --enable-features=UseOzonePlatform --ozone-platform-hint=wayland "$@"
fi
