#!/bin/bash
PROJECT_ROOT="@INSTALL_DIR@"
cd "${PROJECT_ROOT}"
if [[ -n "${DISPLAY}" ]] ; then
	"./${PN}" "$@"
else
	"./${PN}" --enable-features="UseOzonePlatform" --ozone-platform-hint="wayland" "$@"
fi
