# Copyright 2023 Orson Teodoro <orsonteodoro@hotmail.com>
# Copyright 1999-2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

LLVM_MAX_SLOT=14
PYTHON_COMPAT=( python3_{9..11} ) # CI uses 3.8

# LLVM 14 support is complete.
# LLVM 15 support is a Work In Progress (WIP)
# LLVM 16 support is a Work In Progress (WIP)

# Auto-Generated by cargo-ebuild 0.5.2
CRATES="
	adler-1.0.2
	aho-corasick-0.7.20
	ansi_term-0.12.1
	atty-0.2.14
	autocfg-1.1.0
	bindgen-0.59.2
	bit_field-0.10.1
	bitflags-1.3.2
	block-buffer-0.10.3
	bumpalo-3.11.1
	bytemuck-1.12.3
	byteorder-1.4.3
	cbindgen-0.20.0
	cexpr-0.6.0
	cfg-if-1.0.0
	clang-sys-1.4.0
	clap-2.34.0
	color_quant-1.1.0
	cpufeatures-0.2.5
	crc32fast-1.3.2
	crossbeam-channel-0.5.6
	crossbeam-deque-0.8.2
	crossbeam-epoch-0.9.13
	crossbeam-utils-0.8.14
	crunchy-0.2.2
	crypto-common-0.1.6
	digest-0.10.6
	either-1.8.0
	env_logger-0.9.3
	exr-1.5.2
	fastrand-1.8.0
	flate2-1.0.25
	flume-0.10.14
	futures-core-0.3.25
	futures-sink-0.3.25
	generic-array-0.14.6
	getrandom-0.2.8
	gif-0.11.4
	glob-0.3.0
	half-2.1.0
	hashbrown-0.12.3
	heck-0.3.3
	hermit-abi-0.1.19
	hex-0.4.3
	humantime-2.1.0
	image-0.24.5
	indexmap-1.9.2
	instant-0.1.12
	itoa-1.0.4
	jpeg-decoder-0.3.0
	js-sys-0.3.60
	lazy_static-1.4.0
	lazycell-1.3.0
	lebe-0.5.2
	libc-0.2.137
	libloading-0.7.4
	lock_api-0.4.9
	log-0.4.17
	memchr-2.5.0
	memoffset-0.7.1
	minimal-lexical-0.2.1
	miniz_oxide-0.6.2
	nanorand-0.7.0
	nom-7.1.1
	num-complex-0.4.2
	num-integer-0.1.45
	num-rational-0.4.1
	num-traits-0.2.15
	num_cpus-1.14.0
	once_cell-1.16.0
	peeking_take_while-0.1.2
	pin-project-1.0.12
	pin-project-internal-1.0.12
	png-0.17.7
	primal-check-0.3.3
	proc-macro2-1.0.47
	quote-1.0.21
	rayon-1.6.0
	rayon-core-1.10.1
	redox_syscall-0.2.16
	regex-1.7.0
	regex-syntax-0.6.28
	remove_dir_all-0.5.3
	rustc-hash-1.1.0
	rustdct-0.7.1
	rustfft-6.1.0
	ryu-1.0.11
	scoped_threadpool-0.1.9
	scopeguard-1.1.0
	serde-1.0.148
	serde_derive-1.0.148
	serde_json-1.0.89
	sha2-0.10.6
	shlex-1.1.0
	smallvec-1.10.0
	spin-0.9.4
	strength_reduce-0.2.4
	strsim-0.8.0
	syn-1.0.104
	tempfile-3.3.0
	termcolor-1.1.3
	textwrap-0.11.0
	thiserror-1.0.37
	thiserror-impl-1.0.37
	threadpool-1.8.1
	tiff-0.8.0
	toml-0.5.9
	transpose-0.2.2
	typenum-1.15.0
	unicode-ident-1.0.5
	unicode-segmentation-1.10.0
	unicode-width-0.1.10
	vec_map-0.8.2
	version_check-0.9.4
	wasi-0.11.0+wasi-snapshot-preview1
	wasm-bindgen-0.2.83
	wasm-bindgen-backend-0.2.83
	wasm-bindgen-macro-0.2.83
	wasm-bindgen-macro-support-0.2.83
	wasm-bindgen-shared-0.2.83
	weezl-0.1.7
	which-4.3.0
	winapi-0.3.9
	winapi-i686-pc-windows-gnu-0.4.0
	winapi-util-0.1.5
	winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo cmake flag-o-matic lcnr llvm python-any-r1 systemd tmpfiles

MY_P=${P//_/-}

DESCRIPTION="Clam Anti-Virus Scanner"
HOMEPAGE="https://www.clamav.net/"
SRC_URI="
https://github.com/Cisco-Talos/clamav/archive/refs/tags/${MY_P}.tar.gz
	$(cargo_crate_uris ${CRATES})
"
S="${WORKDIR}/clamav-${MY_P}"

THIRD_PARTY_LICENSES+="
	0BSD
	Apache-2.0
	Boost-1.0
	BSD
	BSD-2
	BZIP2
	CC-BY-3.0
	curl
	GPL-2
	ISC
	LGPL-2.1
	MIT
	MPL-2.0
	public-domain
	unRAR
	Unlicense
	UoI-NCSA
	ZLIB
	Unicode-DFS-2016
	|| ( Unlicense MIT )
	|| ( MIT Apache-2.0 )
"

LICENSE="
	${THIRD_PARTY_LICENSES}
	GPL-2
	LGPL-2.1
"

# 0BSD - cargo_home/gentoo/adler-1.0.2/LICENSE-0BSD
# Apache-2.0 - cargo_home/gentoo/glob-0.3.0/LICENSE-APACHE
# Boost-1.0 - cargo_home/gentoo/ryu-1.0.11/LICENSE-BOOST
# BSD - cargo_home/gentoo/instant-0.1.12/LICENSE
# BSD-2 - COPYING/COPYING.file
# BZIP2 - COPYING/COPYING.bzip2
# CC-BY-3.0 - cargo_home/gentoo/crossbeam-channel-0.5.6/LICENSE-THIRD-PARTY
# curl - COPYING/COPYING.curl
# GPL-2 - unit_tests/input/COPYING
# ISC - cargo_home/gentoo/libloading-0.7.4/LICENSE
# LGPL-2.1 - libclammspack/COPYING.LIB
# MIT - clamonacc/c-thread-pool/LICENSE
# MPL-2.0 - cargo_home/gentoo/cbindgen-0.20.0/LICENSE
# public-domain - libclamav/tomsfastmath/LICENSE
# public-domain - COPYING/COPYING.lzma
# unRAR - libclamunrar/license.txt
# Unlicense - cargo_home/gentoo/byteorder-1.4.3/UNLICENSE
# UoI-NCSA - COPYING/COPYING.llvm
# ZLIB - cargo_home/gentoo/miniz_oxide-0.6.2/LICENSE-ZLIB.md
# Unicode-DFS-2016 - cargo_home/gentoo/regex-syntax-0.6.28/src/unicode_tables/LICENSE-UNICODE
# || ( Unlicense MIT ) - cargo_home/gentoo/byteorder-1.4.3/COPYING
# || ( MIT Apache-2.0 ) - cargo_home/gentoo/half-2.1.0/LICENSE

SLOT="0"
if [[ ${PV} != *_rc* ]] ; then
	KEYWORDS="~alpha ~amd64 ~arm ~arm64 ~ppc ~ppc64 ~riscv ~sparc ~x86"
	KEYWORDS+=" ~amd64-linux ~x86-linux ~ppc-macos ~sparc-solaris"
	KEYWORDS+=" ~x86-solaris"
fi
IUSE="
doc clamonacc +clamapp custom-cflags experimental jit libclamav-only man milter rar
selinux systemd test valgrind
"

REQUIRED_USE="
	clamonacc? (
		clamapp
	)
	libclamav-only? (
		!clamapp
		!clamonacc
		!milter
	)
	milter? (
		clamapp
	)
	test? (
		!libclamav-only
	)
"

#RESTRICT="!test? ( test )"

# Require acct-{user,group}/clamav at build time so that we can set
# the permissions on /var/lib/clamav in src_install rather than in
# pkg_postinst; calling "chown" on the live filesystem scares me.

# See CI for details.
# CI uses U 22.04
# OpenSSL-3 required for license compatibility
CURL_PV="7.68.0"
PYTEST_PV="7.2.0"
# The dev-libs/libmspack version has been lowered in this ebuild.
CDEPEND="
	!libclamav-only? (
		>=net-misc/curl-${CURL_PV}
	)
	>=app-arch/bzip2-1.0.8
	>=dev-libs/openssl-1.1.1f:=
	>=dev-libs/json-c-0.13.1:=
	>=dev-libs/libltdl-2.4.6
	>=dev-libs/libmspack-0.10.1_alpha
	>=dev-libs/libpcre2-8.39:=
	>=dev-libs/libxml2-2.9.10
	>=sys-libs/zlib-1.2.1:=
	acct-group/clamav
	acct-user/clamav
	virtual/libiconv
	clamapp? (
		>=net-misc/curl-${CURL_PV}
		>=sys-libs/ncurses-6.2:=
	)
	elibc_glibc? (
		>=sys-libs/glibc-2.31
	)
	elibc_musl? (
		sys-libs/fts-standalone
	)
	jit? (
		<sys-devel/llvm-$((${LLVM_MAX_SLOT} + 1)):=
		>=sys-devel/llvm-14:=
	)
	milter? (
		>=mail-filter/libmilter-8.15.2:=
	)
	rar? (
		>=app-arch/unrar-6.1.5
	)
	test? (
		$(python_gen_any_dep ">=dev-python/pytest-${PYTEST_PV}"'[${PYTHON_USEDEP}]')
	)
"

BDEPEND="
	>=virtual/rust-1.65.0
	virtual/pkgconfig
	doc? (
		>=app-doc/doxygen-1.9.1
	)
	test? (
		${PYTHON_DEPS}
		$(python_gen_any_dep ">=dev-python/pytest-${PYTEST_PV}"'[${PYTHON_USEDEP}]')
		valgrind? (
			>=dev-util/valgrind-3.15.0
		)
	)
"

DEPEND="
	${CDEPEND}
	test? (
		>=dev-libs/check-0.10.0
	)
"

RDEPEND="
	${CDEPEND}
	selinux? (
		sec-policy/selinux-clamav
	)
"

python_check_deps() {
	python_has_version -b ">=dev-python/pytest-${PYTEST_PV}[${PYTHON_USEDEP}]"
}

pkg_setup() {
	use jit && llvm_pkg_setup
	use test && python-any-r1_pkg_setup
einfo
einfo "To hard unmask the jit USE flag, do:"
einfo
echo
echo "mkdir -p /etc/portage/profile/package.use.mask"
echo "echo \"app-antivirus/clamav -jit\" >> /etc/portage/profile/package.use.mask"
echo
}

PATCHES=(
	"${FILESDIR}/${PN}-1.0.0-select-python.patch"
	"${FILESDIR}/${PN}-1.0.0-CMakeLists-allow-llvm16.patch"
	"${FILESDIR}/${PN}-1.0.0-llvm14-noreturn.patch"
	"${FILESDIR}/${PN}-1.0.0-llvm14.patch"
	"${FILESDIR}/${PN}-1.0.0-llvm15.patch"
)

src_prepare() {
	cmake_src_prepare
	if ver_test ${LLVM_SLOT} -ge 16 ; then
einfo "LLVM_SLOT:\t${LLVM_SLOT}"
		eapply "${FILESDIR}/${PN}-1.0.0-llvm16.patch"
		ewarn "JIT is still broken for LLVM 16"
	fi
	if ver_test ${LLVM_SLOT} -ge 15 ; then
einfo "LLVM_SLOT:\t${LLVM_SLOT}"
		ewarn "JIT is still broken for LLVM 15"
	fi
}

print_glibc_required_flags() {
eerror
eerror "Did not find ${1}"
eerror
eerror "sys-libs/glibc must be built with:"
eerror
eerror
eerror "/etc/portage/env/ggdb3.conf:"
eerror
eerror "  CFLAGS=\"\${CFLAGS} -ggdb3\""
eerror "  CXXFLAGS=\"\${CXXFLAGS} -ggdb3\""
eerror
eerror "/etc/portage/env/splitdebug.conf:"
eerror
eerror "  FEATURES=\"\${FEATURES} splitdebug\""
eerror
eerror "/etc/portage/env/compressdebug.conf (optional):"
eerror
eerror "  FEATURES=\"\${FEATURES} splitdebug\""
eerror
eerror "/etc/portage/env/nostrip.conf:"
eerror
eerror "  FEATURES=\"\${FEATURES} nostrip\""
eerror
eerror "/etc/portage/package.env:"
eerror
eerror "  sys-libs/glibc ggdb3.conf splitdebug.conf compressdebug.conf nostrip.conf"
eerror
}

src_configure() {
	use elibc_musl && append-ldflags -lfts
	use ppc64 && append-flags -mminimal-toc

	if ! use custom-cflags ; then
		# Upstream default in CI is just -O3.
		strip-flags
		filter-flags \
			'-march=*' \
			'-mtune=*'
		replace-flags '-O*' '-O3'
	fi

	clang --version
	local mycmakeargs=(
		-DAPP_CONFIG_DIRECTORY="${EPREFIX}"/etc/clamav
		-DBYTECODE_RUNTIME=$(usex jit llvm interpreter)
		-DCLAMAV_GROUP="clamav"
		-DCLAMAV_USER="clamav"
		-DDATABASE_DIRECTORY="${EPREFIX}"/var/lib/clamav
		-DENABLE_APP=$(usex clamapp ON OFF)
		-DENABLE_CLAMONACC=$(usex clamonacc ON OFF)
		-DENABLE_DOXYGEN=$(usex doc)
		-DENABLE_EXPERIMENTAL=$(usex experimental ON OFF)
		-DENABLE_EXTERNAL_MSPACK=ON
		-DENABLE_JSON_SHARED=ON
		-DENABLE_MAN_PAGES=$(usex man ON OFF)
		-DENABLE_MILTER=$(usex milter ON OFF)
		-DENABLE_SHARED_LIB=ON
		-DENABLE_STATIC_LIB=OFF
		-DENABLE_SYSTEMD=$(usex systemd ON OFF)
		-DENABLE_TESTS=$(usex test ON OFF)
		-DENABLE_UNRAR=$(usex rar ON OFF)
		-DOPTIMIZE=ON
	)

	if use test ; then
		# https://bugs.gentoo.org/818673
		# Used to enable some more tests but doesn't behave well in
		# sandbox necessarily(?) + needs certain debug symbols present
		# in e.g. glibc.
		mycmakeargs+=(
			-DCMAKE_DISABLE_FIND_PACKAGE_Valgrind=$(usex valgrind OFF ON)
			-DPYTHON_FIND_VERSION="${EPYTHON#python}"
		)

		unset VALGRIND # Let build scripts decide
		if use valgrind && use elibc_glibc ; then
			if ! grep -q -e "-ggdb3" \
				"${ESYSROOT}"/var/db/pkg/sys-libs/glibc-*/CFLAGS ; then
				print_glibc_required_flags "-ggdb3"
				die
			fi
			if ! grep -q -e "splitdebug" \
				"${ESYSROOT}"/var/db/pkg/sys-libs/glibc-*/FEATURES ; then
				print_glibc_required_flags "splitdebug"
				die
			fi
			if ! grep -q -e "nostrip" \
				"${ESYSROOT}"/var/db/pkg/sys-libs/glibc-*/FEATURES ; then
				print_glibc_required_flags "nostrip"
				die
			fi
		fi
	fi

	if use jit ; then
		# Suppress CMake warnings that variables aren't consumed if we aren't using LLVM
		# https://github.com/Cisco-Talos/clamav/blob/main/INSTALL.md#llvm-optional-see-bytecode-runtime-section
		# https://github.com/Cisco-Talos/clamav/blob/main/INSTALL.md#bytecode-runtime
		mycmakeargs+=(
			-DLLVM_ROOT_DIR="$(get_llvm_prefix -d ${LLVM_MAX_SLOT})"
			-DLLVM_FIND_VERSION="$(best_version sys-devel/llvm:${LLVM_MAX_SLOT} | cut -c 16-)"
		)
	fi

	cmake_src_configure
}

src_test() {
	use valgrind && ewarn "Testing with valgrind may likely fail."
	cd "${BUILD_DIR}" || die
	use jit && unit_tests/check_clamav || die
	cmake_src_test
}

src_install() {
	cmake_src_install
	# init scripts
	newinitd "${FILESDIR}/clamd.initd" clamd
	newinitd "${FILESDIR}/freshclam.initd" freshclam
	use clamonacc \
		&& newinitd "${FILESDIR}/clamonacc.initd" clamonacc
	use milter \
		&& newinitd "${FILESDIR}/clamav-milter.initd" clamav-milter

	rm -rf "${ED}"/var/lib/clamav || die

	if ! use libclamav-only ; then
		if use systemd ; then
			# The tmpfiles entry is behind USE=systemd because the
			# upstream OpenRC service files should (and do) ensure that
			# the directories they need exist and have the correct
			# permissions without the help of opentmpfiles. There are
			# years-old root exploits in opentmpfiles, the design is
			# fundamentally flawed, and the maintainer is not up to
			# the task of fixing it.
			dotmpfiles "${FILESDIR}/tmpfiles.d/clamav.conf"
			systemd_newunit "${FILESDIR}/clamd_at.service-0.104.0" "clamd@.service"
			systemd_dounit "${FILESDIR}/clamd.service"
			systemd_newunit "${FILESDIR}/freshclamd.service-r1" \
				"freshclamd.service"
		fi

		if use clamapp ; then
			# Modify /etc/{clamd,freshclam}.conf to be usable out of the box
			sed \
				-e "s:^\(Example\):\# \1:" \
				-e "s/^#\(PidFile .*\)/\1/" \
				-e "s/^#\(LocalSocket .*\)/\1/" \
				-e "s/^#\(User .*\)/\1/" \
				-e "s:^\#\(LogFile\) .*:\1 ${EPREFIX}/var/log/clamav/clamd.log:" \
				-e "s:^\#\(LogTime\).*:\1 yes:" \
				-e "s/^#\(DatabaseDirectory .*\)/\1/" \
				"${ED}"/etc/clamav/clamd.conf.sample > \
				"${ED}"/etc/clamav/clamd.conf || die

			sed \
				-e "s:^\(Example\):\# \1:" \
				-e "s/^#\(PidFile .*\)/\1/" \
				-e "s/^#\(DatabaseOwner .*\)/\1/" \
				-e "s:^\#\(UpdateLogFile\) .*:\1 ${EPREFIX}/var/log/clamav/freshclam.log:" \
				-e "s:^\#\(NotifyClamd\).*:\1 ${EPREFIX}/etc/clamav/clamd.conf:" \
				-e "s:^\#\(ScriptedUpdates\).*:\1 yes:" \
				-e "s/^#\(DatabaseDirectory .*\)/\1/" \
				"${ED}"/etc/clamav/freshclam.conf.sample > \
				"${ED}"/etc/clamav/freshclam.conf || die

			if use milter ; then
				# Note: only keep the "unix" ClamdSocket and MilterSocket!
				sed \
					-e "s:^\(Example\):\# \1:" \
					-e "s/^#\(PidFile .*\)/\1/" \
					-e "s/^#\(ClamdSocket unix:.*\)/\1/" \
					-e "s/^#\(User .*\)/\1/" \
					-e "s/^#\(MilterSocket unix:.*\)/\1/" \
					-e "s:^\#\(LogFile\) .*:\1 ${EPREFIX}/var/log/clamav/clamav-milter.log:" \
					"${ED}"/etc/clamav/clamav-milter.conf.sample > \
					"${ED}"/etc/clamav/clamav-milter.conf || die

				systemd_newunit "${FILESDIR}/clamav-milter.service-0.104.0" clamav-milter.service
			fi

			local i
			for i in clamd freshclam clamav-milter
			do
				if [[ -f "${ED}"/etc/"${i}".conf.sample ]] ; then
					mv "${ED}"/etc/"${i}".conf{.sample,} || die
				fi
			done

			# These both need to be writable by the clamav user.
			# TODO: use syslog by default; that's what it's for.
			diropts -o clamav -g clamav
			keepdir /var/lib/clamav
			keepdir /var/log/clamav
		fi
	fi

	if use doc ; then
		local HTML_DOCS=( docs/html/. )
		einstalldocs
	fi

	# Don't install man pages for utilities we didn't install
	if use libclamav-only ; then
		rm -r "${ED}"/usr/share/man || die
	fi

	find "${ED}" -name '*.la' -delete || die

	# Some rustc/rustfft references in libclamav.so.11.0.0
	LCNR_TAG="cargo_third_party"
	LCNR_SOURCE="${WORKDIR}/cargo_home/gentoo"
	lcnr_install_files

	# ecompress/unxz is being stupid
	mv "${S}/COPYING/COPYING.lzma"{,_} || die

	LCNR_TAG="${PN}"
	LCNR_SOURCE="${S}"
	lcnr_install_files
}

pkg_postinst() {
	if ! use libclamav-only ; then
		if use systemd ; then
			tmpfiles_process clamav.conf
		fi
	fi
	if use milter ; then
einfo
einfo "For simple instructions how to setup the clamav-milter read the"
einfo "clamav-milter.README.gentoo in /usr/share/doc/${PF}"
einfo
	fi
	local databases=( "${EROOT}"/var/lib/clamav/main.c[lv]d )
	if [[ ! -f "${databases}" ]] ; then
ewarn
ewarn "You must run freshclam manually to populate the virus database before"
ewarn "starting clamav for the first time."
ewarn
	fi
	if ! systemd_is_booted ; then
ewarn
ewarn "This version of ClamAV provides separate OpenRC services for clamd,"
ewarn "freshclam, clamav-milter, and clamonacc. The clamd service now starts"
ewarn "only the clamd daemon itself. You should add freshclam (and perhaps"
ewarn "clamav-milter) to any runlevels that previously contained clamd."
ewarn
	fi
}

# OILEDMACHINE-OVERLAY-META-EBUILD-CHANGES:  LICENSE-variable-changes, update-jit-for-llvm-14-to-15
