#!/bin/bash
#
# Copyright (c) 2023 Orson Teodoro <orsonteodoro@hotmail.com>.  All rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

TRIPLE_ID=$(cat /proc/version | cut -f 3 -d " ")
EXTRAVERSION="${TRIPLE_ID%-*}"
EXTRAVERSION="${EXTRAVERSION#*-}"
PV="${TRIPLE_ID%%-*}"
ARCH="${TRIPLE_ID##*-}"
if [[ -e /etc/tcca-${PV}-${EXTRAVERSION}-${ARCH}.conf ]] ; then
	source /etc/tcca-${PV}-${EXTRAVERSION}-${ARCH}.conf
fi

# TCCA - TCP Congestion Control Algorithm
TCCA_BAD="${TCCA_BAD:-bbr2}"
TCCA_BULK_FG="${TCCA_BULK_FG:-cubic}"
TCCA_BULK_SEND="${TCCA_BULK_SEND:-pcc}"
TCCA_FAIR_SERVER="${TCCA_FAIR_SERVER:-bbr2}"
TCCA_THROUGHPUT_SERVER="${TCCA_THROUGHPUT_SERVER:-dctcp}"
TCCA_STREAMING="${TCCA_STREAMING:-westwood}"
TCCA_REC="${TCCA_REC:-bbr}"
TCCA_GAMING="${TCCA_GAMING:-bbr2}"
TCCA_MULTI_SMALL="${TCCA_MULTI_SMALL:-hybla}"
TCCA_MULTI_LARGE="${TCCA_MULTI_LARGE:-bbr}"
TCCA_MULTI_BG="${TCCA_MULTI_BG:-vegas}"
TCCA_RELIABLE="${TCCA_RELIABLE:-cubic}"
TCCA_RESET="${TCCA_RESET:-cubic}"
TCCA_RURAL="${TCCA_RURAL:-hybla}"
TCCA_WWW_CLIENT="${TCCA_WWW_CLIENT:-vegas}"

# This is for loading modules or TCP CC selection from non-root user.
# sudo is for command line only
# pkexec is for GUI desktop environments or command line
TCCA_ELEVATE_PRIV="${TCCA_ELEVATE_PRIV:-pkexec}" # Can be sudo, pkexec, polkit, root, none

MY_NAME=$(basename "$0")

ARGV=( $@ )
USE_CASE="${1}"
shift
PN="${1}"
shift
PN_ARGS=( $@ )

print_help() {
echo
echo "${MY_NAME} - Helper script to setup the TCP Congestion Control Algorithm"
echo "for new connections for the kernel"
echo
	if [[ "${TCCA_ELEVATE_PRIV}" =~ ("pkexec"|"polkit"|"sudo") ]] ; then
echo "${MY_NAME} [use-case|menu-item] [cmd] [args]"
	else
echo "${MY_NAME} [use-case|menu-item]"
	fi
echo
echo "Use cases:"
echo
echo "  bulk - For large serial downloads as foreground"
echo "       bulk-download                                             (alias)"
echo "       download                                                  (alias)"
echo "  bulk-send - For large uploads over the Internet"
echo "  multi-large - For multiple large downloads that each take > 20s as foreground to complete"
echo "  multi-small - For multiple small downloads that each take <= 20s as foreground to complete"
echo "  fair - For servers"
echo "       http-server                                               (alias)"
echo "       gaming-server                                             (alias)"
echo "  gaming - For gaming clients"
echo "       gaming-client                                             (alias)"
echo "  reliable - For a bug free experience"
echo "  reset - For resetting the TCP Congestion Control"
echo "  multi - For non-disruptive parallel downloads in the background"
echo "       multi-download                                            (alias)"
echo "       ftp-server                                                (alias)"
echo "       p2p                                                       (alias)"
echo "       torrent                                                   (alias)"
echo "  rec - For live stream production or VoIP"
echo "       recording                                                 (alias)"
echo "       streamer                                                  (alias)"
echo "       voip                                                      (alias)"
echo "  rural - For rural connections"
echo "       satellite                                                 (alias)"
echo "  streaming - For receiving live streams"
echo "       live                                                      (alias)"
echo "       live-streaming                                            (alias)"
echo "       online-radio                                              (alias)"
echo "       radio                                                     (alias)"
echo "  streaming-server - For streaming servers"
echo "       media-server                                              (alias)"
echo "  bad - For bad connections"
echo "       packet-loss                                               (alias)"
echo "  www - For browsing without streaming"
echo "       http-client                                               (alias)"
echo "       www-client                                                (alias)"
echo
echo "Menu item:"
echo
echo "  --help - Print this help"
echo "  --status - For printing TCP Congestion Control details"
echo "  --use=<alg> - For using the algorithm directly"
echo
	if [[ "${TCCA_ELEVATE_PRIV}" =~ ("pkexec"|"polkit"|"sudo") ]] ; then
echo "[cmd]    - program to run (optional)"
echo "[args]   - list of arguments to pass to the program (optional)"
echo
	fi
}

unset TCCA_MAP
declare -A TCCA_MAP=(
	["bulk"]="${TCCA_BULK_FG}"
	["bulk-download"]="${TCCA_BULK_FG}"
	["download"]="${TCCA_BULK_FG}"

	["bulk-send"]="${TCCA_BULK_SEND}"

	["multi-large"]="${TCCA_MULTI_LARGE}"

	["multi-small"]="${TCCA_MULTI_SMALL}"

	["fair"]="${TCCA_FAIR_SERVER}"
	["http-server"]="${TCCA_FAIR_SERVER}"
	["gaming-server"]="${TCCA_FAIR_SERVER}"

	["gaming"]="${TCCA_GAMING}"
	["gaming-client"]="${TCCA_GAMING}"

	["reliable"]="${TCCA_RELIABLE}"

	["reset"]="${TCCA_RESET}"

	["multi"]="${TCCA_MULTI_BG}"
	["multi-download"]="${TCCA_MULTI_BG}"
	["ftp-server"]="${TCCA_MULTI_BG}"
	["p2p"]="${TCCA_MULTI_BG}"
	["torrent"]="${TCCA_MULTI_BG}"

	["rec"]="${TCCA_STREAMING_REC}"
	["streamer"]="${TCCA_STREAMING_REC}"
	["voip"]="${TCCA_STREAMING_REC}"

	["rural"]="${TCCA_RURAL}"
	["satellite"]="${TCCA_RURAL}"

	["streaming"]="${TCCA_STREAMING}"
	["live"]="${TCCA_STREAMING}"
	["live-streaming"]="${TCCA_STREAMING}"
	["online-radio"]="${TCCA_STREAMING}"
	["radio"]="${TCCA_STREAMING}"

	["streaming-server"]="${TCCA_THROUGHPUT_SERVER}"
	["media-server"]="${TCCA_THROUGHPUT_SERVER}"

	["bad"]="${TCCA_BAD}"
	["packet-loss"]="${TCCA_BAD}"

	["www"]="${TCCA_WWW_CLIENT}"
	["www-client"]="${TCCA_WWW_CLIENT}"
	["http-client"]="${TCCA_WWW_CLIENT}"
)

print_status() {
echo
echo "The Current TCP Congestion Control algorithm for new connections:"
echo
	echo -e "\t"$(cat /proc/sys/net/ipv4/tcp_congestion_control)
echo
echo "Allowed algorithms:"
echo
	echo -e "\t"$(cat /proc/sys/net/ipv4/tcp_available_congestion_control)
echo
echo "Available kernel modules:"
echo
	pushd /lib/modules/${PV}-${EXTRAVERSION}-${ARCH}/kernel/net/ipv4/ 2>/dev/null 1>/dev/null
		echo -e "\t"$(ls tcp_*.ko* | sed -e "s|.ko.*$||g")
	popd 2>/dev/null 1>/dev/null
echo
}

process_options() {
	local x
	for x in ${ARGV[@]} ; do
		case ${x} in
			--help)
				print_help
				exit 0
				;;
			--status)
				print_status
				exit 0
				;;
			--use=*)
				set_tcca $(echo "${x}" | cut -f 2 -d "=" | sed -e "s|^tcp_||g")
				exit 0
				;;
			*)
				;;
		esac
	done
}

check_dependencies() {
	if [[ -n "${DISPLAY}" ]] && ! which pkexec 2>/dev/null 1>/dev/null ; then
		echo "You must install polkit"
		exit 1
	fi
	if [[ -z "${USE_CASE}" ]] ; then
		echo "You must choose a use case.  See ${MY_NAME} --help."
		exit 1
	else
		echo -e "USE_CASE:\t\t\t${USE_CASE}"
	fi
}

_set_tcca_polkit() {
	local alg="${1}"
	echo -e "TCP_CONGESTION_CONTROL_ALG:\t${alg}"
	if ls /lib/modules/${PV}-${EXTRAVERSION}-${ARCH}/kernel/net/ipv4/tcp_${alg}.ko* 2>/dev/null 1>/dev/null ; then
echo
echo "Loading kernel module for ${alg}"
echo
		pkexec modprobe tcp_${alg}
	fi
echo
echo "Setting TCP Congestion Control algorithm"
echo
	echo "${alg}" \
		| pkexec dd \
			of=/proc/sys/net/ipv4/tcp_congestion_control \
			oflag=append \
			conv=notrunc
}

_set_tcca_sudo() {
	local alg="${1}"
	echo -e "TCP_CONGESTION_CONTROL_ALG:\t${alg}"
	if ls /lib/modules/${PV}-${EXTRAVERSION}-${ARCH}/kernel/net/ipv4/tcp_${alg}.ko* 2>/dev/null 1>/dev/null ; then
echo
echo "Loading kernel module for ${alg}"
echo
		sudo modprobe tcp_${alg}
	fi
echo
echo "Setting TCP Congestion Control algorithm"
echo
	echo "${alg}" \
		| sudo dd \
			of=/proc/sys/net/ipv4/tcp_congestion_control \
			oflag=append \
			conv=notrunc
}

_set_tcca_root() {
	local alg="${1}"
	echo -e "TCP_CONGESTION_CONTROL_ALG:\t${alg}"
	if ls /lib/modules/${PV}-${EXTRAVERSION}-${ARCH}/kernel/net/ipv4/tcp_${alg}.ko* 2>/dev/null 1>/dev/null ; then
echo
echo "Loading kernel module for ${alg}"
echo
		modprobe tcp_${alg}
	fi
echo
echo "Setting TCP Congestion Control algorithm"
echo
	echo "${alg}" \
		| dd \
			of=/proc/sys/net/ipv4/tcp_congestion_control \
			oflag=append \
			conv=notrunc
}

set_tcca() {
	local alg="${1}"
	if [[ "${alg,,}" == "bbr3" ]] ; then
		alg="bbr"
	fi
	if [[ "${TCCA_ELEVATE_PRIV}" =~ ("pkexec"|"polkit") ]] ; then
		_set_tcca_polkit "${alg}"
	elif [[ "${TCCA_ELEVATE_PRIV}" == "sudo" ]] ; then
		_set_tcca_sudo "${alg}"
	else
		_set_tcca_root "${alg}"
	fi
}

select_tcca() {
	local key="${USE_CASE,,}"
	if [[ "${!TCCA_MAP[@]}" =~ "${key}" ]] ; then
		set_tcca ${TCCA_MAP[${key}]}
	else
		echo "${key} does not exist."
		echo "Valid values: ${!TCCA_MAP[@]}"
		exit 1
	fi
}

run_pn() {
	if [[ -n "${PN}" ]] ; then
		echo "Running ${PN} ${PN_ARGS[@]}"
		"${PN}" "${PN_ARGS[@]}"
	fi
}

main() {
	process_options
	check_dependencies
	select_tcca
	if [[ "${TCCA_ELEVATE_PRIV}" =~ ("pkexec"|"polkit"|"sudo") ]] ; then
		run_pn
	fi
}

main
