#!/bin/bash
# Copyright 2024-2026 Orson Teodoro <orsonteodoro@hotmail.com>
# License:  MIT

# A wrapper script for Ollama

# Originally the reason why the sandbox was added to prevent path traversal
# vulnerabilities leading to information disclosure or security problems
# associated with new projects.

# CWE-653 mitigation, currently the use of the sandbox is to mitigate against
# trojanized LLMs, agents without guardrails that produce malware.

ARGS=( ${@} )

LIBDIR="@LIBDIR@"
OLLAMA_BACKEND=${OLLAMA_BACKEND:-"@OLLAMA_BACKEND@"}
OLLAMA_FIREJAIL=${OLLAMA_FIREJAIL:-"@OLLAMA_FIREJAIL@"}

# CWE-401, DoS
# Kill process on OOM for FAFO users
# -1000 never killed
# 0 default
# <500 mid-back of the OOM kill list
# >=500 mid-front of the OOM kill list
# 1000 front of the line OOM kill
OLLAMA_OOM=${OLLAMA_OOM:-500}

main() {
	if [[ "${OLLAMA_BACKEND}" == "rocm" ]] ; then
		export LD_LIBRARY_PATH="/opt/rocm/lib:${LD_LIBRARY_PATH}"
	elif [[ "${OLLAMA_BACKEND}" == "cuda" ]] ; then
		export LD_LIBRARY_PATH="/opt/cuda/${LIBDIR}:${LD_LIBRARY_PATH}"
	fi
	export LD_LIBRARY_PATH="/usr/lib/ollama/${LIBDIR}/${OLLAMA_BACKEND}:${LD_LIBRARY_PATH}"
	export PATH="/usr/lib/ollama/${LIBDIR}/${OLLAMA_BACKEND}:/usr/lib/ollama/bin:${PATH}"
	cd "/usr/lib/ollama/${LIBDIR}/${OLLAMA_BACKEND}" || exit 1

	local FIREJAIL_ARGS=()

	if [[ -n "${LD_LIBRARY_PATH}" ]] ; then
		FIREJAIL_ARGS+=(
			--env=LD_LIBRARY_PATH=${LD_LIBRARY_PATH}
		)
	fi

	if [[ -n "${OLLAMA_CONTEXT_LENGTH}" ]] ; then
		FIREJAIL_ARGS+=(
			--env=OLLAMA_CONTEXT_LENGTH=${OLLAMA_CONTEXT_LENGTH}
		)
	fi

	if [[ -n "${OLLAMA_FLASH_ATTENTION}" ]] ; then
		FIREJAIL_ARGS+=(
			--env=OLLAMA_FLASH_ATTENTION=${OLLAMA_FLASH_ATTENTION}
		)
	fi

	if [[ -n "${OLLAMA_KV_CACHE_TYPE}" ]] ; then
		FIREJAIL_ARGS+=(
			--env=OLLAMA_KV_CACHE_TYPE=${OLLAMA_KV_CACHE_TYPE}
		)
	fi

	if [[ -n "${OLLAMA_OOM}" ]] ; then
		FIREJAIL_ARGS+=(
			--oom=${OLLAMA_OOM}
		)
	fi

	if [[ -n "${OLLAMA_ORIGINS}" ]] ; then
		FIREJAIL_ARGS+=(
			--env=OLLAMA_ORIGINS=${OLLAMA_ORIGINS}
		)
	fi

	if [[ -n "${OLLAMA_VULKAN}" ]] ; then
		FIREJAIL_ARGS+=(
			--env=OLLAMA_VULKAN=${OLLAMA_VULKAN}
		)
	fi

	if [[ "${OLLAMA_FIREJAIL}" == "1" ]] ; then
		/usr/bin/firejail --profile=ollama ${FIREJAIL_ARGS[@]} "/usr/lib/ollama/bin/ollama" "${ARGS[@]}" || exit $?
	else
		"/usr/lib/ollama/bin/ollama" "${ARGS[@]}" || exit $?
	fi
}

main
