#!/bin/bash
# Copyright 2024 Orson Teodoro <orsonteodoro@hotmail.com>
# License:  MIT

# Wrapper script for ollama

ARGS=( ${@} )
BACKEND=${BACKEND:-"@BACKEND@"}

declare -A backends=(
	"cpu"
	"cpu_avx2"
	"cpu_avx"
	"rocm"
	"cuda_v12"
	"cuda_v11"
)

main() {
	cd "/usr/lib64/ollama/${BACKEND}" || exit 1
	../ollama ${ARGS[@]}
}

main
