#!/bin/bash
# Copyright 2024-2026 Orson Teodoro <orsonteodoro@hotmail.com>
# License:  MIT

# A wrapper script for Ollama

# Originally the reason why the sandbox was added to prevent path traversal
# vulnerabilities leading to information disclosure or security problems
# associated with new projects.

# CWE-653 mitigation, currently the use of the sandbox is to mitigate against
# trojanized LLMs, agents without guardrails that produce malware.

ARGS=( ${@} )

LIBDIR="@LIBDIR@"
OLLAMA_BACKEND=${OLLAMA_BACKEND:-"@OLLAMA_BACKEND@"}
OLLAMA_FIREJAIL=${OLLAMA_FIREJAIL:-"@OLLAMA_FIREJAIL@"}

# CWE-401, DoS
# Kill process on OOM for FAFO users
# -1000 never killed
# 0 default
# <500 mid-back of the OOM kill list
# >=500 mid-front of the OOM kill list
# 1000 front of the line OOM kill
OLLAMA_OOM=${OLLAMA_OOM:-500}

main() {
	if [[ "${OLLAMA_BACKEND}" == "rocm" ]] ; then
		export LD_LIBRARY_PATH="/opt/rocm/lib:${LD_LIBRARY_PATH}"
	elif [[ "${OLLAMA_BACKEND}" == "cuda" ]] ; then
		export LD_LIBRARY_PATH="/opt/cuda/${LIBDIR}:${LD_LIBRARY_PATH}"
	fi
	export LD_LIBRARY_PATH="/usr/lib/ollama/${LIBDIR}/${OLLAMA_BACKEND}:${LD_LIBRARY_PATH}"
	export PATH="/usr/lib/ollama/${LIBDIR}/${OLLAMA_BACKEND}:/usr/lib/ollama/bin:${PATH}"
	cd "/usr/lib/ollama/${LIBDIR}/${OLLAMA_BACKEND}" || exit 1

	local FIREJAIL_ARGS=()

# See also https://github.com/ollama/ollama/blob/v0.30.6/envconfig/config.go
	# Editor blocked to limit implied blast radius of saving or accessing home folder.
	local L=(
		"CUDA_VISIBLE_DEVICES"
		#"EDITOR"
		"GGML_VK_VISIBLE_DEVICES"
		"GPU_DEVICE_ORDINAL"
		"HIP_VISIBLE_DEVICES"
		"HSA_OVERRIDE_GFX_VERSION"
		"HTTP_PROXY"
		"http_proxy"
		"HTTPS_PROXY"
		"https_proxy"
		"LD_LIBRARY_PATH"
		"LLAMA_ARG_FIT"
		"LLAMA_ARG_FIT_TARGET"
		"NO_PROXY"
		"no_proxy"
		"OLLAMA_DEBUG"
		"OLLAMA_DEBUG_LOG_REQUESTS"
		"OLLAMA_CONTEXT_LENGTH"
		#"OLLAMA_EDITOR"
		"OLLAMA_FLASH_ATTENTION"
		"OLLAMA_GPU_OVERHEAD"
		"OLLAMA_GO_TEMPLATE"
		"OLLAMA_IGPU_ENABLE"
		"OLLAMA_KV_CACHE_TYPE"
		"OLLAMA_HOST"
		"OLLAMA_KEEP_ALIVE"
		"OLLAMA_LLM_LIBRARY"
		"OLLAMA_LOAD_TIMEOUT"
		"OLLAMA_MAX_LOADED_MODELS"
		"OLLAMA_MAX_TRANSFER_STREAMS"
		"OLLAMA_MAX_QUEUE"
		"OLLAMA_MODELS"
		"OLLAMA_NO_CLOUD"
		"OLLAMA_NOHISTORY"
		"OLLAMA_NOPRUNE"
		"OLLAMA_NUM_PARALLEL"
		"OLLAMA_REMOTES"
		"OLLAMA_ORIGINS"
		"OLLAMA_SCHED_SPREAD"
		"OLLAMA_VULKAN"
		"ROCR_VISIBLE_DEVICES"
		"VISUAL"
	)

	local x
	for x in "${L[@]}" ; do
		[[ "${x}" == "LOCALAI_ARGS" ]] && continue
		if [[ -n "${!x}" ]] ; then
			FIREJAIL_ARGS+=(
				--env=${x}="${!x}"
			)
			export ${x}
		fi
	done


	if [[ -n "${OLLAMA_OOM}" ]] ; then
		FIREJAIL_ARGS+=(
			--oom=${OLLAMA_OOM}
		)
	fi

	if [[ "${OLLAMA_FIREJAIL}" == "1" ]] ; then
		/usr/bin/firejail --profile=ollama ${FIREJAIL_ARGS[@]} "/usr/lib/ollama/bin/ollama" "${ARGS[@]}" || exit $?
	else
		"/usr/lib/ollama/bin/ollama" "${ARGS[@]}" || exit $?
	fi
}

main
