#!/bin/bash
rm log_$(hostname)/*
cp /usr/bin/bfgminer-gpu ./
cp /usr/bin/bfgminer-cpu ./
cp /usr/share/bfgminer/opencl/*.cl ./
chown boincadm:boinc *.cl bfgminer-{gpu,cpu}
DBUSER=$(xml sel -t -v "/boinc/config/db_user" config.xml)
DBPASS=$(xml sel -t -v "/boinc/config/db_passwd" config.xml)
DBNAME=$(xml sel -t -v "/boinc/config/db_name" config.xml)


mysql -B -N --user="${DBUSER}" --password="${DBPASS}" -e "USE ${DBNAME}; TRUNCATE TABLE app;"
mysql -B -N --user="${DBUSER}" --password="${DBPASS}" -e "USE ${DBNAME}; TRUNCATE TABLE app_version;"
mysql -B -N --user="${DBUSER}" --password="${DBPASS}" -e "USE ${DBNAME}; TRUNCATE TABLE host;"
mysql -B -N --user="${DBUSER}" --password="${DBPASS}" -e "USE ${DBNAME}; TRUNCATE TABLE host_app_version;"
mysql -B -N --user="${DBUSER}" --password="${DBPASS}" -e "USE ${DBNAME}; TRUNCATE TABLE platform;"
mysql -B -N --user="${DBUSER}" --password="${DBPASS}" -e "USE ${DBNAME}; TRUNCATE TABLE profile;"
mysql -B -N --user="${DBUSER}" --password="${DBPASS}" -e "USE ${DBNAME}; TRUNCATE TABLE result;"
mysql -B -N --user="${DBUSER}" --password="${DBPASS}" -e "USE ${DBNAME}; TRUNCATE TABLE user;"
mysql -B -N --user="${DBUSER}" --password="${DBPASS}" -e "USE ${DBNAME}; TRUNCATE TABLE workunit;"

unset DBUSER
unset DBPASS

#xml ed -L -d "/boinc/app/name[text()='example_app']/.." project.xml

rm -rf apps/*
#./update_app bfgminer-cpu bfgminer "Boinc BFGMiner" 3.10.5 x86_64-pc-linux-gnu 7.4.42 "" 3
./update_app bfgminer-cpu bfgminer "Boinc BFGMiner" 3.10.5 x86_64-pc-linux-gnu 7.4.42 sse2 3
#./update_app bfgminer-cpu bfgminer "Boinc BFGMiner" 3.10.5 x86_64-pc-linux-gnu 7.4.42 sse3 3
./update_app bfgminer-gpu bfgminer "Boinc BFGMiner" 3.10.5 x86_64-pc-linux-gnu 7.4.42 opencl_ati5_cat132 3 diablo130302.cl  diakgcn121016.cl  phatk121016.cl  poclbm130302.cl  scrypt130511.cl
#./make_masterwu wu_nosimd_noocl       wu_nosimd_noocl        bfgminer templates/workunit_template_nosimd_noocl.xml       templates/results_template_nosimd_noocl.xml       0
./make_masterwu wu_sse2               wu_sse2                bfgminer templates/workunit_template_sse2.xml               templates/results_template_sse2.xml               1
#./make_masterwu wu_sse3               wu_sse3                bfgminer templates/workunit_template_sse3.xml               templates/results_template_sse3.xml               1
./make_masterwu wu_opencl_ati5_cat132 wu_opencl_ati5_cat132  bfgminer templates/workunit_template_opencl_ati5_cat132.xml templates/results_template_opencl_ati5_cat132.xml 2

#./auto_generate_wu wu_nosimd_noocl 10
./auto_generate_wu wu_sse2 10
#./auto_generate_wu wu_sse3 10
./auto_generate_wu wu_opencl_ati5_cat132 10

/etc/init.d/apache2 stop
sleep 5
/etc/init.d/apache2 start
/etc/init.d/boinc stop
sleep 5
/etc/init.d/boinc start
/etc/init.d/boinc-server-coinking stop
sleep 5
/etc/init.d/boinc-server-coinking start

rm *.cl bfgminer-{gpu,cpu}
