#!/bin/bash
INSTALL_PATH="@INSTALL_PATH@"
export PATH="${INSTALL_PATH}/:${PATH}"
cd "${INSTALL_PATH}"
if [[ -n "${DISPLAY}" ]] ; then
	"${INSTALL_PATH}/electron" start --plugins="local-dir:${INSTALL_PATH}/resources/app/plugins" "${@}"
else
	"${INSTALL_PATH}/electron" --enable-features="UseOzonePlatform" --ozone-platform-hint="wayland" start --plugins="local-dir:${INSTALL_PATH}/resources/app/plugins" "${@}"
fi
