#!/bin/bash
NODE_VERSION=${NODE_VERSION}
NODE_ENV=${NODE_ENV}
export PATH="${INSTALL_DIR}/node_modules/.bin:${PATH}"
cd "${INSTALL_DIR}/examples/electron"
"${INSTALL_DIR}/node_modules/.bin/theia" start --plugins=local-dir:../../plugins "${@}"
