#!/bin/bash

USE_SYSTEM_LLVM=${USE_SYSTEM_LLVM:-1}

main() {
	IFS=$'\n'
	local rocm_libs=(
		"libamdhip64.so"
		"libhsa-runtime64.so"
		"librdc_bootstrap.so"
		"librocm-dbgapi.so"
		"librocm_smi64.so"
		"librocrand.so"
		"libroctracer64.so"
	)
	local llvm_libs=(
		"libLLVMCore.so"
		"libLLVMFrontendOpenMP.so"
		"libLLVMOption.so"
		"libLLVMSupport.so"
	)
	local clang_libs=(
		"libclangBasic.so"
	)
	local l
	for path in $(find /usr/lib64/rocm/*/{bin,lib64,lib} 2>/dev/null) ; do
		local is_so=0
		local is_exe=0
		if file "${path}" | grep -q "shared object" ; then
			is_so=1
		elif file "${path}" | grep -q "ELF.*executable" ; then
			is_exe=1
		fi

		if (( ${is_so} || ${is_exe} )) ; then
			local reason=""
			local reason_llvm=""
			local reason_clang=""
			local needs_rpath_patch=0
			local needs_rpath_patch_clang=0
			local needs_rpath_patch_llvm=0
			for l in "${rocm_libs[@]}" ; do
				if ldd "${path}" 2>/dev/null | grep -q "${l}" ; then
					if ldd "${path}" 2>/dev/null | grep "${l}" | grep -q "/rocm/" ; then
						:;
					else
						needs_rpath_patch=1
					fi
				fi
			done

			if [[ "${USE_SYSTEM_LLVM}" == "1" ]] ; then
				for l in "${llvm_libs[@]}" ; do
					if ldd "${path}" 2>/dev/null | grep -q "${l}" ; then
						if ldd "${path}" 2>/dev/null | grep "${l}" | grep -q "/rocm/" ; then
							:;
						else
							needs_rpath_patch_llvm=1
						fi
					fi
				done

				for l in "${clang_libs[@]}" ; do
					if ldd "${path}" 2>/dev/null | grep -q "${l}" ; then
						if ldd "${path}" 2>/dev/null | grep "${l}" | grep -q "/rocm/" ; then
							:;
						else
							needs_rpath_patch_clang=1
						fi
					fi
				done
			fi

			if [[ "${USE_SYSTEM_LLVM}" != "1" ]] ; then
				for l in "${llvm_libs[@]}" ; do
					if ldd "${path}" 2>/dev/null | grep -q "${l}" ; then
						if ldd "${path}" 2>/dev/null | grep "${l}" | grep -q "lib/llvm" ; then
							:;
						else
							needs_rpath_patch_llvm=1
						fi
					fi
				done

				for l in "${clang_libs[@]}" ; do
					if ldd "${path}" 2>/dev/null | grep -q "${l}" ; then
						if ldd "${path}" 2>/dev/null | grep "${l}" | grep -q "lib/llvm" ; then
							:;
						else
							needs_rpath_patch_clang=1
						fi
					fi
				done
			fi

			if (( ${needs_rpath_patch} )) ; then
				echo "missing rpath for ${path} ; Reason:  ${reason}"
			fi

			if (( ${needs_rpath_patch_clang} )) ; then
				echo "missing rpath for ${path} ; Reason:  ${reason_clang} (clang)"
			fi

			if (( ${needs_rpath_patch_llvm} )) ; then
				echo "missing rpath for ${path} ; Reason:  ${reason_llvm} (llvm)"
			fi

			if ldd "${path}" 2>/dev/null | grep -q "not found" ; then
				echo "missing rpath for ${path} ; Reason:  (not found)"
			fi
		fi
	done
	IFS=$' \t\n'
}


main
