# Copyright 2024-2026 Orson Teodoro <orsonteodoro@hotmail.com>
# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

DISTUTILS_EXT=1
DISTUTILS_USE_PEP517="maturin"
PYTHON_COMPAT=( "python3_"{10..12} )
RUST_MAX_VER="1.91.1" # Inclusive
RUST_MIN_VER="1.91.1" # LLVM 21.1
RUST_PV="${RUST_MIN_VER}"

# Found in the crates folder
CRATES_EXCLUDED="
jiter-python-0.14.0
"

# Generated by "./convert-cargo-lock.sh 0.14.0 0.14.0"
CRATES="
ahash-0.8.12
aho-corasick-1.1.4
anes-0.1.6
anstyle-1.0.14
anyhow-1.0.102
autocfg-1.5.0
bitflags-2.11.1
bitvec-1.0.1
bumpalo-3.20.2
cast-0.3.0
cc-1.2.61
cfg-if-1.0.4
ciborium-0.2.2
ciborium-io-0.2.2
ciborium-ll-0.2.2
clap-4.6.1
clap_builder-4.6.0
clap_lex-1.1.0
codspeed-2.10.1
codspeed-criterion-compat-2.10.1
codspeed-criterion-compat-walltime-2.10.1
colored-2.2.0
criterion-plot-0.5.0
crossbeam-deque-0.8.6
crossbeam-epoch-0.9.18
crossbeam-utils-0.8.21
crunchy-0.2.4
either-1.15.0
equivalent-1.0.2
find-msvc-tools-0.1.9
foldhash-0.1.5
funty-2.0.0
futures-core-0.3.32
futures-task-0.3.32
futures-util-0.3.32
getrandom-0.3.4
getrandom-0.4.2
half-2.7.1
hashbrown-0.15.5
hashbrown-0.17.0
heck-0.5.0
hermit-abi-0.5.2
id-arena-2.3.0
indexmap-2.14.0
is-terminal-0.4.17
itertools-0.10.5
itoa-1.0.18
jiter-0.14.0
js-sys-0.3.97
lazy_static-1.5.0
leb128fmt-0.1.0
lexical-parse-float-1.0.6
lexical-parse-integer-1.0.6
lexical-util-1.0.7
libc-0.2.186
log-0.4.29
memchr-2.8.0
num-bigint-0.4.6
num-integer-0.1.46
num-traits-0.2.19
once_cell-1.21.4
oorandom-11.1.5
paste-1.0.15
pin-project-lite-0.2.17
plotters-0.3.7
plotters-backend-0.3.7
plotters-svg-0.3.7
portable-atomic-1.13.1
prettyplease-0.2.37
proc-macro2-1.0.106
pyo3-0.28.3
pyo3-build-config-0.28.3
pyo3-ffi-0.28.3
pyo3-macros-0.28.3
pyo3-macros-backend-0.28.3
python3-dll-a-0.2.15
quote-1.0.45
radium-0.7.0
rayon-1.12.0
rayon-core-1.13.0
r-efi-5.3.0
r-efi-6.0.0
regex-1.12.3
regex-automata-0.4.14
regex-syntax-0.8.10
rustversion-1.0.22
same-file-1.0.6
semver-1.0.28
serde-1.0.228
serde_core-1.0.228
serde_derive-1.0.228
serde_json-1.0.149
shlex-1.3.0
slab-0.4.12
smallvec-1.15.1
syn-2.0.117
tap-1.0.1
target-lexicon-0.13.5
tinytemplate-1.2.1
unicode-ident-1.0.24
unicode-xid-0.2.6
uuid-1.23.1
version_check-0.9.5
walkdir-2.5.0
wasip2-1.0.3+wasi-0.2.9
wasip3-0.4.0+wasi-0.3.0-rc-2026-01-06
wasm-bindgen-0.2.120
wasm-bindgen-macro-0.2.120
wasm-bindgen-macro-support-0.2.120
wasm-bindgen-shared-0.2.120
wasm-encoder-0.244.0
wasm-metadata-0.244.0
wasmparser-0.244.0
web-sys-0.3.97
winapi-util-0.1.11
windows_aarch64_gnullvm-0.52.6
windows_aarch64_msvc-0.52.6
windows_i686_gnu-0.52.6
windows_i686_gnullvm-0.52.6
windows_i686_msvc-0.52.6
windows-link-0.2.1
windows-sys-0.59.0
windows-sys-0.61.2
windows-targets-0.52.6
windows_x86_64_gnu-0.52.6
windows_x86_64_gnullvm-0.52.6
windows_x86_64_msvc-0.52.6
wit-bindgen-0.51.0
wit-bindgen-0.57.1
wit-bindgen-core-0.51.0
wit-bindgen-rust-0.51.0
wit-bindgen-rust-macro-0.51.0
wit-component-0.244.0
wit-parser-0.244.0
wyz-0.5.1
zerocopy-0.8.48
zerocopy-derive-0.8.48
zmij-1.0.21
"

inherit distutils-r1 cargo edo

KEYWORDS="~amd64"
S="${WORKDIR}/${PN}-${PV}"
S_PROJECT="${WORKDIR}/${PN}-${PV}"
S_PYTHON="${WORKDIR}/${PN}-${PV}/crates/jiter-python"
SRC_URI="
$(cargo_crate_uris ${CRATES})
https://github.com/pydantic/jiter/archive/refs/tags/v${PV}.tar.gz
	-> ${P}.tar.gz
"

DESCRIPTION="Fast iterable JSON parser"
HOMEPAGE="
	https://github.com/pydantic/jiter
	https://pypi.org/project/jiter
"
LICENSE="
	MIT
"
RESTRICT="mirror"
SLOT="0/"$(ver_cut "1-2" "${PV}")
IUSE+="
bench dev linting
ebuild_revision_1
"
RDEPEND+="
"
DEPEND+="
	${RDEPEND}
"
BDEPEND+="
	dev-util/maturin[${PYTHON_USEDEP}]
	dev? (
		dev-python/maturin[${PYTHON_USEDEP}]
		dev-python/pytest[${PYTHON_USEDEP}]
		dev-python/pytest-pretty[${PYTHON_USEDEP}]
		dev-python/dirty-equals[${PYTHON_USEDEP}]
	)
	bench? (
		dev-python/orjson[${PYTHON_USEDEP}]
		dev-python/ujson[${PYTHON_USEDEP}]
	)
	linting? (
		dev-util/ruff[${PYTHON_USEDEP}]
	)
"
DOCS=( "README.md" )

pkg_setup() {
	python_setup
	rust_pkg_setup
}

src_unpack() {
	unpack ${A}
#	die # For manual lockfile update
	cp -a \
		"${FILESDIR}/${PV}/Cargo."* \
		"${S}" \
		|| die
	cargo_src_unpack
}

src_prepare() {
	distutils-r1_src_prepare
}

python_configure() {
	:
}

src_configure() {
	cargo_src_configure
	distutils-r1_src_configure
}

python_compile() {
	cargo_src_compile
	pushd "${S_PYTHON}" >/dev/null 2>&1 || die
		edo maturin \
			pep517 \
			build-wheel \
			-i "${PYTHON}" \
			--compatibility off \
			--auditwheel=skip \
			--jobs=1 \
			--offline \
			--manifest-path "${S_PROJECT}/Cargo.toml"

		local d="${WORKDIR}/${PN}-${PV}-${EPYTHON/./_}/install"
		mkdir -p "${d}/usr/bin" || die
		local pyv="${EPYTHON/python/}"
		pyv="${pyv/./}"
		local wheel_path=$(realpath "${S_PROJECT}/target/wheels/${PN}-${PV}-cp${pyv}-cp${pyv}-linux_"*".whl")
		distutils_wheel_install "${d}" \
			"${wheel_path}"
	popd >/dev/null 2>&1 || die
}

src_compile() {
	distutils-r1_src_compile
}

src_install() {
	distutils-r1_src_install
	docinto "licenses"
	dodoc "LICENSE"
}

# OILEDMACHINE-OVERLAY-META:  CREATED-EBUILD
