# Copyright 2026 Orson Teodoro <orsonteodoro@hotmail.com>
# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# @ECLASS: secure-versions.eclass
# @MAINTAINER: Orson Teodoro <orsonteodoro@hotmail.com>
# @SUPPORTED_EAPIS: 7 8 9
# @BLURB: secure versions for node/electron
# @DESCRIPTION:
# Install *only* secure versions for node/electron micropackages.

case ${EAPI:-0} in
	[789]) ;;
	*) die "${ECLASS}: EAPI ${EAPI:-0} not supported" ;;
esac

if [[ -z "${_SECURE_VERSION_NODE_ECLASS}" ]] ; then
_SECURE_VERSION_NODE_ECLASS=1

# Entries below must have a NODE_ or NODE_<SLOT>_ prefix to prevent clobbering.
# Use NODE_<SLOT>_ for multislot version sensitive (See engines.node)
# Use NODE_ for version agnostic

# Multislot
# aws-sdk
# bcrypt
# eslint
# express
# firebase-admin
# jest
# mongoose
# mongodb
# node-sass
# npm
# pg
# sharp
# typescript
# uuid
NODE_24_GRPC_GRPC_JS_PV=${NODE_24_GRPC_GRPC_JS_PV:-"1.9.16"} # typescript@^5.1.x uses @types/node@20
NODE_24_PROTOBUFJS_PV=${NODE_24_PROTOBUFJS_PV:-"7.6.3"} # @types/node@18, deprecated var
NODE_24_PROTOBUFJS_UTF8_PV=${NODE_24_PROTOBUFJS_UTF8_PV:-"1.1.1"}
NODE_24_ELECTRON_PV=${NODE_24_ELECTRON_PV:-"44.1.1"} # node 24.19.0, chromium 152.0.7977.65

# Unislot
NODE_AI_PV=${NODE_AI_PV:-"5.0.52"}
NODE_AT_APIDEVTOOLS_JSON_SCHEMA_REF_PARSER_11_PV=${NODE_AT_APIDEVTOOLS_JSON_SCHEMA_REF_PARSER_11_PV:-"11.2.0"}
NODE_AT_NEONDATABASE_SERVERLESS_PV=${NODE_AT_NEONDATABASE_SERVERLESS_PV:-"1.1.0"}
NODE_AT_OPENTELEMETRY_CORE_PV=${NODE_AT_OPENTELEMETRY_CORE_PV:-"2.8.0"}
NODE_AT_OPENTELEMETRY_PROPAGATOR_JAEGER_PV=${NODE_AT_OPENTELEMETRY_PROPAGATOR_JAEGER_PV:-"2.9.0"}
NODE_AT_OCTOKIT_PLUGIN_PAGINATE_REST_PV=${NODE_AT_OCTOKIT_PLUGIN_PAGINATE_REST_PV:-"9.2.2"}
NODE_AT_OCTOKIT_REQUEST_PV=${NODE_AT_OCTOKIT_REQUEST_PV:-"8.4.1"}
NODE_AT_OCTOKIT_REQUEST_ERROR_PV=${NODE_AT_OCTOKIT_REQUEST_ERROR_PV:-"5.1.1"}
NODE_BETTER_AUTH_PV=${NODE_BETTER_AUTH_PV:-"1.6.27"}
NODE_ADM_ZIP_PV=${NODE_ADM_ZIP_PV:-"0.6.0"}
NODE_AJV_PV=${NODE_AJV_PV:-"8.18.0"}
NODE_APP_BUILDER_LIB_PV=${NODE_APP_BUILDER_LIB_PV:-"26.15.0"}
NODE_BUILDER_UTIL_RUNTIME_PV=${NODE_BUILDER_UTIL_RUNTIME_PV:-"9.7.0"}
NODE_BETTER_AUTH_PV=${NODE_BETTER_AUTH_PV:-"1.6.22"}
NODE_DOMPURIFY_PV=${NODE_DOMPURIFY_PV:-"3.4.11"}
NODE_DRIZZLE_ORM_PV=${NODE_DRIZZLE_ORM_PV:-"0.45.2"}
NODE_ESBUILD_PV=${NODE_ESBUILD_PV:-"0.28.1"}
NODE_FILE_TYPE_PV=${NODE_FILE_TYPE_PV:-"21.3.2"}
NODE_FORM_DATA_PV=${NODE_FORM_DATA_PV:-"4.0.6"} # Deprecated use NODE_FORM_DATA_4_PV
NODE_JS_YAML_PV=${NODE_JS_YAML_PV:-"4.2.0"}
NODE_JSON5_PV=${NODE_JSON5_PV:-"1.0.2"}
NODE_JSONDIFFPATCH_PV=${NODE_JSONDIFFPATCH_PV:-"0.7.2"}
NODE_LOADER_UTILS_PV=${NODE_LOADER_UTILS_PV:-"1.4.1"}
NODE_NEXT_PV=${NODE_NEXT_PV:-"15.5.21"}
NODE_PG_PV=${NODE_PG_PV:-"8.23.0"}
NODE_POSTGRES_PV=${NODE_POSTGRES_PV:-"3.4.9"}
NODE_OPENTELEMETRY_CORE_PV=${NODE_OPENTELEMETRY_CORE_PV:-"2.8.0"}
NODE_QS_PV=${NODE_QS_PV:-"6.14.1"}
NODE_TAR_PV=${NODE_TAR_PV:-"7.5.21"}
NODE_TMP_PV=${NODE_TMP_PV:-"0.2.6"}
NODE_TOUGH_COOKIE_PV=${NODE_TOUGH_COOKIE_PV:-"4.1.3"}
NODE_UNDICI_PV=${NODE_UNDICI_PV:-"6.27.0"}
NODE_POSTCSS_PV=${NODE_POSTCSS_PV:-"8.5.23"}
NODE_SHARP_PV=${NODE_SHARP_PV:-"0.35.3"}
NODE_SERIALIZE_JAVASCRIPT_PV=${NODE_SERIALIZE_JAVASCRIPT_PV:-"7.0.3"}
NODE_UUID_PV=${NODE_UUID_PV:-"11.1.1"}

# Multislot
NODE_AT_TYPES_REACT_19_PV=${NODE_AT_TYPES_REACT_PV:-"19.2.14"}
NODE_FAST_XML_PARSER_5_PV=${NODE_FAST_XML_PARSER_5_PV:-"5.7.0"}
NODE_FAST_XML_PARSER_4_PV=${NODE_FAST_XML_PARSER_4_PV:-"4.1.2"}
NODE_FORM_DATA_4_PV=${NODE_FORM_DATA_4_PV:-"4.0.6"}
NODE_FORM_DATA_2_PV=${NODE_FORM_DATA_2_PV:-"2.5.6"}
NODE_MINIMATCH_9_PV=${NODE_MINIMATCH_9_PV:-"9.0.7"}
NODE_PROTOBUFJS_8_PV=${NODE_PROTOBUFJS_8_PV:-"8.6.6"}
NODE_REACT_19_PV=${NODE_REACT_PV:-"19.2.4"}
NODE_REACT_DOM_19_PV=${NODE_REACT_DOM_PV:-"19.2.4"}
NODE_VITE_8_PV=${NODE_VITE_8_PV:-"8.0.16"}
NODE_VITE_7_PV=${NODE_VITE_8_PV:-"7.6.3"}

fi
