# Copyright 2026 Orson Teodoro <orsonteodoro@hotmail.com>
# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# @ECLASS: secure-versions.eclass
# @MAINTAINER: Orson Teodoro <orsonteodoro@hotmail.com>
# @SUPPORTED_EAPIS: 7 8 9
# @BLURB: secure versions for node/electron
# @DESCRIPTION:
# Install *only* secure versions for node/electron micropackages.

case ${EAPI:-0} in
	[789]) ;;
	*) die "${ECLASS}: EAPI ${EAPI:-0} not supported" ;;
esac

if [[ -z "${_SECURE_VERSION_NODE_ECLASS}" ]] ; then
_SECURE_VERSION_NODE_ECLASS=1

# Entries below must have a NODE_ or NODE_<SLOT>_ prefix to prevent clobbering.
# Use NODE_<SLOT>_ for multislot version sensitive (See engines.node)
# Use NODE_ for version agnostic

# Multislot
# aws-sdk
# bcrypt
# eslint
# express
# firebase-admin
# jest
# mongoose
# mongodb
# node-sass
# npm
# pg
# sharp
# typescript
# uuid
NODE_24_GRPC_GRPC_JS_PV=${NODE_24_GRPC_GRPC_JS_PV:-"1.9.16"} # typescript@^5.1.x uses @types/node@20
NODE_24_ELECTRON_PV=${NODE_24_ELECTRON_PV:-"44.4.3"} # node 24.21.0, chromium 152.0.7977.130
NODE_22_ELECTRON_PV=${NODE_22_ELECTRON_PV:-"35.7.4"} # node 22.16.0, chromium 134.0.6998.205

# Unislot
NODE_AI_PV=${NODE_AI_PV:-"5.0.52"}
NODE_AT_APIDEVTOOLS_JSON_SCHEMA_REF_PARSER_11_PV=${NODE_AT_APIDEVTOOLS_JSON_SCHEMA_REF_PARSER_11_PV:-"11.2.0"}
NODE_AT_NEONDATABASE_SERVERLESS_PV=${NODE_AT_NEONDATABASE_SERVERLESS_PV:-"1.1.0"}
NODE_AT_OPENTELEMETRY_CORE_PV=${NODE_AT_OPENTELEMETRY_CORE_PV:-"2.8.0"}
NODE_AT_OPENTELEMETRY_PROPAGATOR_JAEGER_PV=${NODE_AT_OPENTELEMETRY_PROPAGATOR_JAEGER_PV:-"2.9.0"}
NODE_AT_OCTOKIT_PLUGIN_PAGINATE_REST_PV=${NODE_AT_OCTOKIT_PLUGIN_PAGINATE_REST_PV:-"9.2.2"}
NODE_AT_OCTOKIT_REQUEST_PV=${NODE_AT_OCTOKIT_REQUEST_PV:-"8.4.1"}
NODE_AT_OCTOKIT_REQUEST_ERROR_PV=${NODE_AT_OCTOKIT_REQUEST_ERROR_PV:-"5.1.1"}
NODE_AT_REMIX_RUN_ROUTER_PV=${NODE_AT_REMIX_RUN_ROUTER_PV:-"1.23.4"}
NODE_AT_XMLDOM_XMLDOM_PV=${NODE_AT_XMLDOM_XMLDOM_PV:-"0.9.12"}
NODE_BETTER_AUTH_PV=${NODE_BETTER_AUTH_PV:-"1.6.27"}
NODE_ADM_ZIP_PV=${NODE_ADM_ZIP_PV:-"0.6.0"}
NODE_AJV_PV=${NODE_AJV_PV:-"8.18.0"}
NODE_APP_BUILDER_LIB_PV=${NODE_APP_BUILDER_LIB_PV:-"26.15.0"}
NODE_BUILDER_UTIL_RUNTIME_PV=${NODE_BUILDER_UTIL_RUNTIME_PV:-"9.7.0"}
NODE_BETTER_AUTH_PV=${NODE_BETTER_AUTH_PV:-"1.6.22"}
NODE_DOMPURIFY_PV=${NODE_DOMPURIFY_PV:-"3.4.11"}
NODE_DRIZZLE_ORM_PV=${NODE_DRIZZLE_ORM_PV:-"0.45.2"}
NODE_ESBUILD_PV=${NODE_ESBUILD_PV:-"0.28.1"}
NODE_FILE_TYPE_PV=${NODE_FILE_TYPE_PV:-"21.3.2"}
NODE_FLATTED_PV=${NODE_FLATTED_PV:-"3.4.4"}
NODE_GLOB_PV=${NODE_GLOB_PV:-"10.5.0"}
NODE_JSON5_PV=${NODE_JSON5_PV:-"1.0.2"}
NODE_JSONDIFFPATCH_PV=${NODE_JSONDIFFPATCH_PV:-"0.7.2"}
NODE_LOADER_UTILS_PV=${NODE_LOADER_UTILS_PV:-"1.4.1"}
NODE_LODASH_PV=${NODE_LODASH_PV:-"4.17.23"}
NODE_NEXT_PV=${NODE_NEXT_PV:-"16.3.3"}
NODE_PG_PV=${NODE_PG_PV:-"8.23.0"}
NODE_POSTGRES_PV=${NODE_POSTGRES_PV:-"3.4.9"}
NODE_PROTOBUFJS_UTF8_PV=${NODE_PROTOBUFJS_UTF8_PV:-"1.1.1"} # deprecated
NODE_OPENTELEMETRY_CORE_PV=${NODE_OPENTELEMETRY_CORE_PV:-"2.8.0"}
NODE_QS_PV=${NODE_QS_PV:-"6.14.1"}
NODE_TAR_PV=${NODE_TAR_PV:-"7.5.21"}
NODE_TMP_PV=${NODE_TMP_PV:-"0.2.6"}
NODE_TOUGH_COOKIE_PV=${NODE_TOUGH_COOKIE_PV:-"4.1.3"}
NODE_UNDICI_PV=${NODE_UNDICI_PV:-"6.28.0"}
NODE_POSTCSS_PV=${NODE_POSTCSS_PV:-"8.5.23"}
NODE_SAX_PV=${NODE_SAX_PV:-"1.6.1"}
NODE_SHARP_PV=${NODE_SHARP_PV:-"0.35.4"}
NODE_SERIALIZE_JAVASCRIPT_PV=${NODE_SERIALIZE_JAVASCRIPT_PV:-"7.1.1"}
NODE_SHELL_QUOTE_PV=${NODE_SHELL_QUOTE_PV:-"1.9.0"}
NODE_UUID_PV=${NODE_UUID_PV:-"11.1.1"} # Deprecated

# Multislot
# EOL is not supported.  Typically multislots within 1 year is supported.
NODE_AT_TYPES_REACT_19_PV=${NODE_AT_TYPES_REACT_PV:-"19.2.14"}
NODE_BABEL_CORE_8_PV=${NODE_BABEL_CORE_8_PV:-"8.0.6"}
NODE_BABEL_CORE_7_PV=${NODE_BABEL_CORE_7_PV:-"7.29.7"}
NODE_BABEL_RUNTIME_8_PV=${NODE_BABEL_RUNTIME_8_PV:-"8.0.5"}
NODE_BABEL_RUNTIME_7_PV=${NODE_BABEL_RUNTIME_7_PV:-"7.29.7"}
NODE_FAST_XML_PARSER_5_PV=${NODE_FAST_XML_PARSER_5_PV:-"5.7.0"}
NODE_FAST_XML_PARSER_4_PV=${NODE_FAST_XML_PARSER_4_PV:-"4.1.2"}
NODE_FORM_DATA_4_PV=${NODE_FORM_DATA_4_PV:-"4.0.6"}
NODE_FORM_DATA_2_PV=${NODE_FORM_DATA_2_PV:-"2.5.6"}
NODE_IMMUTABLE_5_PV=${NODE_IMMUTABLE_5_PV:-"5.1.9"}
NODE_IMMUTABLE_4_PV=${NODE_IMMUTABLE_4_PV:-"4.3.9"}
NODE_IMMUTABLE_3_PV=${NODE_IMMUTABLE_3_PV:-"3.8.4"}
NODE_JS_YAML_5_PV=${NODE_JS_YAML_5_PV:-"5.4.2"}
NODE_JS_YAML_4_PV=${NODE_JS_YAML_4_PV:-"4.3.2"}
NODE_JS_YAML_3_PV=${NODE_JS_YAML_3_PV:-"3.15.2"}
NODE_JWS_4_PV=${NODE_JWS_4_PV:-"4.0.1"}
NODE_JWS_3_PV=${NODE_JWS_3_PV:-"3.2.3"}
NODE_LINKIFY_IT_6_PV=${NODE_LINKIFY_IT_6_PV:-"6.1.0"}
NODE_LINKIFY_IT_5_PV=${NODE_LINKIFY_IT_5_PV:-"5.0.2"}
NODE_MINIMATCH_9_PV=${NODE_MINIMATCH_9_PV:-"9.0.7"}
NODE_PICOMATCH_4_PV=${NODE_PICOMATCH_4_PV:-"4.0.7"}
NODE_PICOMATCH_3_PV=${NODE_PICOMATCH_3_PV:-"3.0.2"}
NODE_PICOMATCH_2_PV=${NODE_PICOMATCH_2_PV:-"2.3.2"}
NODE_PROTOBUFJS_8_PV=${NODE_PROTOBUFJS_8_PV:-"8.6.6"}
NODE_PROTOBUFJS_7_PV=${NODE_PROTOBUFJS_7_PV:-"7.5.5"}
NODE_REACT_19_PV=${NODE_REACT_19_PV:-"19.2.7"}
NODE_REACT_DOM_19_PV=${NODE_REACT_DOM_19_PV:-"19.2.7"}
NODE_REACT_ROUTER_8_PV=${NODE_REACT_ROUTER_8_PV:-"8.4.0"}
NODE_REACT_ROUTER_7_PV=${NODE_REACT_ROUTER_7_PV:-"7.18.4"}
NODE_REACT_ROUTER_6_PV=${NODE_REACT_ROUTER_6_PV:-"6.30.6"}
NODE_ROLLUP_4_PV=${NODE_ROLLUP_4_PV:-"4.63.4"}
NODE_ROLLUP_3_PV=${NODE_ROLLUP_3_PV:-"3.30.0"}
NODE_ROLLUP_2_PV=${NODE_ROLLUP_2_PV:-"2.80.0"}
NODE_SVGO_4_PV=${NODE_SVGO_4_PV:-"4.1.0"}
NODE_SVGO_3_PV=${NODE_SVGO_3_PV:-"3.3.5"}
NODE_SVGO_2_PV=${NODE_SVGO_2_PV:-"2.8.4"}
NODE_STORYBOOK_10_PV=${NODE_STORYBOOK_10_PV:-"10.6.0"} # Same as @storybook/core, @storybook/theming
NODE_STORYBOOK_9_PV=${NODE_STORYBOOK_9_PV:-"9.1.20"} # Same as @storybook/core, @storybook/theming
NODE_STORYBOOK_8_PV=${NODE_STORYBOOK_8_PV:-"8.6.18"} # Same as @storybook/core, @storybook/theming
NODE_STORYBOOK_7_PV=${NODE_STORYBOOK_7_PV:-"7.6.24"} # Same as @storybook/core, @storybook/theming
NODE_UUID_14_PV=${NODE_UUID_14_PV:-"14.0.2"}
NODE_UUID_13_PV=${NODE_UUID_13_PV:-"13.0.2"}
NODE_UUID_12_PV=${NODE_UUID_12_PV:-"12.0.1"}
NODE_UUID_11_PV=${NODE_UUID_11_PV:-"11.1.1"}
NODE_VITE_8_PV=${NODE_VITE_8_PV:-"8.3.0"}
NODE_VITE_7_PV=${NODE_VITE_7_PV:-"7.3.6"}
NODE_VITE_6_PV=${NODE_VITE_6_PV:-"6.4.3"}
NODE_VITEST_5_PV=${NODE_VITEST_5_PV:-"5.0.1"}
NODE_VITEST_4_PV=${NODE_VITEST_4_PV:-"4.1.11"}
NODE_VITEST_3_PV=${NODE_VITEST_3_PV:-"3.2.7"}
NODE_WEBPACK_5_PV=${NODE_WEBPACK_5_PV:-"5.111.1"}

fi
