#!/usr/bin/perl -w
package hipvars;

$HIP_BASE_VERSION_MAJOR = "@HIP_BASE_VERSION_MAJOR@";
$HIP_BASE_VERSION_MINOR = "@HIP_BASE_VERSION_MINOR@";

$isWindows = 0;
$HIP_PATH='/usr';
$ROCM_PATH='/usr';
$CLANG_RESOURCE_DIR='@EPREFIX@/usr/lib/clang/@CLANG_SLOT@';
$CUDA_PATH='/opt/cuda';
$HSA_PATH='/usr';
$HIP_CLANG_PATH='@EPREFIX@/usr/lib/llvm/@LLVM_SLOT@/bin';
$HIP_ROCCLR_HOME=$HIP_PATH;
$HIP_PLATFORM='amd';
$HIP_COMPILER = "clang";
$HIP_RUNTIME = "rocclr";
$HIP_VERSION_MAJOR = $HIP_BASE_VERSION_MAJOR;
$HIP_VERSION_MINOR = $HIP_BASE_VERSION_MINOR;
$HIP_VERSION_PATCH = "@HIP_VERSION_PATCH@";
$HIP_VERSION="$HIP_VERSION_MAJOR.$HIP_VERSION_MINOR.$HIP_VERSION_PATCH";
