#!/usr/bin/perl -w
package hipvars;

$HIP_BASE_VERSION_MAJOR = "@HIP_BASE_VERSION_MAJOR@";
$HIP_BASE_VERSION_MINOR = "@HIP_BASE_VERSION_MINOR@";

$isWindows = 0;
$HIP_PATH='@ESYSROOT@/usr';
$ROCM_PATH='@ESYSROOT@/usr';
$CLANG_RESOURCE_DIR='@ESYSROOT_CLANG_PATH_COND@';
$CUDA_PATH='@ESYSROOT@/opt/cuda';
$HSA_PATH='@ESYSROOT@/usr';
$HIP_CLANG_PATH='@ESYSROOT_LLVM_PATH_COND@/bin';
$HIP_CLANG_INCLUDE_PATH='@ESYSROOT_CLANG_PATH_COND@/include';
$HIP_ROCCLR_HOME=$HIP_PATH;
$HIP_PLATFORM='amd';
$HIP_COMPILER = "clang";
$HIP_RUNTIME = "rocclr";
$HIP_VERSION_MAJOR = $HIP_BASE_VERSION_MAJOR;
$HIP_VERSION_MINOR = $HIP_BASE_VERSION_MINOR;
$HIP_VERSION_PATCH = "@HIP_VERSION_PATCH@";
$HIP_VERSION="$HIP_VERSION_MAJOR.$HIP_VERSION_MINOR.$HIP_VERSION_PATCH";
