#!/usr/bin/perl -w
package hipvars;

$HIP_BASE_VERSION_MAJOR = "@HIP_BASE_VERSION_MAJOR@";
$HIP_BASE_VERSION_MINOR = "@HIP_BASE_VERSION_MINOR@";
$HIP_BASE_VERSION_PATCH = "@HIP_BASE_VERSION_PATCH@";
$ESYSROOT = "@ESYSROOT@"
$HIP_PATH = "$ESYSROOT/@ROCM_PATH@"
$ROCM_PATH = "$ESYSROOT/@ROCM_PATH@"
$CLANG_PATH = "@CLANG_PATH@"
$LLVM_PATH = "@LLVM_PATH@"

$isWindows = 0;
$doubleQuote = "\"";
$CLANG_RESOURCE_DIR = "$ESYSROOT/$CLANG_PATH";
$CUDA_PATH = "$ESYSROOT/opt/cuda";
$HSA_PATH = "$ESYSROOT/$ROCM_PATH";
$HIP_CLANG_PATH = "$ESYSROOT/$LLVM_PATH/bin";
$HIP_CLANG_INCLUDE_PATH = "$CLANG_PATH/include";
$HIP_ROCCLR_HOME = $HIP_PATH;
$HIP_PLATFORM = "@HIP_PLATFORM@";
$HIP_COMPILER = "@HIP_COMPILER@";
$HIP_RUNTIME = "@HIP_RUNTIME@";
$HIP_VERSION_MAJOR = $HIP_BASE_VERSION_MAJOR;
$HIP_VERSION_MINOR = $HIP_BASE_VERSION_MINOR;
$HIP_VERSION_PATCH = $HIP_BASE_VERSION_PATCH;
$HIP_VERSION = "$HIP_VERSION_MAJOR.$HIP_VERSION_MINOR.$HIP_VERSION_PATCH";
